// /* NOTE - THIS WILL *NEVER* FULLY TRANSLATE THE GAME, BUT IT WILL ATLEAST PROVIDE YOU WITH FLAVOUR TEXTS IN YOUR PREFERRED LANGUAGE */ //

const finnish = {
  // identifier
  language_id: "finnish",
  finnish: "Suomi",
  english: "English",

  // Races
  human_name: "Ihminen",
  orc_name: "Puoli-Örkki",
  elf_name: "Puoli-Haltia",
  ashen_name: "Kalpea",

  // Character Window
  core_stats: "Yleiset statsit",
  core_resistances: "puolustukset",
  status_resistances: "vastustuskyky",
  passives: "Passiiviset Kyvyt",
  poison_status: "Myrkky",
  burning_status: "Palaminen",
  curse_status: "Kirous",
  stun_status: "Tainnutus",
  bleed_status: "Verenvuoto",

  str_tt: `<i>${icons["str"]}<i>Voima parantaa <i>${icons["melee"]}<i>voima aseiden vahinkoa 2%,\n ja parantaa maksimi taakkaa 0.5`,
  dex_tt: `<i>${icons["dex"]}<i>Taito parantaa <i>${icons["ranged"]}<i>taito aseiden vahinkoa 2%,\nsekä nostaa <i>${icons["hitChance"]}<i>iskujen tarkkuutta ja <i>${icons["evasion"]}<i>väistelyä 0.25`,
  vit_tt: `<i>${icons["vit"]}<i>Sisu parantaa <i>${icons["health"]}<i>terveyttä 5,\n<i>${icons["regenHp_icon"]}<i>terveyden palautimista 1%\n ja maksimi taakkaa 1`,
  int_tt: `<i>${icons["int"]}<i>Älykkyys parantaa <i>${icons["mana"]}<i>taikaa 2,\n<i>${icons["regenMp_icon"]}<i>taian palautimista 1%\n ja <i>${icons["damage"]}<i>maagista vahinkoa 2%`,
  cun_tt: `<i>${icons["cun"]}<i>Oveluus parantaa <i>${icons["critDamage"]}<i>krit vahinkoa 1.5%,\n ja <i>${icons["critDamage"]}<i>krit mahdollisuutta 0.4%`,
  critDamage_tt: `<i>${icons["critDamage"]}<i>Krit vahinko on kertoja joka parantaa kriittisiä iskuja.`,
  critChance_tt: `<i>${icons["critDamage"]}<i>Krit mahdollisuus kertoo millä todennäköisyydellä iskusi on kriittinen.`,
  hitChance_tt: `<i>${icons["hitChance"]}<i>Iskujen tarkkuus parantaa mahdollisuuttasi osua viholliseesi. \nVerrataan vastustajan <i>${icons["evasion"]}<i>väistelyyn.`,
  evasion_tt: `<i>${icons["evasion"]}<i>Väistely parantaa mahdollisuuttasi välttää vahinkoa. \nVerrataan vastustajan <i>${icons["hitChance"]}<i>iskujen tarkkuuteen.`,
  atk_speed_tt: `Tämä on <i>${icons["attackSpeed_icon"]}<i>Hyökkäys nopeutesi.\nKun nopeus on yli 100% voit hyökätä useasti yhden vuoron aikana. \nAlle 100% ja et voi hyöätä joillain kierroksilla.`,
  mov_speed_tt: `Tämä on <i>${icons["movementSpeed_icon"]}<i>Liikkumis nopeutesi. \nYli 100% nopeus antaa sinun liikkua useita ruutuja yhden vuoron aikana. \nAlle 100% hidastaa liikettäsi joillain vuoroilla.`,

  physical_tt: `<i>${icons["physical_armor"]}<i>Fyysinen Panssari nostaa puolustusta fyysisiä iskuja vastaan. \n<i>${icons["slash_icon"]}<i>Viilto, <i>${icons["crush_icon"]}<i>Murskaus ja <i>${icons["pierce_icon"]}<i>Lävistys vahinko alennettu 0.4% joka tasolla. \nPanssarin maksimi arvo on 200.`,
  magical_tt: `<i>${icons["magical_armor"]}<i>Maaginen Suojaus nostaa puolustusta maagisia iskuja vastaan. \n<i>${icons["magic_icon"]}<i>Taika, <i>${icons["dark_icon"]}<i>Pimeä ja <i>${icons["divine_icon"]}<i>Pyhä vahinko alennettu 0.4% joka tasolla. \nPanssarin maksimi arvo on 200.`,
  elemental_tt: `<i>${icons["elemental_armor"]}<i>Elementaalinen Suojaus nostaa puolustusta elementaalisia iskuja vastaan. \n<i>${icons["fire_icon"]}<i>Tuli, <i>${icons["lightning_icon"]}<i>Sähkö ja <i>${icons["ice_icon"]}<i>Jää vahinko alennettu 0.4% joka tasolla. \nPanssarin maksimi arvo on 200.`,

  resistances_tt: "Vahinko tyypin puolustus vähentää saman tyyppistä tulevaa vahinkoa mainitulla prosentilla.",
  stat_resist_tt: `Efektin vastustus laskee sen tekemää vahinkoa mainitulla prosentilla. \n\nSe myös antaa mahdollisuuden kokonaan vastustaa efekti. \n\nKun efekti on täysin vastustettu, se ei tee mitään.`,

  // Status Resists
  poisonDefense: "Myrkytyksen vastustus",
  burningDefense: "Palamisen vastustus",
  curseDefense: "Kirouksen vastustus",
  stunDefense: "Tainnuttamisen vastustus",
  bleedDefense: "Verenvuodon vastustus",

  // Messages
  test_message: "<c>white<c>Tervetuloa <c>gold<c>Dungeons of Tavaraeniin<c>white<c>!",
  follow_slimes: "<c>white<c>Jatka <c>gold<c>limojen<c>white<c> seuraamista saadaksesi reilun tappelun!",
  beach_episode: "<c>gold<c>Luurangot<c>white<c> ovat valloittaneet rannan, valmistaudu ratkomaan luisia ongelmia!",
  // Technical stuff
  changeWordOrder: true,
  mana: "Taika",
  health: "Terveys",
  str: "Voima",
  dex: "Taito",
  vit: "Sisu",
  int: "Älykkyys",
  cun: "Oveluus",
  crush: "Murskaava",
  slash: "Viiltävä",
  pierce: "Lävistävä",
  magic: "Maaginen",
  fire: "Tuli",
  ice: "Jää",
  dark: "Pimeä",
  divine: "Pyhä",
  lightning: "Sähkö",
  crush_def: "Murskaus",
  slash_def: "Viilto",
  pierce_def: "Lävistävyys",
  magic_def: "Maaginen",
  fire_def: "Tuli",
  ice_def: "Jää",
  dark_def: "Pimeä",
  divine_def: "Pyhä",
  lightning_def: "Sähkö",
  hpMax: "Terveyttä",
  mpMax: "Taikaa",
  hitChance: "Iskujen tarkkuus",
  evasion: "Väistely",
  sight: "Näköä",
  increases: "Nostaa",
  decreases: "Alentaa",
  damage: "Vahinkoa",
  movementSpeed: "Liikkumis Nopeus",
  attackSpeed: "Hyökkäys Nopeus",
  by: "",
  strV: "Voima",
  strP: "Voima%",
  vitV: "Sisu",
  vitP: "Sisu%",
  dexV: "Taito",
  dexP: "Taito%",
  intV: "Älykkyys",
  intP: "Älykkyys%",
  hpV: "Terveys",
  hpP: "Terveys%",
  mpV: "Taika",
  mpP: "Taika%",
  resistAllV: "Puolustus",
  resistAllP: "Puolustus%",
  physicalDefP: "Fyysinen Panssari%",
  magicalDefP: "Maaginen Suojaus%",
  elementalDefP: "Elementaalinen Suojaus%",
  hitChanceV: "Iskujen tarkkuus",
  hitChanceP: "Iskujen tarkkuus%",
  evasionV: "Väistely",
  evasionP: "Väistely%",
  critChanceV: "Krit Mahdollisuus",
  critChanceP: "Krit Mahdollisuus",
  critDamageV: "Krit Vahinko",
  critDamageP: "Krit Vahinko",
  movementSpeedV: "Liikkumis nopeus",
  attackSpeedV: "Hyökkäys nopeus",
  status_effect: "Tila efekti",
  status_effects: "Tila efektit",
  last: "Efektin kesto",
  lasts_for: "Efekti kestää",
  resist: "Puolustus",
  silence_text: "Taikasi on estetty!",
  silence: "Estää taian!",
  concentration_text: "Et kykene keskittymään!",
  concentration_req: "Vaatii keskittymisen",
  concentration: "Estää keskittymisen!",
  heal_power: "Parannus voima",
  type: "Tyyppi",
  ranged: "Kaukokäyttö",
  melee: "Lähitaistelu",
  spell: "Loitsu",
  requires_melee_weapon: "Vaatii lähitaistelu aseen",
  requires_ranged_weapon: "Vaatii kaukotaistelu aseen",
  recharge_only_in_combat: "Latautuu vain taistelussa",
  targets_self: "Kohde on oma hahmo",
  mana_cost: "Taian käyttö",
  health_cost: "Terveyden käyttö",
  health_cost_percentage: "Terveyden käyttö",
  use_range: "Käyttö matka",
  damage_multiplier: "Vahingon kerroin",
  resistance_penetration: "Puolustuksen läpäisy",
  aoe_size: "Vahinkoalueen koko",
  yes: "kyllä",
  no: "ei",
  tiles: "ruutua",
  attack: "Hyökkäys",
  heal: "Parannus",
  buff: "Tehoste/Buffi",
  movement: "Liikkuminen",
  charge: "Ryntäys",
  summon: "Kutsuntaloitsu",
  turn: "Kierros",
  turns: "kierrosta",
  turns_alt: "kierroksella",
  cooldown: "Latausaika",
  base_heal: "Parannus voima",
  map_to_hotbar: "Lisää kyky/työkalu",
  remove_from_hotbar: "Poista kyky/työkalu",
  removed_in: "Kestää",
  deals: "Aiheuttaa",
  perk_points: "Perkki pisteet",
  stat_points: "Stat pisteet",
  adventurerPerks: "Seikkailija",
  lvl_up: "Tasosi nousi! Se on nyt [LVL]!",
  regenHp: "Terveyden palautuminen",
  regenMp: "Taian palautuminen",
  regenHpP: "Terveyden palautuminen%",
  regenMpP: "Taian palautuminen%",
  of_max_hp: "Maksimi terveydestä",
  life_steal: "Terveyden riisto",
  life_steal_on_kill_1: "Kun tämä isku tappaa vihollisen, \nparannat terveyttäsi",
  life_steal_on_kill_2: "vihollisen maksimi terveydestä.",
  for_each_enemy_hit: "Jokainen vihollinen johon tämä isku osuu nostaa efektin kestoa ",
  equip: "Varusta",
  unequip: "Riisu",
  drop: "Pudota",
  pick_up: "Poimi",
  map: "Kartta",
  last_played: "Viimeksi pelattu",
  slain: `<f>36px<f><c>white<c>Sinut on <c>crimson<c><f>36px<f>surmattu!\n§<c>silver<c>\tJätit jälkeesi <v>player.grave.xp<v><i>${icons["exp_icon"]}<i>, <v>player.grave.gold<v><i>${icons["gold_icon"]}<i>`,
  respawn: "Synny [R]",
  title_screen: "Alkuruutuun",

  // Item definitions
  slash_damageSub: "Viiltävä",
  slash_damageMain: "Haavoittavan",
  crush_damageSub: "Tylppä",
  crush_damageMain: "Murskaavan",
  pierce_damageSub: "Pistävä",
  pierce_damageMain: "Lävistävän",
  magic_damageSub: "Lumottu",
  magic_damageMain: "Maagisen",
  dark_damageSub: "Pimeä",
  dark_damageMain: "Kamalan",
  divine_damageSub: "Pyhä",
  divine_damageMain: " Jumalallisen",
  fire_damageSub: "Tulinen",
  fire_damageMain: "Liekehtivän",
  lightning_damageSub: "Ukkostava",
  lightning_damageMain: "Salamoivan",
  ice_damageSub: "Jäinen",
  ice_damageMain: "Hyytävän",
  // armor defs
  slash_resistanceSub: "Suojelevainen",
  slash_resistanceMain: "Viilloilta Suojaava",
  crush_resistanceSub: "Pehmeä",
  crush_resistanceMain: "Murskaukselta Suojeleva",
  pierce_resistanceSub: "Paksu",
  pierce_resistanceMain: "Pistoilta Suojaava",
  magic_resistanceSub: "Lumottu",
  magic_resistanceMain: "Magialta Suojaava",
  dark_resistanceSub: "Pyhä",
  dark_resistanceMain: "Pimeyden Karkottava",
  divine_resistanceSub: "Kirottu",
  divine_resistanceMain: "Virsiä Karttava",
  fire_resistanceSub: "Viilentävä",
  fire_resistanceMain: "Tulenkestävä",
  lightning_resistanceSub: "Sähkönjohtava",
  lightning_resistanceMain: "Salamankestävä",
  ice_resistanceSub: "Sulattava",
  ice_resistanceMain: "Jäänmurtava",

  // Item names
  healingScrollI_name: "Parannuksen Loitsukirja I",
  manaScrollI_name: "Taianpalautuksen Loitsukirja I",
  healingPotion_weak_name: "Parantava Eliksiiri (Heikko)",
  manaPotion_weak_name: "Taikaapalauttava Eliksiiri (Heikko)",
  beer_name: "Kalja",
  dagger_name: "Tikari",
  dual_daggers_name: "Tikari Pari",
  stick_name: "Keppi",
  chippedBlade_name: "Kulunut Terä",
  longsword_name: "Pitkämiekkä",
  chippedAxe_name: "Kulunut Kirves",
  orcishAxe_name: "Örkkimäinen Kirves",
  huntingBow_name: "Metsästys Jousi",
  hiisiBow_name: "Hiiden Jousi",
  goldBow_name: "Kultainen Jousi",
  longBow_name: "Pitkäjousi",
  silverSword_name: "Hopeamiekka",
  apprenticeWand_name: "Oppilaan Sauva",
  crimsonStaff_name: "Tulinen Sauva",
  crystalWand_name: "Kristalli Sauva",
  galadorSpear_name: "Galadorin Keihäs",
  pikeMore_name: "Murhahauki",
  trollClub_name: "Peikon Puumaila",
  raggedShirt_name: "Ryysyinen Paita",
  raggedBoots_name: "Ryysyiset Jalkimet",
  raggedPants_name: "Ryysyiset Housut",
  raggedGloves_name: "Ryysyiset Hanskat",
  raggedHood_name: "Ryysyinen Huppu",
  woolHat_name: "Villahattu",
  leatherChest_name: "Nahkaliivi",
  leatherBoots_name: "Nahkakengät",
  leatherLeggings_name: "Nahkajalkasuojat",
  leatherBracers_name: "Nahkakäsisuojat",
  leatherHelmet_name: "Nahkakypärä",
  apprenticeRobe_name: "Oppilaan Kaapu",
  apprenticeBoots_name: "Oppilaan Kengät",
  apprenticePants_name: "Oppilaan Housut",
  ironArmor_name: "Rautahaarniska",
  ironBoots_name: "Rautajalkimet",
  ironLegplates_name: "Rautajalkasuojat",
  ironGauntlets_name: "Rautakäsineet",
  ironHelmet_name: "Rautakypärä",
  rangerArmor_name: "Metsästäjän Haarniska",
  rangerBoots_name: "Metsästäjän Kengät",
  rangerPants_name: "Metsästäjän Housut",
  rangerGloves_name: "Metsästäjän Hanskat",
  rangerHood_name: "Metsästäjän Huppu",
  initiateRobe_name: "Kultti Kaapu",
  initiateShoes_name: "Kultti Kengät",
  initiatePants_name: "Kultti Housut",
  initiateGloves_name: "Kultti Hanskat",
  initiateHood_name: "Kultti Huppu",
  knightArmor_name: "Ritarin Haarniska",
  knightSabatons_name: "Ritarin Jalkimet",
  knightGreaves_name: "Ritarin Jalkasuojat",
  knightGauntlets_name: "Ritarin Kintaat",
  greathelm_name: "Ritarin Kypärä",
  crownOfWisdom_name: "Viisauden Kruunu",
  lichRobes_name: "Kuolema Maagin Kaapu",
  woodenShield_name: "Puukilpi",
  ironShield_name: "Rautakilpi",
  silverShield_name: "Hopeakilpi",
  talismanOfProtection_name: "Puolustava Talismaani",
  emblemOfProtection_name: "Puolustava Tunnus",
  ringOfProtection_name: "Puolustava Sormus",
  scholarsTalisman_name: "Tieteilijän Onnekas Talismaani",
  scholarsEmblem_name: "Tieteilijän Tunnus",
  scholarsRing_name: "Tieteilijän Lumottu Sormus",
  warriorsTalisman_name: "Ylistetyn Soturin Talismaani",
  warriorsEmblem_name: "Soturin Arvostettu Tunnus",
  warriorsRing_name: "Soturin Sormus",
  loneShadesTalisman_name: "Yön Haamun Tähti Talismaani",
  loneShadesEmblem_name: "Yön Haamun Pimeä Tunnus",
  loneShadesRing_name: "Yön Haamun Kolkko Sormus",
  huntersTalisman_name: "Vanhan Metsästäjän Talismaani",
  huntersEmblem_name: "Vanhan Metsästäjän Tunnus",
  huntersRing_name: "Vanhan Metsästäjän Arvostettu Sormus",
  parryingDagger_name: "Torjuntatikari",

  // Artifacts
  part_of_set: "Osa",
  artifact_def: "Artefakti",
  artifact_set: "Artefakti sarjaa",
  artifact_two_piece: "2-palan sarja efekti",
  artifact_three_piece: "3-palan sarja efekti",
  defenderSet_name: "Puolustaja",
  guardianSet_name: "Vartija",
  scholarSet_name: "Tieteilijä",
  warriorSet_name: "Soturi",
  loneShadeSet_name: "Yön Haamu",
  hunterSet_name: "Metsien Suojelija",

  // Enemy names
  hiisi_name: "Hiisi",
  hiisiWarrior_name: "Hiisi Soturi",
  hiisiHunter_name: "Hiisi Metsästäjä",
  skeletonWarrior_name: "Luuranko Soturi",
  skeletonArcher_name: "Luuranko Jousimies",
  skeletonMage_name: "Luuranko Maagi",
  skeletonLich_name: "Luuranko Kuolema Maagi",
  soulWraith_name: "Sielujen Viikatemies",
  greySlime_name: "Harmaa Lima",
  flamingSlime_name: "Liekehtivä Lima",
  electricSlime_name: "Sähköinen Lima",
  norsemanBerserk_name: "Pohjoismies Berserkki",
  norsemanHunter_name: "Pohjoismies Metsästäjä",
  femaleOrcRaider_name: "Örkki Hyökkääjä",
  maleOrcRaider_name: "Örkki Hyökkääjä",
  orcChieftess_name: "Örkki Päällikkö",
  wildTroll_name: "Villi Peikko",
  wildStoneTroll_name: "Villi Kivipeikko",
  troll_name: "Peikko",
  stoneTroll_name: "Kivipeikko",
  enthralledKnight_name: "Hurmattu Ritari",
  spectralKnight_name: "Aave Ritari",

  // Summon names
  skeletonWarriorSummon_name: "Kutsuttu Luuranko Soturi",
  skeletonLichSummon_name: "Kutsuttu Luuranko Kuolema Maagi",
  stoneTrollSummon_name: "Kutsuttu Kivipeikko",
  dummyTarget_name: "Harhautus Nukke",
  arrowTotem_name: "Nuoli Toteemi",
  rangerWolf_name: "Susi Kumppani",

  // LOG TEXTS
  you: "",
  recovery_pl: "parantaen",
  health_points: "terveys pistettä",
  for: "aiheuttaen",
  death: "kuoli.",
  damage_from_effect_pl: "<c>white<c>[STATUS] aiheuttaa [ICON][DMG] vahinkoa kehollesi!",
  damage_from_effect: "<c>white<c>[STATUS] aiheuttaa hahmolle [TARGET] [ICON][DMG] vahinkoa.",
  player_death_log: "OLET KUOLLUT...",
  cure_pl: "Parannat itsesi!",
  cure: "[ACTOR] parantaa itsensä.",
  useConsumable: "Käytät taiallisen esineen!",
  moves_to: "liikkuu ruutuun",
  gained: "Sait",

  // WORLD TEXTS
  gained_xp: "Sait [XP] XP!",
  player_death: "SINUT SURMATTIIN!",

  // Damage types
  poison_damage: "Myrkytys",
  burning_damage: "Polttavaa",

  // Character Creation
  choose_name: "Nimi",
  choose_race: "Rotu",
  choose_class: "Class",
  fighterClass_desc: "<f>19px<f><c>silver<c>Taistelijat ovat tasapainoisia lähitaistelijoita\njotka päihittävät vastustajansa yhdistämällä \nhyvän hyökkäyksen hyvään puolustukseen.\nTaistelijana keskityt lähitaisteluun \nja pysyt kamppailussa pitkään.§\n\n",
  barbarianClass_desc: "<f>19px<f><c>silver<c>Barbaarit ovat lihaskimppuja\njotka rakastavat vaarallisia kamppailuja,\nja käyttävät suuria aseita\nyltääksen kauemmas ja tehdäkseen enemmän vahinkoa.\nBarbaarina keskityt lähitaisteluun\nottaen riskejä suurta vahinkoa varten.§\n\n",
  sorcererClass_desc: "<f>19px<f><c>silver<c>Loitsijat ovat taikaa manipuloivia älykköjä\njotka luovat suurta tuhoa kaukaa.\nLoitsijana keskityt kaukotaisteluun\nJa omaat mahtavan tuhoavaa voimaa,\njoka tosin heikentää fyysistä kehoasi.§\n\n",
  rogueClass_desc: "<f>19px<f><c>silver<c>Varjoissa kulkevat konnat lähestyvät taistelua eri tavalla,\nheikentäen vastustajiansa kaukaa alhaisilla tempuilla,\ntuhoten ne läheltä parhaimmalla hetkellä.\nKonnana jaat voimasi moniin asioihin,\nheikentäen itseäsi muihin verrattuna,\nmutta tulet toimeen tilanteessa kuin tilanteessa.§\n\n",
  rangerClass_desc: "<f>19px<f><c>silver<c>Metsästäjät suojelevat valitsemaansa metsää\ntarkasti harjatun jousen voimin,\nsamalla vahvistaen välejä susiveljen kanssa. \nMetsästäjänä keskityt kaukotaisteluun ja\njätät lähitaistelun sudellesi.§\n\n",

  // Dialog screen stuff
  openStore: "KAUPPA",
  quest: "TEHTÄVÄ",
  smith: "SEPPÄ",
  exit: "POISTU",

  // Misc
  attack_name: "tavallisten iskujen vahinkoa",
  cures_statuses: "Parantaa efektit",
  item_weight: "Paino",
  item_worth: "Arvo",
  item_grade: "Taso",
  cant_equip: "Kyvyt liian alhaiset tavaran käyttöön!",
  item_stat_bonus: "Vaikuttava kyky",
  weapon_has_great_reach: "Normaalia suurempi ase",
  resistance: "Puolustus",
  physical: "Fyysinen Panssari",
  magical: "Maaginen Suojaus",
  elemental: "Elementaalinen Suojaus",
  status_effects_enemy: "<c>white<c>Tila efektit <c>red<c><f>22px<f>viholliselle",
  status_effects_you: "<c>white<c>Tila efektit <c>lime<c><f>22px<f>sinulle",
  encumbrance: "Taakka",
  shrine_activated: "Pyhäkkö aktivoitu!",
  shrine_used: "Pyhäkön voimat ovat jo kulutettu...",
  add_ability: "Lisää kyvyn",
  requires: "Vaatii",
  critChance: "Krit mahdollisuus",
  critDamage: "Krit voima",
  resistAll: "Puolustusvoima",
  uses: "Käyttökerrat",
  amount: "Määrä",
  item_name: "Tavaran Nimi",
  item_type: "Tyyppi",
  item_rarity: "Harvinaisuus",
  item_weight_title: "Paino",
  item_worth_title: "Arvo",
  weapon: "ase",
  armor: "panssari",
  consumable: "käytettävä",
  artifact: "artefakti",
  required_stats: "Vaaditut kyvyt",
  active_if: "Aktivoituu kun",
  hp_more_than: "Terveys yli",
  hp_less_than: "Terveys alle",
  mp_more_than: "Taika yli",
  mp_less_than: "Taika alle",
  passive: "Passiivinen kyky",
  too_much_weight: "Kannat liikaa painoa! Pudota jotain!",
  summons_unit: "Kutsuu hahmon",
  summon_level: "Kutsutun hahmon taso",
  summon_last: "Kutsuttu hahmo kestää",
  total_summon_limit: "Kutsuttujen hahmojen max määrä",
  permanent: "Pysyvä",
  all_summons_damage: "Kutsuttujen hahmojen vahinko",
  all_summons_regenHp: "Kutsuttujen hahmojen terveyden palautuminen",
  two_handed_weapon: "Kahden käsen ase",
  rooted: "Et voi liikkua!",
  closest_enemy: "Etäisyys lähimpään viholliseen: ",
  expGain: "Kokemuspisteiden saanti",
  pick_item: "Poimi esine",
  pick_chest: "Avaa arkku",
  read_msg: "Lue viesti",
  talk_to_npc: "Puhu henkilölle",
  item_slot: "Varuste paikka",
  artifact1: "Talismaani",
  artifact2: "Tunnus",
  artifact3: "Sormus",
  chest: "Haarniska",
  helmet: "Kypärä",
  gloves: "Hanskat",
  legs: "Jalkasuojukset",
  boots: "Kengät",
  offhand: "Kilpi",
  buy_item: "Osta esine",
  sell_item: "Myy esine",
  quest_added: "<c>goldenrod<c>Tehtävä '<c>gold<c>[QUEST]<c>goldenrod<c>' alkanut!",
  revive: "Olet herännyt henkiin pyhäköllä!",

  // Character names
  testMerchant_name: "Karl Bauer",
  blacksmithMaroch_name: "Maroch",

  // Passive abilities
  resilience_of_the_lone_wanderer_name: "Kulkijan Sinnikkyys",
  lone_wanderer_desc: "Edes tuonela ei kykene pysäyttämään tehtäväsi suoritusta.",
  troll_regeneration_name: "Peikkojen Kestävyys",
  no_natural_regen_name: "Tukahtunut Palautuminen",
  low_natural_regen_name: "Heikentynyt Palautuminen",
  medium_natural_regen_name: "Hidas Palautuminen",
  magically_impotent_name: "Taikalukko",
  magical_regen_name: "Taian Valtaama",
  weaker_natural_ability_name: "Vaivalloinen",
  orc_frenzy_name: "Örkkimäinen Kiihko",
  orc_resilience_name: "Örkkimäinen Kestävyys",
  cornered_animal_name: "Nurkkaan Ajettu Eläin",
  slow_name: "Hidas",
  fast_name: "Nopea",
  frenzy_name: "Kiihko",
  heightened_casting_name: "Vahva Alku",
  warrior_instinct_name: "Soturin Aisti",
  confident_shot_name: "Varma Laukaisu",
  blood_rage_1_name: "Taiston Hirmu I",
  blood_rage_2_name: "Taiston Hirmu II",
  reckless_1_name: "Hyökkääjä I",
  reckless_2_name: "Hyökkääjä II",
  sense_of_danger_1_name: "Kuudes Aisti I",
  sense_of_danger_2_name: "Kuudes Aisti II",
  frantic_mana_recovery_name: "Hätäinen Taian Palautus",
  mark_of_hunter_name: "Suojelijan Merkki",
  racial_ability_orc_1_name: "Örkin Lihaksikkuus",
  racial_ability_human_1_name: "Ihmisen Kestävyys",
  racial_ability_elf_1_name: "Haltian Viisaus",
  racial_ability_ashen_1_name: "Kalpean Ketteryys",

  // Enemy types
  against_type_syntax: " vastaan",
  singular_type_slime: "Lima",
  plural_type_slime: "Limoja",
  singular_type_skeleton: "Luuranko",
  plural_type_skeleton: "Luurankoja",
  singular_type_barbarian: "Barbaari",
  plural_type_barbarian: "Barbaareja",
  singular_type_troll: "Peikko",
  plural_type_troll: "Peikkoja",
  singular_type_hiisi: "Hiisi",
  plural_type_hiisi: "Hiisiä",
  singular_type_wraith: "Haamu",
  plural_type_wraith: "Haamuja",

  // Enemy races
  against_race_syntax: " vastaan",
  singular_race_elemental: "Elementtaali",
  plural_race_elemental: "Elementtaaleja",
  singular_race_undead: "Epäkuollut",
  plural_race_undead: "Epäkuolleita",
  singular_race_human: "Ihminen",
  plural_race_human: "Ihmisiä",
  singular_race_monster: "Hirviö",
  plural_race_monster: "Hirviöitä",
  singular_race_orc: "Örkki",
  plural_race_orc: "Örkkejä",

  /* MENU */

  menu_resume: "Takaisin",
  menu_options: "Asetukset",
  menu_save_games: "Tallennetut Pelit",
  menu_main_screen: "Päämenu",
  menu_new_game: "Uusi Peli",
  menu_load_game: "Lataa Peli",

  setting_log_enemy_movement: "Kirjaa hahmojen sijainnit",
  setting_toggle_minimap: "Minikartta pois/päällä",
  setting_hide_helmet: "Piilota kypärä",
  setting_randomize_items: "Satunnaiset tavaroiden statsit",
  setting_game_language: "Pelin kieli",
  setting_hotkey_inv: "Avaa inventaario",
  setting_hotkey_char: "Avaa hahmoruutu",
  setting_hotkey_perk: "Avaa kehitysruutu",
  setting_hotkey_journal: "Avaa tehtävälista",
  setting_hotkey_codex: "Avaa codex",
  setting_hotkey_area_map: "Avaa kartta",
  setting_hotkey_ranged: "Vaihda 'Ammunta Tila'",
  setting_hotkey_move_up: "Liiku ylöspäin",
  setting_hotkey_move_down: "Liiku alaspäin",
  setting_hotkey_move_left: "Liiku vasemmalle",
  setting_hotkey_move_right: "Liiku oikealle",
  setting_hotkey_move_right_up: "Liiku koilliseen",
  setting_hotkey_move_right_down: "Liiku kaakkoon",
  setting_hotkey_move_left_up: "Liiku luoteeseen",
  setting_hotkey_move_left_down: "Liiku lounaaseen",
  setting_hotkey_interact: "Poimi esine / käytä",
  setting_hotkey_open_world_messages: "Avaa teksti ikkuna",
  setting_ui_scale: "UI skaalaus",

  open_menu: "Avaa valikko",

  space_key: "VÄLILYÖNTI",

  save_over: "Tallenna peli",
  load_game: "Jatka peliä",
  delete_save: "Poista peli",
  create_save: "Luo uusi tallennus",
  create_file: "Tallenna tiedostoon",
  load_file: "Jatka peliä tiedostosta",
  storage_used: "Tallennus tila",
  out_of_date: "\tVanhentunut \n\nTämä tallennus on vanhentunut, \nja täten ei välttämättä toimi oikein.",
  version: "Versio",
  old_save: "Vanha",

  // Grades
  common: "Yleinen",
  uncommon: "Epätavallinen",
  rare: "Harvinainen",
  mythical: "Myyttinen",
  legendary: "Legendaarinen",

  // Adjectives
  str_adjective: "Vahva",
  dex_adjective: "Näppärä",
  vit_adjective: "Sisukas",
  int_adjective: "Älykäs",
  cun_adjective: "Ovela",
  mpMax_adjective: "Henkinen",
  hpMax_adjective: "Terve",
  spellDamage_adjective: "Maaginen",
  rangedDamage_adjective: "Kaukainen",
  meleeDamage_adjective: "Fyysinen",
  evasion_adjective: "Ketterä",
  hitChance_adjective: "Tarkka",
  critDamage_adjective: "Kriittinen",
  critChance_adjective: "Kriittinen",
  slashDamage_adjective: "Viiltävä",
  crushDamage_adjective: "Murskaava",
  pierceDamage_adjective: "Lävistävä",
  magicDamage_adjective: "Maaginen",
  darkDamage_adjective: "Pimeä",
  divineDamage_adjective: "Pyhä",
  fireDamage_adjective: "Liekehtivä",
  iceDamage_adjective: "Jäinen",
  lightningDamage_adjective: "Sähköinen",
  resistAll_adjective: "Puolustava",
  regenMp_adjective: "Taianpalauttava",
  regenHp_adjective: "Parantava",
  damage_adjective: "Vahingoittava",
  movementSpeed_adjective: "Nopea",
  attackSpeed_adjective: "Kiireinen",

  // Statuses
  effect_defend_name: "Puolustaa",
  effect_poison_name: "Myrkky",
  effect_poison_desc: "Myrkky kiertää veressäsi, \nsyöden voimasi ja terveytesi.",
  effect_venom_name: "Syvä myrkky",
  effect_venom_desc: "Myrkytys heikentää kehoasi.",
  effect_rage_name: "Raivo",
  effect_rage_desc: "Hävisit äskettäin kilpailun, \nmutta vain koska vastustajasi huijasi!",
  effect_berserk_name: "Berserkki",
  effect_berserk_desc: "HAKKAA PÄÄLLE POHJANPOIKA!!!",
  effect_sunder_name: "Rikottu panssari",
  effect_sunder_desc: "Puolustuksesi on tuhottu.",
  effect_dazed_name: "Pökerryksissä",
  effect_dazed_desc: "Pääsi on sekaisin iskun jäljiltä, \njonka takia et kykene tarkkoihin liikkeisiin.",
  effect_blighted_name: "Vitsattu",
  effect_blighted_desc: "Kehosi on heikentynyt vitsauksesta.",
  effect_ward_of_aurous_name: "Aurouksen Suoja",
  effect_ward_of_aurous_desc: "Kehosi on turvassa Aurouksen suojan alla.",
  effect_battle_fury_name: "Taistelun Riemu",
  effect_battle_fury_desc: "Riemuitse ja raivoa! Adrenaniili kiertää veressä ja veri lentää!",
  effect_burning_name: "Tulessa",
  effect_burning_desc: "OLET TULESSA!",
  effect_chilled_name: "Jäinen",
  effect_chilled_desc: "Kylmyys hidastaa ja heikentää..",
  effect_summoned_name: "Kutsuntaloitsu",
  effect_summoned_desc: "Kutsuttu soturi katoaa tämän loputtua",
  effect_disoriented_name: "Sekaisin",
  effect_disoriented_desc: "Maailma pyörii ja näet kaiken kahdesti.",
  effect_dueled_name: "Kaksintaistelu",
  effect_dueled_desc: "Et voi paeta haasteesta.",
  effect_sneaky_stabbing_name: "Polttava Puukotus",
  effect_sneaky_stabbing_desc: "Tämä tulee satuttamaan kohdettasi.",
  effect_smoke_bomb_effect_name: "Savu Pommi",
  effect_smoke_bomb_effect_desc: "Savu tukkii keuhkosi ja heikentää näköäsi!",
  effect_smoke_evasion_name: "Savuverhon Peite",
  effect_smoke_evasion_desc: "Käytät savua hyväksesi ja väistelet vastustajiesi iskuja paremmin!",
  effect_encouraged_warrior_shout_name: "Rohkaistunut!",
  effect_encouraged_warrior_shout_desc: "Rohkeus virtaa veressäsi ja motivaatio menee katosta läpi!",
  effect_disheartened_warrior_shout_name: "Lannistunut",
  effect_disheartened_warrior_shout_desc: "Pelko syö voimiasi...",
  effect_heightened_senses_name: "Kärjistyneet Aistit",
  effect_heightened_senses_desc: "Aistisi kiehuvat rajoillaan ja tunnet ympäristösi kuin omat taskusi.",
  effect_paralyzed_name: "Lamautunut",
  effect_paralyzed_desc: "Et kykene käyttämään yhtäkään lihasta kehossasi.",

  // Abilities and stuff
  attack_action_desc_pl: "Teet [DMG] vahinkoa hahmoon [TARGET] hyökkäykselläsi.",
  attack_action_desc: "iskee hahmoa [TARGET], tehden [DMG] vahinkoa.",
  defend_name: "Puolusta",
  defend_desc: "Keskity suojaamaan itseäsi tällä kierroksella.",
  defend_action_desc_pl: "Keskityt puolustautumiseen.",
  defend_action_desc: "keskittyy puolustautumiseen.",
  focus_strike_name: "Tarkka Isku",
  focus_strike_desc: "Silmäile kohteesi liikettä tarkasti,\niskien sopivimmalla hetkellä.",
  focus_strike_action_desc_pl: "Isket hahmoa [TARGET] tarkasti koko voimallasi, ja teet [DMG] vahinkoa.",
  focus_strike_action_desc: "käyttää koko voimaansa iskien hahmoa",
  true_shot_name: "Tappava Nuoli",
  true_shot_desc: "Laita kaikki voimasi tähän laukaukseen,\ntähdäten vastustajasi heikkouteen.",
  true_shot_action_desc_pl: "Täytät seuraavan nuolesi taialla, ja vapautat sen jousestasi hahmoa [TARGET] kohti, tehden [DMG] vahinkoa.",
  true_shot_action_desc: "[ACTOR] ampuu kohdetta [TARGET] taialla vahvistetulla nuolella, tehden [DMG] vahinkoa.",
  first_aid_name: "Ensiapu",
  first_aid_desc: "Hoida pienet haavasi tavalla tai toisella.",
  first_aid_action_desc_pl: "Käytät ensiapu taitojasi haavoihisi, ",
  first_aid_action_desc: "käyttää ensipau taitojaan haavoihinsa, ",
  icy_javelin_name: "Jäinen Keihäs",
  icy_javelin_desc: "Ammu jäästä tehty keihäs vihollistasi päin.",
  icy_javelin_action_desc_pl: "Ammut jäästä tehdyn keihään kohti hahmoa [TARGET], tehden [DMG] vahinkoa.",
  icy_javelin_action_desc: "ampuu jäästä tehdyn keihään kohti hahmoa [TARGET], aiheuttaen [DMG] vahinkoa.",
  icy_javelin_action_desc_aoe_pl: "[TARGET] ottaa [DMG] vahinkoa räjähdyksen voimasta!",
  barbarian_rage_name: "Barbaarin Raivo",
  barbarian_rage_desc: "Aivotyö on ajan tuhlaamista,\nhaluat näkyviä tuloksia HETI!",
  barbarian_rage_action_desc_pl: "Taistelussa ei muuta tarvitse kuin vihata näitä mulkkuja ympärilläsi! HAAA!!",
  barbarian_rage_action_desc: "käy kuumana ja alkaa raivota kovaa.",
  berserk_name: "Berserkki",
  berserk_desc: "PERRRRRRRRKELE!!!!",
  berserk_action_desc_pl: "NYT KYLLÄ PALO PINNA, ON AIKA PISTÄÄ NÄITÄ HULLUJA KUONOON!!!!!!",
  berserk_action_desc: "MENETTI JÄRKENSÄ, NYT KANNATTAA VAROA TAI SE ANTAA ISÄN KÄDESTÄ!!",
  shadow_step_name: "Varjoaskel",
  shadow_step_desc: "Astu varjojen välillä nopeasti.",
  shadow_step_action_desc_pl: "Käytät varjoja hyväksesi, ja liikut haluamaasi suuntaan väläyksessä.",
  shadow_step_action: "käyttää ympäröiviä varjoja liikkuakseen nopeasti.",
  retreat_name: "Vetäydy",
  retreat_desc: "Laita vähän etäisyyttä vaaraan.",
  retreat_action_desc_pl: "Juokset rajusti pois päin!",
  retreat_action: "yrittää paeta taistelusta!",
  charge_name: "Rynnäkkö",
  charge_desc: "Ryntää vihollistasi päin rajusti.",
  charge_action_desc_pl: "Ryntäät vastustajaa [TARGET] päin, tehden [DMG] vahinkoa!",
  charge_action_desc: "ryntää päin hahmoa [TARGET], aiheuttaen [DMG] vahinkoa.",
  reap_name: "Leikkuun into",
  reap_desc: "Ryntää kohtii mehevää sielua.",
  reap_action_desc_pl: "Leikkaat ilmaa päästäksesi hahmon [TARGET] siuluun käsiksi, tehden [DMG] vahinkoa!",
  reap_action_desc: "leikkaa ympäröivää ilmaa rynnäten kohti hahmoa [TARGET], leikaten hänen sieluansa [DMG] vahingon verran!",
  purification_name: "Puhdistus",
  purification_desc: "Puhdista kehosi myrkyistä ja epäpuhtauksista.",
  blight_name: "Vitsaus",
  blight_desc: "Kiroa kohteesi vitsauksella.",
  blight_action_desc_pl: "Vitsaat hahmon [TARGET], tehden [DMG] vahinkoa, ja heikentäen häntä!",
  blight_action_desc: "vitsaa hahmon [TARGET], aiheuttaen [DMG] vahinkoa, ja heikentäen häntä.",
  fireball_name: "Tulipallo",
  fireball_desc: "Heitä tulinen räjähde vihollistesi suuntaan \nja sytytä kaikki kohteesi liekkeihin.",
  fireball_action_desc_pl: "Lähetät tulisen ammuksen kohti vastustajiesi turmiota!",
  fireball_action_desc_aoe_pl: "[TARGET] paistuu räjähtävissä liekeissä, ottaen [DMG] vahinkoa!",
  piercing_mana_bolt_name: "Maaginen Pultti",
  piercing_mana_bolt_desc: "Ammu taiallinen panos vihollistasi kohti.",
  piercing_mana_bolt_action_desc_pl: "Taiot maagisen ammuksen lentämään kohti hahmoa [TARGET], tehden [DMG] vahinkoa!",
  piercing_mana_bolt_action_desc: "ampuu maagisen pultin hahmoa [TARGET] kohti, aiheuttaen [DMG] vahinkoa.",
  ward_of_aurous_name: "Aurouksen Kilpi",
  ward_of_aurous_desc: "Suojaa kehosi tuhoutumattomalla kilvellä!",
  ward_of_aurous_action_desc_pl: "Kutsut Aurouksen kilven suojaamaan kehoasi!",
  ward_of_aurous_action_desc: "suojaa itsensä maagisella kilvellä.",
  battle_fury_name: "Taistelijan Raivo",
  battle_fury_desc: "Hallittu viha vahvistaa.",
  battle_fury_action_desc_pl: "Annat taistelun viedä mielesi mennessään!",
  battle_fury_action_desc: "riehaantuu taistelun riemusta.",
  venomous_blow_name: "Häijy Isku",
  venomous_blow_desc: "Tässä tällissä onkin ikävä yllätys.",
  venomous_blow_action_desc_pl: "Myrkytät hahmon [TARGET] nopealla iskulla, joka myös aiheuttaa [DMG] vahinkoa!",
  venomous_blow_action_desc: "myrkyttää hahmon [TARGET] iskulla joka tekee [DMG] vahinkoa.",
  poisoned_arrow_name: "Myrkky Nuoli",
  poisoned_arrow_desc: "Taistelu muuttuu metsästykseksi.",
  poisoned_arrow_action_desc_pl: "Ammut myrkyllisen nuolen kohti hahmoa [TARGET], tehden [DMG] vahinkoa!",
  poisoned_arrow_action_desc: "ampuu myrkyllisen nuolen kohti hahmoa [TARGET], aiheuttaen [DMG] vahinkoa.",
  summon_skeleton_warrior_name: "Luo Luuranko Soturi",
  summon_skeleton_warrior_desc: "Kutsuu luuranko soturin taistelemaan puolellasi.",
  summon_skeleton_warrior_action_desc_pl: "Kutsut Luuranko Soturin kentälle!",
  barbarian_charge_name: "Barbaarin Rynnäkkö",
  barbarian_charge_desc: "Törmää kohteeseesi villillä raivolla.",
  barbarian_charge_action_desc_pl: "Karjut rajusti kuin villieläin ja ryntäät kohti hahmoa [TARGET], törmäys aiheuttaen [DMG] vahinkoa!",
  barbarian_charge_action_desc: "raivoaa eläimellisesti ja ryntää päin hahmoa [TARGET], tehden [DMG] vahinkoa.",
  chivalrious_blow_name: "Ritarillinen Hyökkäys",
  chivalrious_blow_desc: "Haasta vastustajasi kaksintaisteluun mahtavalla iskulla!",
  chivalrious_blow_action_desc_pl: "Isket hahmoa [TARGET] kunnialla, kutsuen hänet kamppailuun ja tehden [DMG] vahinkoa!",
  chivalrious_blow_action_desc: "lyö hahmoa [TARGET] kunnioittavasti, kutsuen hänet taisteluun ja tehden [DMG] vahinkoa.",
  challenge_name: "Haaste",
  challenge_desc: "Pienennä välisi kamppailu kumppaniisi suoralla juoksulla!",
  challenge_action_desc_pl: "Rynnäköit pelottomasti kohti hahmoa [TARGET], lämähtäen häneen voimalla, aiheuttaen [DMG] vahinkoa!",
  challenge_action_desc: "Ryntää kohti hahmoa [TARGET] karjuen 'ÄLÄ LÄHDE KARKUUN!', pian törmäten häneen, tehden [DMG] vahinkoa.",
  sneaky_stabbing_name: "Polttava Puukottaja",
  sneaky_stabbing_desc: "Iske vihollista kivuliaimpiin kohtiin.",
  sneaky_stabbing_action_desc_pl: "Vahvistat kykyäsi tunnistaa vihollisesi heikkoudet.",
  sneaky_stabbing_action_desc: "alkaa tarkkailemaan muiden heikoimpia paikkoja.",
  smoke_bomb_name: "Savu Pommi",
  smoke_bomb_desc: "Harhauta vastustajiasi savuisella räjähdyksellä.",
  smoke_bomb_action_desc_pl: "Heität pommin maahan, täyttäen pieneen alueen savulla!",
  smoke_bomb_action_desc_aoe_pl: "[TARGET] ottaa pommin täräyksen suoraan vastaan, ottaen [DMG] vahinkoa!",
  distraction_name: "Hätäinen Hämy",
  distraction_desc: "Heitä rähjäinen nukke maahan harhauttamaan pahantekijöitä.",
  distraction_action_desc_pl: "Asetat nuken maahan hämäämään vihollisiasi!",
  invigorating_finish_name: "Voimistava Viimeistely Isku",
  invigorating_finish_desc: "Laita kaikkesi tähän iskuun ja yritä tuhota vihollisesi omasta ruumistasi välittämättä!",
  invigorating_finish_action_desc_pl: "Isket hahmoa [TARGET] viimeistelevällä hyökkäyksellä, tehden [DMG] vahinkoa!",
  invigorating_finish_action_desc: "Täräyttää hahmoa [TARGET] viimeistelevällä hyökkäyksellä, aiheuttaen [DMG] vahinkoa.",
  warrior_shout_name: "Soturin Karjaisu!",
  warrior_shout_desc: "Rohkaise itseäsi ja kauhistuta vihollisesi \nhyytävällä huudolla!",
  warrior_shout_action_desc_pl: "Karjaiset niin kovaa että pelkkä äänesi riittää tuhoamaan heikoimmat vastustajasi!",
  warrior_shout_action_desc_aoe_pl: "[TARGET] vastaanottaa ääniaallosta kovan iskun, ottaen [DMG] vahinkoa!",
  totem_of_arrows_name: "Nuoli Toteemi",
  totem_of_arrows_desc: "Patsas joka ampuu nuolia.",
  totem_of_arrows_action_desc_pl: "Asetat nuoli toteemin kentälle.",
  ranger_wolf_name: "Metsästäjän Susi",
  ranger_wolf_desc: "Ihmisen paras ystävä.",
  ranger_wolf_action_desc_pl: "Vihellät sudellesi, ja se ilmestyy puolellesi silmänräpäyksessä.",
  awaken_name: "Havahdus",
  awaken_desc: "Pystyt erottamaan pienimmätkin liikkeet vahvalla näölläsi.",
  awaken_action_desc_pl: "Keskität vaistosi parantamaan katsettasi.",
  finishing_blow_name: "Tappoisku",
  finishing_blow_desc: "Käytä omaa terveyttäsi viedäksesi toisen.",
  finishing_blow_action_desc_pl: "Vahvistat iskusi omalla elinvoimallasi, aiheuttaen [DMG] vahinkoa hahmoon [TARGET]!",
  finishing_blow_action_desc: "iskee elinvoimansa vahvistamalla tällillä hahmoa [TARGET], tehden [DMG] vahinkoa!",
  sundering_arrow_name: "Murtava Laukaisu",
  sundering_arrow_desc: "Puolita vastustajasi puolustusvoima vahvalla nuolella.",
  sundering_arrow_action_desc_pl: "Ammut panssarinläpäisevän nuolen kohti hahmoa [TARGET], tehden [DMG vahinkoa]!",
  sundering_arrow_action_desc: "ampuu panssarinläpäisevän nuolen kohti hahmoa [TARGET], aiheuttaen [DMG] vahinkoa.",
  shock_arrow_name: "Shokki Nuoli",
  shock_arrow_desc: "Lamauta vihollinen kaukaa.",
  shock_arrow_action_desc_pl: "Ammut lamauttavan nuolen hahmoa [TARGET] kohti, tehden [DMG] vahinkoa ja lamauttaen kohteen!",
  shock_arrow_action_desc: "ampuu lamauttavan nuolen kohti hahmoa [TARGET], aiheuttaen [DMG] vahinkoa ja lamauttaen kohteen!",

  // CLASSES
  fighterClass_name: "Taistelija",
  barbarianClass_name: "Barbaari",
  sorcererClass_name: "Loitsija",
  rogueClass_name: "Konna",
  rangerClass_name: "Metsästäjä",

  // PERKS // 

  // SORCERER
  introduction_to_sorcery_name: "Maagin Alkukirja",
  introduction_to_sorcery_desc: "Kehitys tapahtuu askel kerrallaan.",
  intent_studies_name: "Taikojan Oppi",
  intent_studies_desc: "Opiskelu korostaa kokemusta.",
  might_of_magic_name: "Magian Mahti",
  might_of_magic_desc: "Sotaan valmistautuminen edistyy parhaiten magialla.",
  spells_of_battle_name: "Taistelun Taiat",
  spells_of_battle_desc: "Keskity helpoimpaan iskuusi ja et voi epäonnistua.",
  school_of_fire_name: "Tulen Opetukset",
  school_of_fire_desc: "Anna sielusi palaa intohimosta!",
  molded_by_flame_name: "Liekeissä Herännyt",
  molded_by_flame_desc: "Tulen voima herättää uusia tuntemuksia.",
  shield_of_ages_name: "Aikojen Kilpi",
  shield_of_ages_desc: "Vanhat kikat suojaavat uusia loitsijoita.",
  shield_of_aurous_name: "Aurouksen Suoja",
  shield_of_aurous_desc: "Aurous on havainnut kunniasi!",
  burning_passion_name: "Palava Intohimo",
  burning_passion_desc: "Mikään ei pysäytä liekehtivää sieluasi!",
  wisdoms_of_the_past_name: "Menneet Viisaudet",
  wisdoms_of_the_past_desc: "Vanhoilta ajoilta voi paljon neuvoja ammentaa.",
  flame_wizard_fury_name: "Tulivelhon Viha",
  flame_wizard_fury_desc: "Viha muuttuu tuleksi, ja tuli voimaksi.",
  makings_of_a_summoner_name: "Valtiaan Kutsu",
  makings_of_a_summoner_desc: "Taian mestarin ei tarvitse taistella yksin, kuninkaalla on aina palvelioita.",
  magical_bonds_name: "Maaginen Yhteys",
  magical_bonds_desc: "Kun kuningas komentaa, kaikki tottelevat.",
  elemental_mage_name: "Alkuaineiden Mestari",
  elemental_mage_desc: "Luonnon voimat ovat käytettävissäsi.",
  piercing_javelin_name: "Lävistävä Keihäs",
  piercing_javelin_desc: "Panssari ei pelasta tarpeeksi vahvalta iskulta.",

  // FIGHTER
  battle_sense_name: "Kamppailun Aistit",
  battle_sense_desc: "Ken taistelee elääkseen, tuntee pienimmänkin muutoksen ilmassa.",
  fighters_vitality_name: "Taistelijan Vireys",
  fighters_vitality_desc: "Lähitaistelussa vain vahvimmat soturit selviytyvät.",
  patient_blow_name: "Kärsivällinen Soturi",
  patient_blow_desc: "Tilanteen tarkkailu on taistelijan vahvin kortti.",
  strength_training_name: "Voimatreeni",
  strength_training_desc: "Voima edistää kamppailu-taitoa.",
  fighting_style_name: "Harjaantunut Iskijä",
  fighting_style_desc: "En pelkää miestä, joka on kerran harjoitellut 10 000 eri iskua, \nmutta pelkään miestä joka on harjoitellut yhtä iskua 10 000 kertaa.",
  furious_assault_name: "Raivokas Hyökkäys",
  furious_assault_desc: "Taistelua ei voiteta seisoskelemalla! Eteenpäin!",
  tactical_genius_name: "Taktiikkojen Kuningas",
  tactical_genius_desc: "Vahva on hän, kuka voi ajatella sodan raivossa.",
  resistant_in_melee_name: "Kestävä",
  resistant_in_melee_desc: "Taistelussa pysyminen on jo pitkä askel voittoon.",
  charging_bull_name: "Ryntäävä Sonni",
  charging_bull_desc: "Ottaen mallia karmeasta eläimestä, murskaa esteesi rajulla voimalla!",
  concentrated_warrior_name: "Taistelun Tasapaino",
  concentrated_warrior_desc: "Voiton voi taata vain yhdistämällä julman raivon ja lempeän kärsivällisyyden.",
  absorber_of_life_force_name: "Elinvoima Soturi",
  absorber_of_life_force_desc: "Kuolleiden voiman vienti pitää kehosi taistelu kunnossa, tarvitsematta lepoa.",
  fighting_with_your_voice_name: "Veteraanin Iltahuuto",
  fighting_with_your_voice_desc: "Välillä kaikki mitä tarvitset on kannustava huuto.",

  // ROGUE
  way_of_the_rogue_name: "Varjoinen Tie",
  way_of_the_rogue_desc: "Kamppailun ei tarvitse olla reilua, vain voitolla on merkitystä.",
  weakpoint_spotter_name: "Heikkouden Löytäjä",
  weakpoint_spotter_desc: "Kohdetta isketään vain parhaimalla hetkellä.",
  shadow_warrior_name: "Varjosoturi",
  shadow_warrior_desc: "Livahda varjoihin kun tilanne kääntyy.",
  fighting_dirty_name: "Likainen Tappelija",
  fighting_dirty_desc: "Luota taitoosi, mutta luota älyysi enemmän.",
  glass_cannon_name: "Hyökkääjä",
  glass_cannon_desc: "Puolustamalla ei taistelua voiteta!",
  ranged_expert_name: "Tarkka-ampuja",
  ranged_expert_desc: "Opettele tappamaan kaukaa.",
  poison_specialist_name: "Myrkyttäjä",
  poison_specialist_desc: "Soturi kuin soturi kärsii myrkytyksen seuraamuksista.",
  simple_strokes_name: "Tehokkaat Viillot",
  simple_strokes_desc: "Kun ei muuhun kykene, varmat iskut pelastavat.",
  dance_of_death_name: "Kuoleman Tanssi",
  dance_of_death_desc: "Kiemurtelu ei pelasta tältä tarkkuudelta!",
  poison_from_afar_name: "Tarkka-Myrkyttäjä",
  poison_from_afar_desc: "Kaukaa turvasta on helpoin murhata.",
  quicker_draw_name: "Nopeampi Veto",
  quicker_draw_desc: "Nopeammin, nopeammin!",
  smoke_screen_name: "Savuverho",
  smoke_screen_desc: "Peitä vastustajasi näkökenttä.",
  sneakier_stabbing_name: "Konnan Kepponen",
  sneakier_stabbing_desc: "Tästä tempusta eivät puukotukselle allergiset pidä!",
  smoke_and_mirrors_name: "Taikatemppu",
  smoke_and_mirrors_desc: "Savua ja peilejä...",
  tricky_distraction_name: "Harhautusliike",
  tricky_distraction_desc: "Laita vastustajasi läiskimään väärää kohdetta.",
  poison_taster_name: "Myrkyn Maistelija",
  poison_taster_desc: "Ammattilainen tuntee tuotteensa tarkasti.",

  // BARBARIAN
  thrill_of_battle_name: "Taiston Himo",
  thrill_of_battle_desc: "Kamppailun kaipaus on pureutunut vereesi.",
  weapon_mastery_name: "Harjoittelu",
  weapon_mastery_desc: "Kykyjä täytyy hiota tai ne katoavat.",
  raging_charge_name: "Raivokas Ryntäys",
  raging_charge_desc: "Itsevarma hyökkäys suoraan vihollista päin on rohkeuden merkki!",
  hardened_constitution_name: "Vahva Rakenne",
  hardened_constitution_desc: "Kehosi on ase, täten siitä kuuluu pitää huolta.",
  power_of_injuries_name: "Kivun Merkitys",
  power_of_injuries_desc: "Niin kauan kun kipu sattuu elämä jatkuu!",
  sharp_senses_name: "Kuudes Aisti",
  sharp_senses_desc: "Sankariteot luonnistuvat häneltä, ken uskaltaa vaarantaa henkensä.",
  perk_barbarian_rage_name: "Raivo",
  perk_barbarian_rage_desc: "Raivo ja viha laittavat veren virtaamaan.",
  impatient_name: "Kärsimätön",
  impatient_desc: "Jatketaan jo!!!!",
  ultimate_warrior_name: "Tuhon Soturi",
  ultimate_warrior_desc: "Voitan sotani koska uskallan taistella!",
  unyielding_rage_name: "Jatkuva Raivo",
  unyielding_rage_desc: "Anna vihan hallita ja kaikki kärsivät.",
  perk_finishing_blow_name: "Viimeinen Hyökkäys",
  perk_finishing_blow_desc: "Vahingoita muita oman terveytesi kustannuksella.",
  true_finish_name: "Viimeisetkin Voimat",
  true_finish_desc: "Kaikki mikä lähtee irti lähtee kovaa!",
  perk_berserker_name: "Kunnia tai Kuolema",
  perk_berserker_desc: "KEHOLLANI EI OLE VÄLIÄ KUNHAN EN TUOTA HÄPEÄÄ ITSELLENI!",
  perk_calmer_berserk_name: "Mietitäänpä tarkemmin...",
  perk_calmer_berserk_desc: "Elämäni päättyminen tarkoittaa myös taistelun päättymistä..",

  // RANGER
  target_practice_name: "Ammunta Harjoittelu",
  target_practice_desc: "Mestarina ei synnytä.",
  call_of_the_forest_name: "Metsän Kutsu",
  call_of_the_forest_desc: "Kehosi on kuin luotu villiä luontoa varten.",
  powered_arrow_name: "Tuhoava Isku",
  powered_arrow_desc: "Murskaa vihollisen puolustukset.",
  rapid_fire_name: "Konekivääri",
  rapid_fire_desc: "Kovaa kyytiä!",
  critical_hit_name: "Kriittinen isku",
  critical_hit_desc: "Isompi luku = isompi parempi. Aivotyö vaikea.",
  rangers_call_name: "Metsästäjän Kutsu",
  rangers_call_desc: "Luonto kutsuu villiä puoltasi!",
  awakening_name: "Luonnon Avautuminen",
  awakening_desc: "Alat päästä ymmärrykseen.",
  hunter_mark_name: "Suojelijan Symboli",
  hunter_mark_desc: "Onnittelut, aloitat nyt urasi luonnonsuojelijana.",
  wild_call_name: "Elämänkumppani",
  wild_call_desc: "Matkan ei tarvitse olla yksinäinen.",
  trusted_companion_name: "Luotettava Ystävä",
  trusted_companion_desc: "Kumppanisi ei sinua pettäisi.",
  fierce_beast_name: "Villi Peto",
  fierce_beast_desc: "Tämä susi ei ole mikään terrieri.",
  shocking_assault_name: "Sähköisku",
  shocking_assault_desc: "Lamautetaan laumat.",
  leave_you_paralyzed_name: "Iskee kuin Salama",
  leave_you_paralyzed_desc: "Ja pysäyttää yhtä vahvasti.",

  // ADVENTURER
  hearty_adventurer_1_name: "Kestävä Terveys I (Orion Pharma)",
  hearty_adventurer_1_desc: "Hyvinvointia rakentamassa.",
  hearty_adventurer_2_name: "Kestävä Terveys II (Orion Pharma)",
  hearty_adventurer_2_desc: "Hyvinvointia rakentamassa.",
  hearty_adventurer_3_name: "Kestävä Terveys III (Orion Pharma)",
  hearty_adventurer_3_desc: "Hyvinvointia rakentamassa.",
  hearty_adventurer_4_name: "Kestävä Terveys IV (Orion Pharma)",
  hearty_adventurer_4_desc: "Hyvinvointia rakentamassa.",
  hearty_adventurer_5_name: "Kestävä Terveys V (Orion Pharma)",
  hearty_adventurer_5_desc: "Hyvinvointia rakentamassa.",
  first_aid_expert_name: "Ensiavun Ekspertti",
  first_aid_expert_desc: "Hyvinvointia ylläpitämässä.",
  cleanser_name: "Puhdistaja",
  cleanser_desc: "Keho pidetään puhtaana.",
  advancing_backwards_name: "Rohkea Pakoreitti",
  advancing_backwards_desc: "Edistymistä eri suuntaan.",

  // NECROMANCER
  pursuit_of_undeath_name: "Kuolemattomuuden Tavoittelu",
  pursuit_of_undeath_desc: "Kryptisin keinoin.",

  // Settings tooltips
  log_char_movement: "<f>16px<f>Kirjaa teksti ruutuun vihollisten sijainnin joka kierroksella. \nVoi täyttää ruudun nopeasti.",
  toggle_minimap: "<f>16px<f>Minikartta auttaa suunnistamaan eri alueissa. \nVoi hidastaa peliä.",
  hide_helmet: "<f>16px<f>Piilota kypärä nähdäksesi hahmosi naama.",
  randomize_items: "<f>16px<f>Varusteet generoivat satunnaiset statsit.\nAntaa pelille suuremman roguelike tunnelman.",
  interact_help: "<f>16px<f>Avaa arkkuja ja poimi tavaroita seisomalla niiden päällä. \nMyös mahdollistaa hahmoille puhumisen.",
  world_messages: "<f>16px<f>Näe lisää viestejä teksti ruudussa.",
  toggle_rangedMode: "<f>16px<f>Ammunta tila näyttää ammunta aseiden kantomatkan.",
  ui_scale: "<f>16px<f>Muuttaa UI-elementtien kokoa kertoimella.\nMuuta jos elementit ovat liian pieniä tai suuria.",
} as any;

const english = {
  // Identifier
  language_id: "english",
  finnish: "Suomi",
  english: "English",

  // Races
  human_name: "Human",
  orc_name: "Half-Orc",
  elf_name: "Half-Elf",
  ashen_name: "Ashen",

  // Character Window
  core_stats: "Core stats",
  core_resistances: "Core resistances",
  status_resistances: "Status Resists",
  passives: "Passive Abilities",
  poison_status: "Poison",
  burning_status: "Burning",
  curse_status: "Curse",
  stun_status: "Stun",
  bleed_status: "Bleed",

  str_tt: `<i>${icons["str"]}<i>Strength increases <i>${icons["melee"]}<i>damage with strength scaling weapons by 2%,\n and encumbrance by 0.5`,
  dex_tt: `<i>${icons["dex"]}<i>Dexterity increases <i>${icons["ranged"]}<i>damage with dexterity scaling weapons by 2%,\nand increases both <i>${icons["hitChance"]}<i>Hit chance and <i>${icons["evasion"]}<i>evasion by 0.25`,
  vit_tt: `<i>${icons["vit"]}<i>Vitality increases <i>${icons["health"]}<i>health by 5,\n<i>${icons["regenHp_icon"]}<i>health regeneration by 1%\n and encumbrance by 1`,
  int_tt: `<i>${icons["int"]}<i>Intelligence increases <i>${icons["mana"]}<i>mana by 2,\n<i>${icons["regenMp_icon"]}<i>mana recovery by 1%\n and <i>${icons["damage"]}<i>magical damage by 2%`,
  cun_tt: `<i>${icons["cun"]}<i>Cunning increases <i>${icons["critDamage"]}<i>crit damage by 1.5%,\n and <i>${icons["critDamage"]}<i>crit chance by 0.4%`,
  critDamage_tt: `<i>${icons["critDamage"]}<i>Crit damage is the multiplier that improves crit hits.`,
  critChance_tt: `<i>${icons["critDamage"]}<i>Crit chance increases your chances of achieving critical hits.`,
  hitChance_tt: `<i>${icons["hitChance"]}<i>Hit chance increases the chance of hitting your target. \nCompared to enemy's <i>${icons["evasion"]}<i>evasion.`,
  evasion_tt: `<i>${icons["evasion"]}<i>Evasion increases your chance of avoiding damage. \nCompared to enemy's <i>${icons["hitChance"]}<i>hit chance.`,
  atk_speed_tt: `This is your <i>${icons["attackSpeed_icon"]}<i>Attack speed.\nValues over 100% allow you to sometimes hit twice or more in a single round. \nValues under 100% cause you to miss some turns.`,
  mov_speed_tt: `This is your <i>${icons["movementSpeed_icon"]}<i>Movement speed. \nValues over 100% allow you to sometimes move twice or more in a single round. \nValues under 100% cause you not to move during some rounds.`,

  physical_tt: `<i>${icons["physical_armor"]}<i>Physical Armor increases resistance against physical attacks. \n<i>${icons["slash_icon"]}<i>Slashing, <i>${icons["crush_icon"]}<i>Crushing and <i>${icons["pierce_icon"]}<i>Piercing damage reduced by 0.4% per point. \nArmor has a maximum value of 200.`,
  magical_tt: `<i>${icons["magical_armor"]}<i>Magical Armor increases resistance against magical attacks. \n<i>${icons["magic_icon"]}<i>Magical, <i>${icons["dark_icon"]}<i>Dark and <i>${icons["divine_icon"]}<i>Divine damage reduced by 0.4% per point. \nArmor has a maximum value of 200.`,
  elemental_tt: `<i>${icons["elemental_armor"]}<i>Elemental Armor increases resistance against elemental attacks. \n<i>${icons["fire_icon"]}<i>Fire, <i>${icons["lightning_icon"]}<i>Lightning and <i>${icons["ice_icon"]}<i>Ice damage reduced by 0.4% per point. \nArmor has a maximum value of 200.`,

  resistances_tt: "Resistance decreases incoming damage of its type by the indicated %.",
  stat_resist_tt: `Status resistance decreases any damage caused by effects by the indicated %. \n\nIt also gives a chance of completely resisting the effect. \n\nWhen effect is resisted, it is not applied at all.`,

  // Status Resists
  poisonDefense: "Poison resistance",
  burningDefense: "Burning resistance",
  curseDefense: "Curse resistance",
  stunDefense: "Stun resistance",
  bleedDefense: "Bleed resistance",

  // Messages
  test_message: "<c>white<c>Welcome to <c>gold<c>Dungeons of Tavaraen<c>white<c>!",
  follow_slimes: "<c>white<c>Keep following the <c>gold<c>slimes<c>white<c> and you'll get a fair fight!",
  beach_episode: "<c>white<c>Beach infested with <c>gold<c>skeletons<c>white<c>, prepare for trouble!",

  // Technical stuff
  changeWordOrder: false,
  mana: "mana",
  health: "health",
  str: "Strength",
  dex: "Dexterity",
  vit: "Vitality",
  int: "Intelligence",
  cun: "Cunning",
  crush: "Crushing",
  slash: "Slashing",
  pierce: "Piercing",
  magic: "Magical",
  fire: "Fire",
  ice: "Ice",
  dark: "Dark",
  divine: "Divine",
  lightning: "Lightning",
  crush_def: "Crushing",
  slash_def: "Slashing",
  pierce_def: "Piercing",
  magic_def: "Magical",
  fire_def: "Fire",
  ice_def: "Ice",
  dark_def: "Dark",
  divine_def: "Divine",
  lightning_def: "Lightning",
  hpMax: "Health",
  mpMax: "Mana",
  hitChance: "Hit Chance",
  evasion: "Evasion",
  sight: "Sight",
  increases: "Increases",
  decreases: "Decreases",
  damage: "Damage",
  movementSpeed: "Movement Speed",
  attackSpeed: "Attack Speed",
  by: "by ",
  strV: "Strength",
  strP: "Strength%",
  vitV: "Vitality",
  vitP: "Vitality%",
  dexV: "Dexterity",
  dexP: "Dexterity%",
  intV: "Intelligence",
  intP: "Intelligence%",
  hpV: "Health",
  hpP: "Health%",
  mpV: "Mana",
  mpP: "Mana%",
  resistAllV: "All Resistances",
  resistAllP: "All Resistances%",
  physicalDefP: "Physical Armor%",
  magicalDefP: "Magical Warding%",
  elementalDefP: "Elemental Armor%",
  hitChanceV: "Hit Chance",
  hitChanceP: "Hit Chance%",
  evasionV: "Evasion",
  evasionP: "Evasion%",
  critChanceV: "Crit Chance",
  critChanceP: "Crit Chance",
  critDamageV: "Crit Damage",
  critDamageP: "Crit Damage",
  movementSpeedV: "Movement Speed",
  attackSpeedV: "Attack Speed",
  status_effect: "Status effect",
  status_effects: "Status effects",
  last: "Effect time",
  lasts_for: "Lasts for",
  resist: "Resist",
  silence_text: "You are silenced!",
  silence: "Silences magic!",
  concentration_text: "Your concentration is broken!",
  concentration: "Breaks concentration!",
  heal_power: "Healing Power",
  concentration_req: "Requires Concentration",
  type: "Type",
  ranged: "Ranged",
  melee: "Melee",
  spell: "Spell",
  requires_melee_weapon: "Requires Melee Weapon",
  requires_ranged_weapon: "Requires Ranged Weapon",
  recharge_only_in_combat: "Recharge Only In Combat",
  targets_self: "Targets Self",
  mana_cost: "Mana Cost",
  health_cost: "Health Cost",
  health_cost_percentage: "Health Cost",
  use_range: "Use Range",
  damage_multiplier: "Damage Multiplier",
  resistance_penetration: "Resistance Penetration",
  aoe_size: "Area of Effect",
  yes: "yes",
  no: "no",
  tiles: "tiles",
  attack: "Attack",
  heal: "Heal",
  buff: "Buff",
  movement: "Movement",
  charge: "Charge",
  summon: "Summon",
  turn: "Turn",
  turns: "turns",
  turns_alt: "turns",
  cooldown: "Cooldown",
  base_heal: "Base Heal",
  map_to_hotbar: "Map ability/item",
  remove_from_hotbar: "Remove ability/item",
  removed_in: "Removed in",
  deals: "Deals",
  perk_points: "Perk points",
  stat_points: "Stat points",
  adventurerPerks: "Adventurer",
  lvl_up: "You leveled up! Your level is now [LVL]!",
  regenHp: "Health regeneration",
  regenMp: "Mana recovery",
  regenHpP: "Health regeneration%",
  regenMpP: "Mana recovery%",
  of_max_hp: "MAX HP",
  life_steal: "Lifesteal",
  life_steal_on_kill_1: "When this attack kills an enemy, \nyou recover",
  life_steal_on_kill_2: "of the enemy's maximum health.",
  for_each_enemy_hit: "Each enemy hit by this ability increases buff duration by",
  equip: "Equip",
  unequip: "Unequip",
  drop: "Drop",
  pick_up: "Pick up",
  map: "Map",
  last_played: "Last played",
  slain: `<f>36px<f><c>white<c>You have been <c>crimson<c><f>36px<f>slain!\n§<c>silver<c>\tYou left behind <v>player.grave.xp<v><i>${icons["exp_icon"]}<i>, <v>player.grave.gold<v><i>${icons["gold_icon"]}<i>`,
  respawn: "Respawn [R]",
  title_screen: "Title Screen",

  // Enemy names
  hiisi_name: "Hiisi",
  hiisiWarrior_name: "Hiisi Warrior",
  hiisiHunter_name: "Hiisi Hunter",
  skeletonWarrior_name: "Skeleton Warrior",
  skeletonArcher_name: "Skeleton Archer",
  skeletonMage_name: "Skeleton Mage",
  skeletonLich_name: "Skeleton Lich",
  soulWraith_name: "Soul Wraith",
  greySlime_name: "Grey Slime",
  flamingSlime_name: "Flaming Slime",
  electricSlime_name: "Electric Slime",
  norsemanBerserk_name: "Norseman Berserker",
  norsemanHunter_name: "Norseman Hunter",
  femaleOrcRaider_name: "Orc Raider",
  maleOrcRaider_name: "Orc Raider",
  orcChieftess_name: "Orc Chieftess",
  wildTroll_name: "Wild Troll",
  wildStoneTroll_name: "Wild Stone Troll",
  troll_name: "Troll",
  stoneTroll_name: "Stone Troll",
  enthralledKnight_name: "Enthralled Knight",
  spectralKnight_name: "Spectral Knight",

  // Summon names
  skeletonWarriorSummon_name: "Conjured Skeleton Warrior",
  skeletonLichSummon_name: "Conjured Skeleton Lich",
  stoneTrollSummon_name: "Conjured Stone Troll",
  dummyTarget_name: "Dummy Target",
  arrowTotem_name: "Arrow Totem",
  rangerWolf_name: "Wolf Companion",

  // LOG TEXTS
  you: "You",
  recovery_pl: "recovering",
  health_points: "health",
  for: "for",
  death: "dies.",
  damage_from_effect_pl: "<c>yellow<c>You<c>white<c> take [ICON][DMG] damage from [STATUS]!",
  damage_from_effect: "<c>white<c>[TARGET] takes [ICON][DMG] damage from [STATUS].",
  player_death_log: "YOU ARE DEAD...",
  cure_pl: "<c>yellow<c>You<c>white<c> cure yourself!",
  cure: "[ACTOR] cures themself.",
  useConsumable: "<c>yellow<c>You<c>white<c> use a consumable item!",
  moves_to: "moves to tile",
  gained: "Gained",


  // WORLD TEXTS
  gained_xp: "Gained [XP] XP!",
  player_death: "YOU WERE KILLED!",

  // Damage types
  poison_damage: "Poison",
  burning_damage: "Burning",

  // Character Creation
  choose_name: "Name",
  choose_race: "Race",
  choose_class: "Class",
  fighterClass_desc: "<f>19px<f><c>silver<c>Fighters are balanced melee combatants\nwho defeat their foes by combining \ngood offense with great defense.\nAs a fighter you focus on melee combat \nand have great staying potential.§\n\n",
  barbarianClass_desc: "<f>19px<f><c>silver<c>Barbarians are brutes\nwho love fighting on the edge,\npreferring to use two handed weapons\nfor more reach and damage.\nAs a barbarian you focus on melee combat\nand have great offensive power\nwith high risk high reward gameplay.§\n\n",
  sorcererClass_desc: "<f>19px<f><c>silver<c>Sorcerers are spell weaving intellectuals\nwho prefer inflicting devastating damage from a distance.\nAs a sorcerer you focus on ranged combat \nand have excellent offensive power,\nat the cost of being vulnerable in close range.§\n\n",
  rogueClass_desc: "<f>19px<f><c>silver<c>Rogues lurk in the shadows,\npreferring to soften their targets from range\nbefore finishing them off at close range.\nAs a rogue you don't particularly excel\nin either ranged or melee combat,\nbut are more flexible than others.§\n\n",
  rangerClass_desc: "<f>19px<f><c>silver<c>Rangers are forest guardians \nwho prefer ranged weapons and \nbonding with their wolf companion. \nAs a ranger you focus on ranged combat \nand have an excellent partner helping you out.§\n\n",

  // Dialog screen stuff
  openStore: "STORE",
  quest: "QUEST",
  smith: "SMITH",
  exit: "EXIT",

  // Misc
  attack_name: "base attack damage",
  cures_statuses: "Cures",
  resistance: "Resistances",
  physical: "Physical Armor",
  magical: "Magical Warding",
  elemental: "Elemental Shielding",
  item_weight: "Weight",
  item_worth: "Worth",
  item_grade: "Grade",
  cant_equip: "Stats too low to equip this item!",
  item_stat_bonus: "Scales with",
  weapon_has_great_reach: "Greater reach than most weapons",
  status_effects_enemy: "<c>white<c>Status effects to <c>red<c><f>22px<f>enemy",
  status_effects_you: "<c>white<c>Status effects to <c>lime<c><f>22px<f>you",
  encumbrance: "Encumbrance",
  shrine_activated: "Shrine activated!",
  shrine_used: "Shrine's power has already been spent...",
  add_ability: "Grants ability",
  requires: "Requires",
  critChance: "Crit Chance",
  critDamage: "Crit Damage",
  resistAll: "All Resistances",
  uses: "Uses Remaining",
  amount: "Amount",
  item_name: "Item name",
  item_type: "Type",
  item_rarity: "Rarity",
  item_weight_title: "Weight",
  item_worth_title: "Worth",
  weapon: "weapon",
  armor: "armor",
  consumable: "consumable",
  artifact: "artifact",
  required_stats: "Required stats",
  active_if: "Active if",
  hp_more_than: "Health more than",
  hp_less_than: "Health less than",
  mp_more_than: "Mana more than",
  mp_less_than: "Mana less than",
  passive: "Passive ability",
  too_much_weight: "You're carrying too much to move! Drop something!",
  summons_unit: "Summons unit",
  summon_level: "Summoned unit level",
  summon_last: "Summoned unit last",
  total_summon_limit: "Summon limit",
  permanent: "Permanent",
  all_summons_damage: "All summoned units' damage",
  all_summons_regenHp: "All summoned units' hp regen",
  two_handed_weapon: "Two-handed",
  rooted: "Can't move!",
  closest_enemy: "Distance to closest enemy: ",
  expGain: "Experience gain",
  pick_item: "Pick up item",
  pick_chest: "Open chest",
  read_msg: "Read message",
  talk_to_npc: "Speak with",
  item_slot: "Slot",
  artifact1: "Talisman",
  artifact2: "Emblem",
  artifact3: "Ring",
  chest: "Torso",
  helmet: "Helmet",
  gloves: "Hands",
  legs: "Legs",
  boots: "Feet",
  offhand: "Offhand",
  buy_item: "Buy item",
  sell_item: "Sell item",
  quest_added: "<c>goldenrod<c>Quest '<c>gold<c>[QUEST]<c>goldenrod<c>' has begun!",
  revive: "You have been revived at a shrine!",

  // Character names
  testMerchant_name: "Karl Bauer",
  blacksmithMaroch_name: "Maroch",

  // Artifacts
  part_of_set: "Part of",
  artifact_def: "Artifact",
  artifact_set: "Artifact Set",
  artifact_two_piece: "2-piece set effect",
  artifact_three_piece: "3-piece set effect",
  defenderSet_name: "Defender",
  guardianSet_name: "Guardian",
  scholarSet_name: "Scholar",
  warriorSet_name: "Warrior",
  loneShadeSet_name: "Lone Shade",
  hunterSet_name: "Hunter",

  // Passive abilities
  resilience_of_the_lone_wanderer_name: "Lone Wanderer's Resilience",
  lone_wanderer_desc: "You have a duty to complete, and nothing will stop you, not even death itself.",
  troll_regeneration_name: "Troll Regeneration",
  no_natural_regen_name: "Sealed Recovery",
  low_natural_regen_name: "Weakened Recovery",
  medium_natural_regen_name: "Slow Recovery",
  magically_impotent_name: "Magically Sealed",
  magical_regen_name: "Magical Domination",
  weaker_natural_ability_name: "Cumbersome",
  orc_frenzy_name: "Orcish Frenzy",
  orc_resilience_name: "Orcish Resilience",
  cornered_animal_name: "Cornered Animal",
  slow_name: "Slow",
  fast_name: "Fast",
  frenzy_name: "Frenzy",
  heightened_casting_name: "Heightened Casting",
  warrior_instinct_name: "Warrior Instinct",
  confident_shot_name: "Confident Shot",
  blood_rage_1_name: "Blood Rage I",
  blood_rage_2_name: "Blood Rage II",
  reckless_1_name: "Reckless I",
  reckless_2_name: "Reckless II",
  sense_of_danger_1_name: "Danger Sense I",
  sense_of_danger_2_name: "Danger Sense II",
  frantic_mana_recovery_name: "Frantic Mana Recovery",
  mark_of_hunter_name: "Mark of the Hunter",
  racial_ability_orc_1_name: "Orcish Musculature",
  racial_ability_human_1_name: "Human Tenacity",
  racial_ability_elf_1_name: "Elven Wisdom",
  racial_ability_ashen_1_name: "Ashen Agility",

  // Enemy types
  against_type_syntax: " against ",
  singular_type_slime: "Slime",
  plural_type_slime: "Slimes",
  singular_type_skeleton: "Skeleton",
  plural_type_skeleton: "Skeletons",
  singular_type_barbarian: "Barbarian",
  plural_type_barbarian: "Barbarians",
  singular_type_troll: "Troll",
  plural_type_troll: "Trolls",
  singular_type_hiisi: "Hiisi",
  plural_type_hiisi: "Hiisi creatures",
  singular_type_wraith: "Wraith",
  plural_type_wraith: "Wraiths",

  // Enemy races
  against_race_syntax: " against ",
  singular_race_elemental: "Elemental",
  plural_race_elemental: "Elementals",
  singular_race_undead: "Undead",
  plural_race_undead: "Undead",
  singular_race_human: "Human",
  plural_race_human: "Humans",
  singular_race_monster: "Monster",
  plural_race_monster: "Monsters",
  singular_race_orc: "Orc",
  plural_race_orc: "Orcs",

  /* MENU */

  menu_resume: "Resume",
  menu_options: "Options",
  menu_save_games: "Save Games",
  menu_main_screen: "Main Menu",
  menu_new_game: "New Game",
  menu_load_game: "Load Game",

  setting_log_enemy_movement: "Log character movement",
  setting_toggle_minimap: "Toggle minimap",
  setting_hide_helmet: "Hide helmet",
  setting_randomize_items: "Random equipment stats",
  setting_game_language: "Game language",
  setting_hotkey_inv: "Open inventory screen",
  setting_hotkey_char: "Open character screen",
  setting_hotkey_perk: "Open level up screen",
  setting_hotkey_journal: "Open journal",
  setting_hotkey_codex: "Open codex",
  setting_hotkey_area_map: "Open area map",
  setting_hotkey_ranged: "Toggle 'Ranged Mode'",
  setting_hotkey_move_up: "Move up",
  setting_hotkey_move_down: "Move down",
  setting_hotkey_move_left: "Move left",
  setting_hotkey_move_right: "Move right",
  setting_hotkey_move_right_up: "Move north-east",
  setting_hotkey_move_right_down: "Move south-east",
  setting_hotkey_move_left_up: "Move north-west",
  setting_hotkey_move_left_down: "Move south-west",
  setting_hotkey_interact: "Interact",
  setting_hotkey_open_world_messages: "Open text box",
  setting_ui_scale: "UI scaling",

  open_menu: "Open game menu",

  space_key: "SPACE",

  save_over: "Save over file",
  load_game: "Load game",
  delete_save: "Delete save file",
  create_save: "Create new save",
  create_file: "Save to file (downloads a .txt file)",
  load_file: "Load from file (opens prompt)",
  storage_used: "Storage",
  out_of_date: "\tOut of date \n\nThis save is out of date, \nand thus may not work anymore.",
  version: "Version",
  old_save: "Old",

  // Grades
  common: "Common",
  uncommon: "Uncommon",
  rare: "Rare",
  mythical: "Mythical",
  legendary: "Legendary",

  // Adjectives
  str_adjective: "Strong",
  dex_adjective: "Dexterious",
  vit_adjective: "Vigorous",
  int_adjective: "Intelligent",
  cun_adjective: "Cunning",
  mpMax_adjective: "Spiritual",
  hpMax_adjective: "Healthy",
  spellDamage_adjective: "Magically Oriented",
  rangedDamage_adjective: "Range Oriented",
  meleeDamage_adjective: "Physically Oriented",
  evasion_adjective: "Agile",
  hitChance_adjective: "Accurate",
  critDamage_adjective: "Critical",
  critChance_adjective: "Critical",
  slashDamage_adjective: "Slashing",
  crushDamage_adjective: "Crushing",
  pierceDamage_adjective: "Piercing",
  magicDamage_adjective: "Magical",
  darkDamage_adjective: "Dark",
  divineDamage_adjective: "Divine",
  fireDamage_adjective: "Flaming",
  iceDamage_adjective: "Freezing",
  lightningDamage_adjective: "Electrifying",
  resistAll_adjective: "Defensive",
  regenMp_adjective: "Magic Returning",
  regenHp_adjective: "Regenerating",
  damage_adjective: "Damaging",
  movementSpeed_adjective: "Quick",
  attackSpeed_adjective: "Hasty",

  // Statuses
  effect_defend_name: "Defending",
  effect_poison_name: "Poison",
  effect_poison_desc: "Poison courses through your body, \nweakening and harming you.",
  effect_venom_name: "Venom",
  effect_venom_desc: "Venom courses through your body, \nweakening and harming you.",
  effect_rage_name: "Rage",
  effect_rage_desc: "You are slighty upset.",
  effect_berserk_name: "Berserk",
  effect_berserk_desc: "RRAAAAAGHH!!",
  effect_sunder_name: "Sundered",
  effect_sunder_desc: "Your armor has been sundered, rendering it much less effective.",
  effect_dazed_name: "Dazed",
  effect_dazed_desc: "A blow has left you dazed, \nmaking it much harder to perform any action.",
  effect_blighted_name: "Blighted",
  effect_blighted_desc: "Your very soul is weakened from a vile blight.",
  effect_ward_of_aurous_name: "Ward of Aurous",
  effect_ward_of_aurous_desc: "Feel at ease, Aurous himself is guaranteeing your safety.",
  effect_battle_fury_name: "Fury",
  effect_battle_fury_desc: "You are concentrating on physical might.",
  effect_burning_name: "Burning",
  effect_burning_desc: "YOU ARE ON FIRE!",
  effect_chilled_name: "Chilled",
  effect_chilled_desc: "Your body is cooling down, getting slower, weakening...",
  effect_summoned_name: "Summon",
  effect_summoned_desc: "Your conjuration dies once this expires.",
  effect_disoriented_name: "Disoriented",
  effect_disoriented_desc: "Something has left you delirious, unable to grasp your surroundings properly.",
  effect_dueled_name: "Dueled",
  effect_dueled_desc: "You have been dueled and can no longer back from the fight.",
  effect_sneaky_stabbing_name: "Sneaky Stabbing",
  effect_sneaky_stabbing_desc: "Your ability to hit critical points has been enhanced.",
  effect_smoke_bomb_effect_name: "Smoke Bomb",
  effect_smoke_bomb_effect_desc: "Your sight and power have been compromised by a hazy smoke screen.",
  effect_smoke_evasion_name: "Smoke Screen Evasion",
  effect_smoke_evasion_desc: "You exploit the smoke screen you've planted to evade attacks more easily.",
  effect_encouraged_warrior_shout_name: "Encouraged!",
  effect_encouraged_warrior_shout_desc: "You're feeling brave after receiving some motivation!",
  effect_disheartened_warrior_shout_name: "Disheartened",
  effect_disheartened_warrior_shout_desc: "Your courage has failed you.",
  effect_heightened_senses_name: "Heightened Senses",
  effect_heightened_senses_desc: "Your senses have peaked, making you more aware",
  effect_paralyzed_name: "Paralyzed",
  effect_paralyzed_desc: "You are paralyzed and can't move a muscle.",

  // Abilities and stuff
  attack_action_desc_pl: "<c>yellow<c>You<c>white<c> connect an attack against [TARGET] and harm them for [DMG] damage.",
  attack_action_desc: "attacks [TARGET], dealing [DMG] damage.",
  defend_name: "Defend",
  defend_desc: "Focus on protecting yourself this turn.",
  defend_action_desc_pl: "<c>yellow<c>You<c>white<c> focus on defending.",
  defend_action_desc: "focuses on defending.",
  focus_strike_name: "Focus Strike",
  focus_strike_desc: "Observe your opponent with precision,\nstriking only at the greatest opening.",
  focus_strike_action_desc_pl: "<c>yellow<c>You<c>white<c> focus on your opponents' mistakes, punishing [TARGET] with [DMG] damage.",
  focus_strike_action_desc: "focus strikes [TARGET] for [DMG] damage.",
  true_shot_name: "True Shot",
  true_shot_desc: "Unleash a precise arrow with all your might,\nstriking your opponent's weak point.",
  true_shot_action_desc_pl: "<c>yellow<c>You<c>white<c> coat an arrow in magic, and cast true shot on [TARGET], dealing [DMG] damage.",
  true_shot_action_desc: "shoots a magic powered arrow at [TARGET], dealing [DMG] damage.",
  first_aid_name: "First Aid",
  first_aid_desc: "Do whatever you can to recover\nfrom slight injuries on the field, ",
  first_aid_action_desc_pl: "perform first aid on your wounds, ",
  first_aid_action_desc: "performs first aid on their wounds, ",
  icy_javelin_name: "Icy Javelin",
  icy_javelin_desc: "Shoot a javelin made of pure ice and magic.",
  icy_javelin_action_desc_pl: "<c>yellow<c>You<c>white<c> form a pike from ice, and cast it towards [TARGET], dealing [DMG] damage.",
  icy_javelin_action_desc: "fires a javelin of ice at [TARGET], dealing [DMG] damage.",
  barbarian_rage_name: "Barbarian Rage",
  barbarian_rage_desc: "Stop thinking and switch to pure offense,\nbolstered by your ability to ignore pain!",
  barbarian_rage_action_desc_pl: "fill your mind with nothing but rage at the bastard enemies you face!",
  barbarian_rage_action_desc: "fills their mind with unyielding rage!",
  berserk_name: "Berserk",
  berserk_desc: "RRRAAAAAAAAAAAAAAAAAAGHHHHH!!!!!!",
  berserk_action_desc_pl: "YOU THROW AWAY ANY THOUGHT OF SELF PRESERVATION, IT'S TIME TO PUT THESE BASTARDS TO SLEEP!!!",
  berserk_action_desc: "GOES COMPLETELY BERSERK, BETTER BE WARY!!",
  shadow_step_name: "Shadow Step",
  shadow_step_desc: "Step in to the shadow, \nto find a new realm.",
  shadow_step_action_desc_pl: "<c>yellow<c>You<c>white<c> use the shadows to your advantage, moving rapidly to your destination.",
  shadow_step_action: "uses the shadows as a boost to get to their destination.",
  retreat_name: "Draw Back",
  retreat_desc: "Scurry away from battle.",
  retreat_action_desc_pl: "<c>yellow<c>You<c>white<c> disengage your foes, covering some ground!",
  retreat_action: "retreats from battle!",
  charge_name: "Charge",
  charge_desc: "Charge wildly at your foe.",
  charge_action_desc_pl: "<c>yellow<c>You<c>white<c> charge at [TARGET], dealing [DMG] damage!",
  charge_action_desc: "charges at [TARGET], dealing [DMG] damage.",
  reap_name: "Reap",
  reap_desc: "Lash out towards a foe.",
  reap_action_desc_pl: "<c>yellow<c>You<c>white<c> charge at [TARGET] intent to reap their soul, dealing [DMG] damage!",
  reap_action_desc: "charges at [TARGET], reaping them for [DMG] damage.",
  purification_name: "Purification",
  purification_desc: "Purify your body of poisons and other maladies.",
  blight_name: "Blight",
  blight_desc: "Blight your foe to weaken them.",
  blight_action_desc_pl: "<c>yellow<c>You<c>white<c> blight [TARGET], dealing [DMG] damage and weakening them!",
  blight_action_desc: "blights [TARGET], dealing [DMG] damage and weakening them.",
  fireball_name: "Fireball",
  fireball_desc: "Incinerate your foes with a flaming ball of destruction.",
  fireball_action_desc_pl: "<c>yellow<c>You<c>white<c> throw a fiery ball towards your foes!",
  fireball_action_desc: "shoots a fireball at [TARGET], burning them for [DMG] damage.",
  fireball_action_desc_aoe_pl: "[TARGET] is burned by the blast, causing [DMG] damage!",
  piercing_mana_bolt_name: "Piercing Bolt of Magic",
  piercing_mana_bolt_desc: "Pierce your foe with pure magic.",
  piercing_mana_bolt_action_desc_pl: "<c>yellow<c>You<c>white<c> fire a mana bolt at [TARGET], dealing [DMG] damage!",
  piercing_mana_bolt_action_desc: "shoots a mana bolt at [TARGET], dealing [DMG] damage.",
  ward_of_aurous_name: "Ward of Aurous",
  ward_of_aurous_desc: "Defend your body with an invincible shield.",
  ward_of_aurous_action_desc_pl: "<c>yellow<c>You<c>white<c> summon the ward of Aurous himself upon your body!",
  ward_of_aurous_action_desc: "defends themself with a magical ward.",
  battle_fury_name: "Battle Fury",
  battle_fury_desc: "Concentrating your anger into a controlled fury \nwill allow you to summon immense power.",
  battle_fury_action_desc_pl: "<c>yellow<c>You<c>white<c> allow a controlled fury to manifest in your mind!",
  battle_fury_action_desc: "commits to a furious offensive.",
  venomous_blow_name: "Venomous Blow",
  venomous_blow_desc: "This attack has a nasty surprise.",
  venomous_blow_action_desc_pl: "<c>yellow<c>You<c>white<c> strike [TARGET] with a sudden blow, dealing [DMG] damage and poisoning them!",
  venomous_blow_action_desc: "poisons [TARGET] with a sudden strike, dealing [DMG] damage.",
  poisoned_arrow_name: "Poisoned Arrow",
  poisoned_arrow_desc: "Death from afar. Slow death.",
  poisoned_arrow_action_desc_pl: "<c>yellow<c>You<c>white<c> shoot a poisonous arrow at [TARGET], dealing [DMG] damage!",
  poisoned_arrow_action_desc: "shoots an arrow coated in poison at [TARGET], dealing [DMG] damage.",
  summon_skeleton_warrior_name: "Summon Skeleton Warrior",
  summon_skeleton_warrior_desc: "Conjure a Skeleton Warrior to protect you.",
  summon_skeleton_warrior_action_desc_pl: "You call Skeleton Warrior to battle!",
  barbarian_charge_name: "Barbarian Charge",
  barbarian_charge_desc: "Recklessly close in on foes.",
  barbarian_charge_action_desc_pl: "<c>yellow<c>You<c>white<c> unleash a fearsome warcry and charge towards [TARGET], dealing [DMG] damage and disorienting them!",
  barbarian_charge_action_desc: "charges at [TARGET] with a ferocious cry, ramming into them for [DMG] damage.",
  chivalrious_blow_name: "Chivalrious Blow",
  chivalrious_blow_desc: "Gracefully strike your foe, tempting them to duel you.",
  chivalrious_blow_action_desc_pl: "<c>yellow<c>You<c>white<c> gracefully strike [TARGET], dealing [DMG] damage and dueling them!",
  chivalrious_blow_action_desc: "masterfully strikes [TARGET], harming them for [DMG] damage and dueling them.",
  challenge_name: "Challenge",
  challenge_desc: "Rush towards your opponent, ready to battle them with honour!",
  challenge_action_desc_pl: "<c>yellow<c>You<c>white<c> rush forwards, looking at [TARGET] while doing so, soon slamming into them for [DMG] damage!",
  challenge_action_desc: "rushes towards [TARGET] while shouting 'I CHALLENGE YOU!', quickly slamming into them for [DMG] damage.",
  sneaky_stabbing_name: "Sneaky Stabbing",
  sneaky_stabbing_desc: "Carefully examine your enemy's body, looking for juicy stabbing targets.",
  sneaky_stabbing_action_desc_pl: "<c>yellow<c>You<c>white<c> enhance your ability to detect weakpoints!",
  sneaky_stabbing_action_desc: "enhances their ability to detect weakspots.",
  smoke_bomb_name: "Smoke Bomb",
  smoke_bomb_desc: "Distract your targets with a well placed smoke screen.",
  smoke_bomb_action_desc_pl: "<c>yellow<c>You<c>white<c> throw a bomb on the ground, quickly filling the area with smoke!",
  smoke_bomb_action_desc_aoe_pl: "[TARGET] is caught in the smoky explosion, taking [DMG] damage!",
  distraction_name: "Hasty Distraction",
  distraction_desc: "Plant a dummy nearby for enemies to target.",
  distraction_action_desc_pl: "You prop a dummy target on the ground!",
  invigorating_finish_name: "Invigorating Finish",
  invigorating_finish_desc: "Put your all into a blow with the intent to finish your foe.",
  invigorating_finish_action_desc_pl: "<c>yellow<c>You<c>white<c> attempt to land a finishing blow on [TARGET], dealing [DMG] damage!",
  invigorating_finish_action_desc: "attemps to land a finishing blow on [TARGET], dealing [DMG] damage.",
  warrior_shout_name: "Warrior Shout!",
  warrior_shout_desc: "Encourage yourself and horrify opponents \nwith a bloodcurdling scream!",
  warrior_shout_action_desc_pl: "<c>yellow<c>You<c>white<c> shout so loudly that the noise itself becomes harmful to others!",
  warrior_shout_action_desc_aoe_pl: "[TARGET] is struck by the sonic blast, taking [DMG] damage!",
  totem_of_arrows_name: "Totem of Arrows",
  totem_of_arrows_desc: "Totem that fires arrows at your enemies. Immobile.",
  totem_of_arrows_action_desc_pl: "You place an arrow totem on the field.",
  ranger_wolf_name: "Ranger's Wolf",
  ranger_wolf_desc: "Man's best friend.",
  ranger_wolf_action_desc_pl: "You whistle for your Wolf, and it appears before you in the blink of an eye.",
  awaken_name: "Awaken",
  awaken_desc: "Focus your senses to see further and be more accurate.",
  awaken_action_desc_pl: "You focus your senses to your sight.",
  finishing_blow_name: "Finishing Blow",
  finishing_blow_desc: "Sacrifice your life to end your foes'",
  finishing_blow_action_desc_pl: "<c>yellow<c>You<c>white<c> enhance your next attack with your vitality, dealing [DMG] damage to [TARGET]!",
  finishing_blow_action_desc: "enhances their blow with their vitality, dealing [DMG] to [TARGET]!",
  sundering_arrow_name: "Sundering Arrow",
  sundering_arrow_desc: "Reduce your enemy's defense by half from afar.",
  sundering_arrow_action_desc_pl: "<c>yellow<c>You<c>white<c> shoot a sundering arrow at [TARGET], harming them for [DMG] damage!",
  sundering_arrow_action_desc: "fires a sundering arrow at [TARGET], causing [DMG] damage.",
  shock_arrow_name: "Shock Arrow",
  shock_arrow_desc: "Paralyze an enemy.",
  shock_arrow_action_desc_pl: "<c>yellow<c>You<c>white<c> fire a paralyzing arrow at [TARGET], dealing [DMG] damage and leaving them paralyzed!",
  shock_arrow_action_desc: "fires a paralyzing arrow at [TARGET], leaving them paralyzed with [DMG] damage!",

  // CLASSES
  fighterClass_name: "Fighter",
  barbarianClass_name: "Barbarian",
  sorcererClass_name: "Sorcerer",
  rogueClass_name: "Rogue",
  rangerClass_name: "Ranger",

  // PERKS //

  // SORCERER
  introduction_to_sorcery_name: "Introduction to Sorcery",
  introduction_to_sorcery_desc: "Even the greatest of mages \nmust start somewhere.",
  intent_studies_name: "Intent Studies",
  intent_studies_desc: "Learning is a sign of good fortune.",
  might_of_magic_name: "Might of Magic",
  might_of_magic_desc: "Harness the power of sorcery.",
  spells_of_battle_name: "Spells of Battle",
  spells_of_battle_desc: "In battle only the most simple of spells will act consistently.",
  school_of_fire_name: "The School of Fire",
  school_of_fire_desc: "Your will burns like a great bonfire.",
  molded_by_flame_name: "Molded by Flame",
  molded_by_flame_desc: "Become one with fire.",
  shield_of_ages_name: "Shield of Ages",
  shield_of_ages_desc: "Proper magisters prepare measures against magic.",
  shield_of_aurous_name: "Ward of Aurous",
  shield_of_aurous_desc: "Aurous himself protects you with his warmth.",
  burning_passion_name: "Burning Passion",
  burning_passion_desc: "Your passion for magic is set ablaze!",
  wisdoms_of_the_past_name: "Wisdoms of the Past",
  wisdoms_of_the_past_desc: "Knowledge from the past protects the future.",
  flame_wizard_fury_name: "The Flame Wizard's Fury",
  flame_wizard_fury_desc: "Your foes shall tremble at your flaming fury!",
  makings_of_a_summoner_name: "The Summoner King's Call",
  makings_of_a_summoner_desc: "In order to become a king of magic, one must have servants.",
  magical_bonds_name: "Bonds forged from Magic",
  magical_bonds_desc: "Steel, faith nor gunpowder will stop my puppets!",
  elemental_mage_name: "Master of the Elements",
  elemental_mage_desc: "Elements of nature bend to your will.",
  piercing_javelin_name: "Armour Piercing Javelin",
  piercing_javelin_desc: "This one packs a ton of punch.",

  // FIGHTER
  battle_sense_name: "Battle Sense",
  battle_sense_desc: "After numerous battles, you have developed a keen sense for danger",
  fighters_vitality_name: "Fighter's Vitality",
  fighters_vitality_desc: "Combat necessitates the sturdiest of bodies.",
  patient_blow_name: "Patient Blow",
  patient_blow_desc: "Careful observation is a fighter's greatest asset.",
  strength_training_name: "Strength Training",
  strength_training_desc: "When tactics fail, strength is relied upon.",
  fighting_style_name: "Fighting Style",
  fighting_style_desc: "I fear not the man who has practiced 10 000 blows once, \nbut I fear the man who has practiced one blow 10 000 times.",
  furious_assault_name: "Furious Assault",
  furious_assault_desc: "Nothing will be gained without a hearty offensive!",
  tactical_genius_name: "Tactical Genius",
  tactical_genius_desc: "Keeping a calm mind in the midst of battle grants one an immense advantage.",
  resistant_in_melee_name: "Resistant in Melee",
  resistant_in_melee_desc: "Developing keen sense of the melee allows you to avoid some blows.",
  charging_bull_name: "Charging Bull",
  charging_bull_desc: "The enemy will be disoriented by a sudden frontal charge!",
  concentrated_warrior_name: "Balanced Warrior",
  concentrated_warrior_desc: "Combining patience with unrelenting offense fells all evils.",
  absorber_of_life_force_name: "Absorber of Life Force",
  absorber_of_life_force_desc: "When there's no chance for rest between combats, \none must reinvigorate oneself from combat itself.",
  fighting_with_your_voice_name: "A Helping Voice",
  fighting_with_your_voice_desc: "Sometimes all you need to push forward is an encouraging shout.",

  // ROGUE
  way_of_the_rogue_name: "Way of the Rogue",
  way_of_the_rogue_desc: "Fight from the shadows, never risking your skin!",
  weakpoint_spotter_name: "Weakpoint Spotter",
  weakpoint_spotter_desc: "Strike only at the most opportune moment.",
  shadow_warrior_name: "Shadow Warrior",
  shadow_warrior_desc: "Keep your distance from the foe.",
  fighting_dirty_name: "Fighting Dirty",
  fighting_dirty_desc: "Honor and fairness are excellent ways to get killed.",
  glass_cannon_name: "Glass Cannon",
  glass_cannon_desc: "Make every blow count, for they could be the last.",
  ranged_expert_name: "Ranged Expert",
  ranged_expert_desc: "Pelt them with arrows.",
  poison_specialist_name: "Poison Specialist",
  poison_specialist_desc: "Poison can always be relied upon.",
  simple_strokes_name: "Simple Strokes",
  simple_strokes_desc: "Become a well tuned killing machine.",
  dance_of_death_name: "Dance of Death",
  dance_of_death_desc: "No amount of struggling will stop me!",
  poison_from_afar_name: "Filthy Marksman",
  poison_from_afar_desc: "I'll just stay safe here while you die over there.",
  quicker_draw_name: "Quicker Draw",
  quicker_draw_desc: "Faster, faster!",
  smoke_screen_name: "Smoke Screen",
  smoke_screen_desc: "Deprive your foes of their senses.",
  sneakier_stabbing_name: "Sneakier Stabbing",
  sneakier_stabbing_desc: "Exploit your opponents allergy to multiple stab wounds.",
  smoke_and_mirrors_name: "Smoke & Mirrors",
  smoke_and_mirrors_desc: "That's all it takes to fool even the sane.",
  tricky_distraction_name: "Tricky Distraction",
  tricky_distraction_desc: "Make your foes go after the wrong target.",
  poison_taster_name: "Poison Taster",
  poison_taster_desc: "Can't accidentally poison yourself if you do it intentionally!",

  // BARBARIAN
  thrill_of_battle_name: "Thrill of Battle",
  thrill_of_battle_desc: "Revel in your lust for combat.",
  weapon_mastery_name: "Weapon Mastery",
  weapon_mastery_desc: "What good is strength if you can't use it?",
  raging_charge_name: "Raging Charge",
  raging_charge_desc: "Sometimes the deciding factor is a frontal assault.",
  hardened_constitution_name: "Hardened Constitution",
  hardened_constitution_desc: "Living in tribes toughens the body.",
  power_of_injuries_name: "Power through Injury",
  power_of_injuries_desc: "Pain is a reminder that you are still alive!",
  sharp_senses_name: "Sixth Sense",
  sharp_senses_desc: "Put your life in the line and you'll accomplish heroic deeds.",
  perk_barbarian_rage_name: "Raging",
  perk_barbarian_rage_desc: "Rage, fury and anger are all necessary emotions in the wild!",
  impatient_name: "Impatient",
  impatient_desc: "Hurry it up, I need to FIGHT!",
  ultimate_warrior_name: "Ultimate Warrior",
  ultimate_warrior_desc: "I win because I place victory before survival!",
  unyielding_rage_name: "Continuous Rage",
  unyielding_rage_desc: "This rage is unyielding, it consumes me!",
  perk_finishing_blow_name: "Finishing Blow",
  perk_finishing_blow_desc: "End your opponent at the cost of your own body.",
  true_finish_name: "Last Bits of Strength",
  true_finish_desc: "Anything you can muster will go in this attack!",
  perk_berserker_name: "Death over Dishonor",
  perk_berserker_desc: "I MUST LIVE ONLY AS LONG AS IT TAKES FOR YOU TO STOP DOING SO!",
  perk_calmer_berserk_name: "On Second Thought...",
  perk_calmer_berserk_desc: "Maybe I can keep living and still kill you!",

  // RANGER
  target_practice_name: "Target Practice",
  target_practice_desc: "Practice makes perfect.",
  call_of_the_forest_name: "Call of the Forest",
  call_of_the_forest_desc: "Your very body itself is made for the wilds.",
  powered_arrow_name: "Powered Arrow",
  powered_arrow_desc: "This shot will leave a mark.",
  rapid_fire_name: "Rapid Fire",
  rapid_fire_desc: "Leave them no time to recover!",
  critical_hit_name: "Critical Hit",
  critical_hit_desc: "Finish the job with a brutal blow.",
  rangers_call_name: "Call of the Ranger",
  rangers_call_desc: "The Wilds themselves are calling to you!",
  awakening_name: "Awakening of the Wild",
  awakening_desc: "Your true purpose is making itself known.",
  hunter_mark_name: "The Hunter's Mark",
  hunter_mark_desc: "The Wilds have recognized you as a true ranger.",
  wild_call_name: "Ranger's Companion",
  wild_call_desc: "You need not be alone on this journey.",
  trusted_companion_name: "Trusted Companion",
  trusted_companion_desc: "You can trust everything to your friend.",
  fierce_beast_name: "Fierce Beast",
  fierce_beast_desc: "The Wild molds its servants.",
  shocking_assault_name: "Shocking Assault",
  shocking_assault_desc: "This'll sting for sure!",
  leave_you_paralyzed_name: "♪ Leave you feeling paralyzed ♪",
  leave_you_paralyzed_desc: "You won't be getting up after this one.",

  // ADVENTURER
  hearty_adventurer_1_name: "Hearty Adventurer I",
  hearty_adventurer_1_desc: "Toughening up.",
  hearty_adventurer_2_name: "Hearty Adventurer II",
  hearty_adventurer_2_desc: "Toughening up.",
  hearty_adventurer_3_name: "Hearty Adventurer III",
  hearty_adventurer_3_desc: "Toughening up.",
  hearty_adventurer_4_name: "Hearty Adventurer IV",
  hearty_adventurer_4_desc: "Toughening up.",
  hearty_adventurer_5_name: "Hearty Adventurer V",
  hearty_adventurer_5_desc: "Toughening up.",
  first_aid_expert_name: "First Aid Expert",
  first_aid_expert_desc: "Good vibes.",
  cleanser_name: "Cleanser",
  cleanser_desc: "Better vibes.",
  advancing_backwards_name: "Advancing Backwards",
  advancing_backwards_desc: "Bravely running away.",

  // NECROMANCER
  pursuit_of_undeath_name: "Pursuit of Undeath",
  pursuit_of_undeath_desc: "Pursuing undeath.",

  // Settings tooltips
  log_char_movement: "<f>16px<f>Logs enemy movement in the text area every turn. \nCan clutter the text screen.",
  toggle_minimap: "<f>16px<f>The minimap helps with navigating through areas. \nCan cause the game to run slower.",
  hide_helmet: "<f>16px<f>Toggle helmet visiblity to see or hide character's face.",
  randomize_items: "<f>16px<f>Equipment generates random extra stats.\nGives the game a more roguelike feeling.",
  interact_help: "<f>16px<f>Open chests or pick loot when standing on the same tile. \nAlso used to talk to NPCs and interact with world.",
  world_messages: "<f>16px<f>View more action messages displayed in the bottom left.",
  toggle_rangedMode: "<f>16px<f>Ranged mode allows you to see where your ranged weapon can reach.",
  ui_scale: "<f>16px<f>Scales UI-elements based on multiplier.\nChange this value if UI is too large or small.",
} as any;

var lang = english;