const items = {
  awesomeGoldBow: {
    id: "awesomeGoldBow",
    name: "Awesome Golden Bow",
    damages: { pierce: 30, magic: 8 },
    requiresStats: { dex: 12 },
    range: 12,
    img: "/resources/icons/goldBow.png",
    sprite: "goldBow",
    price: 2500,
    weight: 2,
    type: "weapon",
    firesProjectile: "arrowProjectile",
    statBonus: "dex",
    grade: "rare",
    slot: "weapon",
    spriteMap: { x: 2048, y: 0 },
  },
  apprenticeWand: {
    id: "apprenticeWand",
    name: "Apprentice Wand",
    damages: { magic: 100 },
    requiresStats: { int: 5 },
    stats: {
      magicDamageP: 5,
    },
    range: 6,
    img: "resources/icons/apprentice_wand.png",
    sprite: "apprenticeWand",
    price: 25,
    weight: 1.2,
    type: "weapon",
    firesProjectile: "magicBlastProjectile",
    statBonus: "int",
    grade: "common",
    slot: "weapon",
    spriteMap: { x: 2176, y: 0 },
  },
  dualDaggers: {
    id: "dualDaggers",
    name: "Dual Daggers",
    damages: { slash: 50, pierce: 80 },
    range: 1,
    img: "resources/icons/dual_daggers.png",
    sprite: "rustyDualDaggers",
    stats: {
      attackSpeedV: 25,
    },
    twoHanded: true,
    price: 70,
    weight: 2.3,
    type: "weapon",
    statBonus: "dex",
    grade: "uncommon",
    slot: "weapon",
    spriteMap: { x: 256, y: 0 },
  },
};
