interface grades {
  [common: string]: any;
  uncommon: any;
  rare: any;
  mythical: any;
  legendary: any;
}

const grades = {
  common: {
    color: "#e0e0e0",
    worth: 1
  },
  uncommon: {
    color: "#7ccf63",
    worth: 2
  },
  rare: {
    color: "#4287f5",
    worth: 3.25
  },
  mythical: {
    color: "#5e18a3",
    worth: 5
  },
  legendary: {
    color: "#cfcf32",
    worth: 8
  }
} as grades;

const items = {
  dagger: {
    id: "dagger",
    name: "Dagger",
    damages: { slash: 4 },
    damagesTemplate: [
      { type: "slash", value: [1, 2], chance: 10 },
      { type: "dark", value: [1, 5], chance: 4 },
      { type: "divine", value: [1, 5], chance: 4 },
      { type: "fire", value: [1, 5], chance: 7 },
      { type: "lightning", value: [1, 5], chance: 5 },
      { type: "ice", value: [1, 5], chance: 5 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 3], chance: 1.25 },
      { type: "strP", value: [3, 5, 9], chance: 1 },
      { type: "dexV", value: [1, 2, 3], chance: 1.75 },
      { type: "dexP", value: [3, 5, 7], chance: 1.5 },
      { type: "vitV", value: [1, 2, 3], chance: 1.25 },
    ],
    range: 1,
    img: "resources/icons/weapon_dagger.png",
    sprite: "rustyDagger",
    price: 10,
    weight: 1.2,
    type: "weapon",
    statBonus: "dex",
    grade: "common",
    slot: "weapon"
  },
  stick: {
    id: "stick",
    name: "Stick",
    damages: { crush: 3 },
    damagesTemplate: [
      { type: "crush", value: [1, 1], chance: 8 },
      { type: "dark", value: [1, 2], chance: 4 },
      { type: "divine", value: [1, 2], chance: 4 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2], chance: 1.25 },
      { type: "dexV", value: [1, 2], chance: 1.75 },
    ],
    range: 1,
    img: "resources/icons/weapon_club.png",
    sprite: "stick",
    price: 10,
    weight: 0.9,
    type: "weapon",
    statBonus: "str",
    grade: "common",
    slot: "weapon"
  },
  trollClub: {
    id: "trollClub",
    name: "Troll Club",
    damages: { crush: 13 },
    damagesTemplate: [
      { type: "crush", value: [2, 6], chance: 7 },
      { type: "dark", value: [4, 5], chance: 4 },
      { type: "divine", value: [4, 5], chance: 4 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 4, 7], chance: 1.25 },
      { type: "dexV", value: [1, 2, 4, 7], chance: 1.75 },
    ],
    stats: {
      hitChanceV: 5
    },
    requiresStats: {
      str: 18
    },
    range: 1,
    img: "resources/icons/troll_club.png",
    sprite: "trollClub",
    price: 75,
    weight: 5.4,
    type: "weapon",
    statBonus: "str",
    twoHanded: true,
    grade: "uncommon",
    slot: "weapon"
  },
  chippedBlade: {
    id: "chippedBlade",
    name: "Chipped Longsword",
    damages: { slash: 5, pierce: 1 },
    damagesTemplate: [
      { type: "slash", value: [2, 4], chance: 10 },
      { type: "pierce", value: [1, 2], chance: 10 },
      { type: "dark", value: [2, 5], chance: 4 },
      { type: "divine", value: [2, 5], chance: 4 },
      { type: "fire", value: [2, 5], chance: 7 },
      { type: "lightning", value: [2, 5], chance: 5 },
      { type: "ice", value: [2, 5], chance: 5 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 4], chance: 1.25 },
      { type: "strP", value: [3, 5, 9], chance: 1 },
      { type: "dexV", value: [1, 2, 3], chance: 1.75 },
      { type: "dexP", value: [3, 5, 7], chance: 1.5 },
      { type: "vitV", value: [1, 2, 3], chance: 1.25 },
      { type: "vitP", value: [3, 5, 7], chance: 1.25 },
    ],
    range: 1,
    img: "resources/icons/weapon_chipped_blade.png",
    sprite: "chippedBlade",
    price: 18,
    weight: 2.1,
    type: "weapon",
    statBonus: "str",
    grade: "common",
    slot: "weapon"
  },
  longsword: {
    id: "longsword",
    name: "Longsword",
    damages: { slash: 6, pierce: 3 },
    damagesTemplate: [
      { type: "slash", value: [1, 2], chance: 4 },
      { type: "pierce", value: [1, 2], chance: 4 },
      { type: "dark", value: [2, 5], chance: 4 },
      { type: "divine", value: [2, 5], chance: 4 },
      { type: "fire", value: [4, 6], chance: 6 },
      { type: "lightning", value: [4, 6], chance: 6 },
      { type: "ice", value: [2, 4], chance: 5 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 4], chance: 1.75 },
      { type: "strP", value: [3, 5, 9], chance: 1 },
      { type: "dexV", value: [1, 2, 4], chance: 1.75 },
      { type: "dexP", value: [3, 5, 7], chance: 1.5 },
      { type: "vitV", value: [1, 2, 4], chance: 1.25 },
      { type: "vitP", value: [3, 5, 7], chance: 1.25 },
    ],
    requiresStats: {
      str: 8
    },
    range: 1,
    img: "resources/icons/weapon_blade.png",
    sprite: "blade",
    price: 60,
    weight: 2.4,
    type: "weapon",
    statBonus: "str",
    grade: "common",
    slot: "weapon"
  },
  silverSword: {
    id: "silverSword",
    name: "Silver Sword",
    damages: { slash: 10, pierce: 5, magic: 5 },
    damagesTemplate: [
      { type: "slash", value: [3, 7], chance: 4 },
      { type: "pierce", value: [3, 6], chance: 4 },
      { type: "magic", value: [3, 6], chance: 4 },
      { type: "dark", value: [3, 6], chance: 4 },
      { type: "divine", value: [2, 5], chance: 4 },
      { type: "fire", value: [4, 6], chance: 6 },
      { type: "lightning", value: [4, 6], chance: 6 },
      { type: "ice", value: [2, 4], chance: 5 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 4], chance: 3.25 },
      { type: "strP", value: [3, 5, 9], chance: 4 },
      { type: "dexV", value: [1, 2, 4], chance: 3.25 },
      { type: "dexP", value: [3, 5, 7], chance: 4 },
      { type: "vitV", value: [1, 2, 4], chance: 3.25 },
      { type: "vitP", value: [3, 5, 7], chance: 4 },
    ],
    requiresStats: {
      str: 10,
      dex: 4
    },
    range: 1,
    img: "resources/icons/silver_sword.png",
    sprite: "silverSword",
    price: 500,
    weight: 2.4,
    type: "weapon",
    statBonus: "str",
    grade: "rare",
    slot: "weapon"
  },
  chippedAxe: {
    id: "chippedAxe",
    name: "Chipped Axe",
    damages: { crush: 6, pierce: 1 },
    damagesTemplate: [
      { type: "crush", value: [2, 3], chance: 4 },
      { type: "pierce", value: [1, 3], chance: 4 },
      { type: "dark", value: [2, 5], chance: 4 },
      { type: "divine", value: [2, 5], chance: 5 },
      { type: "fire", value: [2, 4], chance: 7 },
      { type: "lightning", value: [2, 5], chance: 7 },
      { type: "ice", value: [2, 4], chance: 5 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 3], chance: 1.75 },
      { type: "strP", value: [3, 5, 9], chance: 1 },
      { type: "dexV", value: [1, 2, 3], chance: 1.75 },
      { type: "dexP", value: [3, 5, 7], chance: 1.5 },
      { type: "vitV", value: [1, 2, 3], chance: 1.25 },
      { type: "vitP", value: [3, 5, 7], chance: 1.25 },
    ],
    range: 1,
    img: "resources/icons/chipped_axe.png",
    sprite: "chippedAxe",
    price: 35,
    weight: 2.9,
    type: "weapon",
    statBonus: "str",
    grade: "common",
    slot: "weapon"
  },
  huntingBow: {
    id: "huntingBow",
    name: "Hunting Bow",
    damages: { pierce: 5 },
    damagesTemplate: [
      { type: "pierce", value: [1, 2], chance: 8 },
      { type: "dark", value: [1, 2], chance: 4 },
      { type: "divine", value: [1, 2], chance: 4 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 3], chance: 1.25 },
      { type: "dexV", value: [1, 2, 3], chance: 1.75 },
    ],
    requiresStats: {
      dex: 5
    },
    range: 7,
    img: "resources/icons/weapon_bow.png",
    sprite: "bow",
    price: 10,
    weight: 0.9,
    type: "weapon",
    firesProjectile: "arrowProjectile",
    statBonus: "dex",
    grade: "common",
    slot: "weapon"
  },
  apprenticeWand: {
    id: "apprenticeWand",
    name: "Apprentice Wand",
    damages: { magic: 5 },
    damagesTemplate: [
      { type: "magic", value: [1, 3], chance: 5 },
      { type: "dark", value: [1, 2], chance: 4 },
      { type: "divine", value: [1, 2], chance: 4 },
    ],
    statsTemplate: [
      { type: "intV", value: [1, 2, 3], chance: 1.25 },
      { type: "dexV", value: [1, 2, 3], chance: 1.75 },
    ],
    requiresStats: {
      int: 5
    },
    stats: {
      magicDamageP: 5
    },
    range: 6,
    img: "resources/icons/apprentice_wand.png",
    sprite: "apprenticeWand",
    price: 25,
    weight: 1.2,
    type: "weapon",
    firesProjectile: "magicBlastProjectile",
    statBonus: "int",
    grade: "common",
    slot: "weapon"
  },
  woodenShield: {
    id: "woodenShield",
    name: "Wooden Shield",
    resistances: { slash: 5, crush: 5, pierce: 5, fire: -5, magic: 5, dark: 3, divine: 3, lightning: 2, ice: 1 },
    resistancesTemplate: [
      { type: "slash", value: [1, 2], chance: 5 },
      { type: "crush", value: [2, 5], chance: 7 },
      { type: "dark", value: [1, 3], chance: 5 },
      { type: "divine", value: [1, 3], chance: 5 },
      { type: "fire", value: [-1, -3], chance: 5 },
      { type: "lightning", value: [-1, -3], chance: 5 },
      { type: "ice", value: [2, 4], chance: 5 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 3], chance: 1.25 },
      { type: "strP", value: [3, 5, 8], chance: 2.5 },
      { type: "dexV", value: [1, 2, 3], chance: 1.75 },
      { type: "dexP", value: [3, 5, 7], chance: 1.5 },
      { type: "vitV", value: [1, 2, 4], chance: 1.75 },
      { type: "vitP", value: [3, 6, 9], chance: 1.8 },
      { type: "hpMaxV", value: [4, 8, 12], chance: 3.5 },
    ],
    img: "resources/icons/wooden_shield.png",
    sprite: "woodenShield",
    price: 13,
    weight: 1.2,
    type: "armor",
    grade: "common",
    slot: "offhand"
  },
  ironShield: {
    id: "ironShield",
    name: "Iron Shield",
    resistances: { slash: 13, crush: 9, pierce: 11, fire: 4, magic: 2, dark: 2, divine: 4, lightning: 1, ice: 5 },
    resistancesTemplate: [
      { type: "pierce", value: [2, 5], chance: 5 },
      { type: "slash", value: [3, 7], chance: 5 },
      { type: "crush", value: [2, 5], chance: 7 },
      { type: "dark", value: [2, 5], chance: 5 },
      { type: "divine", value: [2, 5], chance: 5 },
      { type: "fire", value: [1, 3], chance: 5 },
      { type: "lightning", value: [1, 2], chance: 5 },
      { type: "ice", value: [2, 4], chance: 5 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 3, 4], chance: 1.25 },
      { type: "strP", value: [3, 5, 8, 10], chance: 2.5 },
      { type: "dexV", value: [1, 2, 3, 5], chance: 1.75 },
      { type: "dexP", value: [3, 5, 7, 9], chance: 1.5 },
      { type: "vitV", value: [1, 2, 4, 5], chance: 1.75 },
      { type: "vitP", value: [3, 6, 9, 11], chance: 1.8 },
      { type: "hpMaxV", value: [4, 8, 12, 15], chance: 3.5 },
    ],
    requiresStats: {
      str: 6,
      vit: 8
    },
    img: "resources/icons/iron_shield.png",
    sprite: "ironShield",
    price: 62,
    weight: 3.1,
    type: "armor",
    grade: "uncommon",
    slot: "offhand"
  },
  silverShield: {
    id: "silverShield",
    name: "Silver Shield",
    resistances: { slash: 18, crush: 12, pierce: 14, fire: 9, magic: 7, dark: 5, divine: 8, lightning: 0, ice: 2 },
    resistancesTemplate: [
      { type: "pierce", value: [3, 6], chance: 5 },
      { type: "slash", value: [4, 8], chance: 5 },
      { type: "crush", value: [3, 6], chance: 7 },
      { type: "dark", value: [3, 6], chance: 5 },
      { type: "divine", value: [3, 6], chance: 5 },
      { type: "fire", value: [1, 2], chance: 5 },
      { type: "lightning", value: [1, 2], chance: 5 },
      { type: "ice", value: [1, 2], chance: 5 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 3, 4], chance: 3 },
      { type: "strP", value: [3, 5, 8, 10], chance: 4.5 },
      { type: "dexV", value: [1, 2, 3, 5], chance: 3.25 },
      { type: "dexP", value: [3, 5, 7, 9], chance: 2.75 },
      { type: "vitV", value: [1, 2, 4, 5], chance: 3.25 },
      { type: "vitP", value: [3, 6, 9, 11], chance: 3.4 },
      { type: "hpMaxV", value: [4, 8, 12, 15], chance: 5.75 },
    ],
    requiresStats: {
      str: 7,
      dex: 7,
      vit: 7
    },
    img: "resources/icons/silver_shield.png",
    sprite: "silverShield",
    price: 255,
    weight: 4.5,
    type: "armor",
    grade: "rare",
    slot: "offhand"
  },
  raggedShirt: {
    id: "raggedShirt",
    name: "Ragged Shirt",
    resistances: { slash: 1, crush: 5, pierce: 2, fire: -2, ice: 2 },
    resistancesTemplate: [
      { type: "slash", value: [1, 2], chance: 5 },
      { type: "crush", value: [2, 5], chance: 7 },
      { type: "dark", value: [1, 3], chance: 5 },
      { type: "divine", value: [1, 3], chance: 5 },
      { type: "fire", value: [-1, -3], chance: 5 },
      { type: "lightning", value: [-1, -3], chance: 5 },
      { type: "ice", value: [2, 4], chance: 5 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 3], chance: 1.25 },
      { type: "strP", value: [3, 5, 8], chance: 2.5 },
      { type: "dexV", value: [1, 2, 3], chance: 1.75 },
      { type: "dexP", value: [3, 5, 7], chance: 1.5 },
      { type: "vitV", value: [1, 2, 4], chance: 1.75 },
      { type: "vitP", value: [3, 6, 9], chance: 1.8 },
      { type: "hpMaxV", value: [4, 8, 12], chance: 3.5 },
    ],
    img: "resources/icons/ragged_shirt.png",
    sprite: "raggedShirt",
    price: 6,
    weight: 0.8,
    type: "armor",
    grade: "common",
    slot: "chest"
  },
  raggedPants: {
    id: "raggedPants",
    name: "Ragged Pants",
    resistances: { slash: 2, crush: 4, pierce: 2, fire: -1, ice: 1 },
    resistancesTemplate: [
      { type: "slash", value: [1, 3], chance: 5 },
      { type: "crush", value: [1, 3], chance: 7 },
      { type: "dark", value: [1, 3], chance: 5 },
      { type: "divine", value: [1, 3], chance: 5 },
      { type: "fire", value: [-1, -2], chance: 5 },
      { type: "lightning", value: [-1, -2], chance: 5 },
      { type: "ice", value: [2, 3], chance: 10 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 3], chance: 1.25 },
      { type: "strP", value: [3, 5, 8], chance: 2.5 },
      { type: "dexV", value: [1, 2, 3], chance: 1.75 },
      { type: "dexP", value: [3, 5, 7], chance: 1.5 },
      { type: "vitV", value: [1, 2, 4], chance: 1.75 },
      { type: "vitP", value: [3, 6, 9], chance: 1.8 },
      { type: "hpMaxV", value: [4, 8, 12], chance: 3.5 },
    ],
    img: "resources/icons/ragged_pants.png",
    sprite: "raggedPants",
    price: 5,
    weight: 0.8,
    type: "armor",
    grade: "common",
    slot: "legs"
  },
  raggedBoots: {
    id: "raggedBoots",
    name: "Ragged Boots",
    resistances: { slash: 1, crush: 3, pierce: 2, fire: -1, ice: 1 },
    resistancesTemplate: [
      { type: "slash", value: [1, 1], chance: 5 },
      { type: "crush", value: [1, 3], chance: 7 },
      { type: "pierce", value: [1, 2], chance: 5 },
      { type: "dark", value: [1, 2], chance: 5 },
      { type: "divine", value: [1, 2], chance: 5 },
      { type: "fire", value: [-1, -3], chance: 5 },
      { type: "lightning", value: [-1, -3], chance: 5 },
      { type: "ice", value: [2, 3], chance: 5 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 3], chance: 1.25 },
      { type: "strP", value: [2, 4, 6], chance: 1 },
      { type: "dexV", value: [1, 2, 3], chance: 1.75 },
      { type: "dexP", value: [3, 5, 7], chance: 1.5 },
    ],
    img: "resources/icons/ragged_boots.png",
    sprite: "raggedBoots",
    price: 4,
    weight: 0.2,
    type: "armor",
    grade: "common",
    slot: "boots"
  },
  raggedGloves: {
    id: "raggedGloves",
    name: "Ragged Gloves",
    resistances: { slash: 1, crush: 2, pierce: 2, fire: -1, ice: 1 },
    resistancesTemplate: [
      { type: "slash", value: [1, 1], chance: 5 },
      { type: "crush", value: [1, 3], chance: 7 },
      { type: "pierce", value: [1, 2], chance: 5 },
      { type: "dark", value: [1, 2], chance: 5 },
      { type: "divine", value: [1, 2], chance: 5 },
      { type: "fire", value: [-1, -2], chance: 5 },
      { type: "lightning", value: [-1, -2], chance: 5 },
      { type: "ice", value: [2, 3], chance: 5 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 3], chance: 1.25 },
      { type: "strP", value: [2, 4, 6], chance: 1 },
      { type: "dexV", value: [1, 2, 3], chance: 1.75 },
      { type: "dexP", value: [3, 5, 7], chance: 1.5 },
    ],
    img: "resources/icons/gloves.png",
    sprite: "raggedGloves",
    price: 3,
    weight: 0.15,
    type: "armor",
    grade: "common",
    slot: "gloves"
  },
  enchantedCap: {
    id: "enchantedCap",
    name: "Enchanted Cap of Untold Skeletal Might",
    resistances: { slash: 70, crush: 70, pierce: 70, magic: 70, fire: 70, ice: 70, dark: 70, divine: 70, lightning: 70 },
    resistancesTemplate: [
      { type: "slash", value: [1, 1], chance: 5 },
      { type: "crush", value: [1, 3], chance: 7 },
      { type: "pierce", value: [1, 2], chance: 5 },
      { type: "dark", value: [1, 2], chance: 5 },
      { type: "divine", value: [1, 2], chance: 5 },
      { type: "fire", value: [-1, -2], chance: 5 },
      { type: "lightning", value: [-1, -2], chance: 5 },
      { type: "ice", value: [2, 3], chance: 5 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 3], chance: 1.25 },
      { type: "strP", value: [2, 4, 6], chance: 1 },
      { type: "dexV", value: [1, 2, 3], chance: 1.75 },
      { type: "dexP", value: [3, 5, 7], chance: 1.5 },
    ],
    stats: {
      dexP: 200,
      strP: 200,
      vitP: 200,
      intV: 100,
      cunV: -25
    },
    coversHair: true,
    img: "resources/icons/kas_dj.png",
    sprite: "kasDJ",
    price: 25000,
    weight: 0.1,
    type: "armor",
    grade: "legendary",
    slot: "helmet"
  },
  raggedHood: {
    id: "raggedHood",
    name: "Ragged Hood",
    resistances: { slash: 2, crush: 3, pierce: 3, fire: -2, ice: 1, dark: 1, divine: 1 },
    resistancesTemplate: [
      { type: "slash", value: [1, 1], chance: 5 },
      { type: "crush", value: [1, 3], chance: 7 },
      { type: "pierce", value: [1, 2], chance: 5 },
      { type: "dark", value: [1, 2], chance: 5 },
      { type: "divine", value: [1, 2], chance: 5 },
      { type: "fire", value: [-1, -2], chance: 5 },
      { type: "lightning", value: [-1, -2], chance: 5 },
      { type: "ice", value: [2, 3], chance: 5 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 3], chance: 1.25 },
      { type: "strP", value: [2, 4, 6], chance: 1 },
      { type: "dexV", value: [1, 2, 3], chance: 1.75 },
      { type: "dexP", value: [3, 5, 7], chance: 1.5 },
    ],
    coversHair: true,
    img: "resources/icons/ragged_hood.png",
    sprite: "raggedHood",
    price: 5,
    weight: 0.2,
    type: "armor",
    grade: "common",
    slot: "helmet"
  },
  leatherChest: {
    id: "leatherChest",
    name: "Leather Chest",
    resistances: { slash: 4, crush: 7, pierce: 5, magic: 5,  ice: 2, lightning: 3, dark: 1, divine: 1, fire: 2 },
    resistancesTemplate: [
      { type: "slash", value: [1, 4], chance: 7 },
      { type: "crush", value: [1, 4], chance: 7 },
      { type: "pierce", value: [1, 4], chance: 7 },
      { type: "magic", value: [1, 4], chance: 7 },
      { type: "dark", value: [1, 4], chance: 7 },
      { type: "divine", value: [1, 4], chance: 7 },
      { type: "fire", value: [1, 4], chance: 7 },
      { type: "lightning", value: [1, 4], chance: 7 },
      { type: "ice", value: [1, 4], chance: 7 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 3, 4], chance: 1.75 },
      { type: "strP", value: [3, 5, 8, 10], chance: 3.25 },
      { type: "dexV", value: [1, 2, 3, 4], chance: 2.25 },
      { type: "dexP", value: [3, 5, 7, 9], chance: 2 },
      { type: "vitV", value: [1, 2, 4, 5], chance: 2.25 },
      { type: "vitP", value: [3, 6, 9, 12], chance: 2.45 },
      { type: "hpMaxV", value: [4, 8, 12, 16], chance: 4.5 },
    ],
    requiresStats: {
      vit: 5,
      dex: 6
    },
    img: "resources/icons/leather_chest.png",
    sprite: "leatherChest",
    price: 50,
    weight: 1.7,
    type: "armor",
    grade: "common",
    slot: "chest"
  },
  leatherLeggings: {
    id: "leatherLeggings",
    name: "Leather Leggings",
    resistances: { slash: 3, crush: 5, pierce: 4, magic: 4,  ice: 2, lightning: 2, dark: 1, divine: 1, fire: 1 },
    resistancesTemplate: [
      { type: "slash", value: [1, 3], chance: 7 },
      { type: "crush", value: [1, 3], chance: 7 },
      { type: "pierce", value: [1, 3], chance: 7 },
      { type: "magic", value: [1, 3], chance: 7 },
      { type: "dark", value: [1, 3], chance: 7 },
      { type: "divine", value: [1, 3], chance: 7 },
      { type: "fire", value: [1, 3], chance: 7 },
      { type: "lightning", value: [1, 3], chance: 7 },
      { type: "ice", value: [1, 3], chance: 7 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 3, 4], chance: 1.75 },
      { type: "strP", value: [3, 5, 8, 10], chance: 3.25 },
      { type: "dexV", value: [1, 2, 3, 4], chance: 2.25 },
      { type: "dexP", value: [3, 5, 7, 9], chance: 2 },
      { type: "vitV", value: [1, 2, 4, 5], chance: 2.25 },
      { type: "vitP", value: [3, 6, 9, 12], chance: 2.45 },
      { type: "hpMaxV", value: [4, 8, 12, 16], chance: 4.5 },
    ],
    requiresStats: {
      vit: 5,
      dex: 6
    },
    img: "resources/icons/leather_leg_bracers.png",
    sprite: "leatherLeggings",
    price: 45,
    weight: 1.5,
    type: "armor",
    grade: "common",
    slot: "legs"
  },
  leatherBracers: {
    id: "leatherBracers",
    name: "Leather Bracers",
    resistances: { slash: 2, crush: 3, pierce: 2, magic: 2,  ice: 1, lightning: 1, dark: 1, divine: 1, fire: 1 },
    resistancesTemplate: [
      { type: "slash", value: [1, 2], chance: 7 },
      { type: "crush", value: [1, 2], chance: 7 },
      { type: "pierce", value: [1, 2], chance: 7 },
      { type: "magic", value: [1, 2], chance: 7 },
      { type: "dark", value: [1, 2], chance: 7 },
      { type: "divine", value: [1, 2], chance: 7 },
      { type: "fire", value: [1, 2], chance: 7 },
      { type: "lightning", value: [1, 2], chance: 7 },
      { type: "ice", value: [1, 2], chance: 7 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 3], chance: 1.75 },
      { type: "strP", value: [3, 5, 8], chance: 3.25 },
      { type: "dexV", value: [1, 2, 3], chance: 2.25 },
      { type: "dexP", value: [3, 5, 7], chance: 2 },
      { type: "vitV", value: [1, 2, 4], chance: 2.25 },
      { type: "vitP", value: [3, 6, 9], chance: 2.45 },
      { type: "hpMaxV", value: [4, 8, 12], chance: 4.5 },
    ],
    requiresStats: {
      vit: 3,
      dex: 4
    },
    img: "resources/icons/leather_bracers.png",
    sprite: "leatherBracers",
    price: 25,
    weight: 0.65,
    type: "armor",
    grade: "common",
    slot: "gloves"
  },
  leatherHelmet: {
    id: "leatherHelmet",
    name: "Leather Helmet",
    resistances: { slash: 2, crush: 4, pierce: 2, magic: 2,  ice: 2, lightning: 2, dark: 2, divine: 2, fire: 2 },
    resistancesTemplate: [
      { type: "slash", value: [1, 2], chance: 7 },
      { type: "crush", value: [1, 2], chance: 7 },
      { type: "pierce", value: [1, 2], chance: 7 },
      { type: "magic", value: [1, 2], chance: 7 },
      { type: "dark", value: [1, 2], chance: 7 },
      { type: "divine", value: [1, 2], chance: 7 },
      { type: "fire", value: [1, 2], chance: 7 },
      { type: "lightning", value: [1, 2], chance: 7 },
      { type: "ice", value: [1, 2], chance: 7 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 3], chance: 1.75 },
      { type: "strP", value: [3, 5, 8], chance: 3.25 },
      { type: "dexV", value: [1, 2, 3], chance: 2.25 },
      { type: "dexP", value: [3, 5, 7], chance: 2 },
      { type: "vitV", value: [1, 2, 4], chance: 2.25 },
      { type: "vitP", value: [3, 6, 9], chance: 2.45 },
      { type: "hpMaxV", value: [4, 8, 12], chance: 4.5 },
    ],
    requiresStats: {
      vit: 3,
      dex: 4
    },
    coversHair: true,
    img: "resources/icons/leather_helmet.png",
    sprite: "leatherHelmet",
    price: 30,
    weight: 0.5,
    type: "armor",
    grade: "common",
    slot: "helmet"
  },
  leatherBoots: {
    id: "leatherBoots",
    name: "Leather Booots",
    resistances: { slash: 2, crush: 3, pierce: 2, magic: 1,  ice: 1, lightning: 1, dark: 1, divine: 1, fire: 1 },
    resistancesTemplate: [
      { type: "slash", value: [1, 2], chance: 7 },
      { type: "crush", value: [1, 2], chance: 7 },
      { type: "pierce", value: [1, 2], chance: 7 },
      { type: "magic", value: [1, 2], chance: 7 },
      { type: "dark", value: [1, 2], chance: 7 },
      { type: "divine", value: [1, 2], chance: 7 },
      { type: "fire", value: [1, 2], chance: 7 },
      { type: "lightning", value: [1, 2], chance: 7 },
      { type: "ice", value: [1, 2], chance: 7 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 3], chance: 1.75 },
      { type: "strP", value: [3, 5, 8], chance: 3.25 },
      { type: "dexV", value: [1, 2, 3], chance: 2.25 },
      { type: "dexP", value: [3, 5, 7], chance: 2 },
      { type: "vitV", value: [1, 2, 4], chance: 2.25 },
      { type: "vitP", value: [3, 6, 9], chance: 2.45 },
      { type: "hpMaxV", value: [4, 8, 12], chance: 4.5 },
    ],
    requiresStats: {
      vit: 3,
      dex: 4
    },
    img: "resources/icons/leather_boots.png",
    sprite: "leatherBoots",
    price: 25,
    weight: 0.75,
    type: "armor",
    grade: "common",
    slot: "boots"
  },
  ironArmor: {
    id: "ironArmor",
    name: "Iron Armour",
    resistances: { slash: 15, crush: 10, pierce: 14, magic: 8,  ice: 5, lightning: 3, dark: 6, divine: 6, fire: 7 },
    resistancesTemplate: [
      { type: "slash", value: [3, 8], chance: 7 },
      { type: "crush", value: [3, 8], chance: 7 },
      { type: "pierce", value: [3, 8], chance: 7 },
      { type: "magic", value: [3, 8], chance: 7 },
      { type: "dark", value: [3, 8], chance: 7 },
      { type: "divine", value: [3, 8], chance: 7 },
      { type: "fire", value: [3, 8], chance: 7 },
      { type: "lightning", value: [3, 8], chance: 7 },
      { type: "ice", value: [3, 8], chance: 7 },
    ],
    statsTemplate: [
      { type: "strV", value: [2, 4, 6, 8], chance: 1.75 },
      { type: "strP", value: [5, 8, 12, 15], chance: 3.25 },
      { type: "dexV", value: [2, 4, 6, 8], chance: 2.25 },
      { type: "dexP", value: [5, 8, 11, 14], chance: 2 },
      { type: "vitV", value: [2, 4, 5, 7], chance: 2.25 },
      { type: "vitP", value: [5, 7, 11, 15], chance: 2.45 },
      { type: "hpMaxV", value: [10, 15, 20, 25], chance: 4.5 },
    ],
    requiresStats: {
      vit: 10,
      str: 10
    },
    img: "resources/icons/iron_armor.png",
    sprite: "ironArmor",
    price: 200,
    weight: 10.5,
    type: "armor",
    grade: "uncommon",
    slot: "chest"
  },
  ironLegplates: {
    id: "ironLegplates",
    name: "Iron Legplates",
    resistances: { slash: 11, crush: 8, pierce: 10, magic: 6,  ice: 5, lightning: 3, dark: 5, divine: 5, fire: 5 },
    resistancesTemplate: [
      { type: "slash", value: [3, 7], chance: 7 },
      { type: "crush", value: [3, 7], chance: 7 },
      { type: "pierce", value: [3, 7], chance: 7 },
      { type: "magic", value: [3, 7], chance: 7 },
      { type: "dark", value: [3, 7], chance: 7 },
      { type: "divine", value: [3, 7], chance: 7 },
      { type: "fire", value: [3, 7], chance: 7 },
      { type: "lightning", value: [3, 7], chance: 7 },
      { type: "ice", value: [3, 7], chance: 7 },
    ],
    statsTemplate: [
      { type: "strV", value: [2, 4, 6, 8], chance: 1.75 },
      { type: "strP", value: [5, 8, 12, 15], chance: 3.25 },
      { type: "dexV", value: [2, 4, 6, 8], chance: 2.25 },
      { type: "dexP", value: [5, 8, 11, 14], chance: 2 },
      { type: "vitV", value: [2, 4, 5, 7], chance: 2.25 },
      { type: "vitP", value: [5, 7, 11, 15], chance: 2.45 },
      { type: "hpMaxV", value: [10, 15, 20, 25], chance: 4.5 },
    ],
    requiresStats: {
      vit: 10,
      str: 10
    },
    img: "resources/icons/iron_leg_plates.png",
    sprite: "ironLegplates",
    price: 150,
    weight: 5.25,
    type: "armor",
    grade: "uncommon",
    slot: "legs"
  },
  ironHelmet: {
    id: "ironHelmet",
    name: "Iron Helmet",
    resistances: { slash: 6, crush: 4, pierce: 5, magic: 4,  ice: 4, lightning: 1, dark: 3, divine: 3, fire: 4 },
    resistancesTemplate: [
      { type: "slash", value: [2, 5], chance: 7 },
      { type: "crush", value: [2, 5], chance: 7 },
      { type: "pierce", value: [2, 5], chance: 7 },
      { type: "magic", value: [2, 5], chance: 7 },
      { type: "dark", value: [2, 5], chance: 7 },
      { type: "divine", value: [2, 5], chance: 7 },
      { type: "fire", value: [2, 5], chance: 7 },
      { type: "lightning", value: [2, 5], chance: 7 },
      { type: "ice", value: [2, 5], chance: 7 },
    ],
    statsTemplate: [
      { type: "strV", value: [2, 4, 6], chance: 1.75 },
      { type: "strP", value: [5, 8, 12], chance: 3.25 },
      { type: "dexV", value: [2, 4, 6], chance: 2.25 },
      { type: "dexP", value: [5, 8, 11], chance: 2 },
      { type: "vitV", value: [2, 4, 5], chance: 2.25 },
      { type: "vitP", value: [5, 7, 11], chance: 2.45 },
      { type: "hpMaxV", value: [10, 15, 20], chance: 4.5 },
    ],
    requiresStats: {
      vit: 8,
      str: 8
    },
    coversHair: true,
    img: "resources/icons/iron_helmet.png",
    sprite: "ironHelmet",
    price: 100,
    weight: 3,
    type: "armor",
    grade: "uncommon",
    slot: "helmet"
  },
  ironGauntlets: {
    id: "ironGauntlets",
    name: "Iron Gauntlets",
    resistances: { slash: 5, crush: 4, pierce: 4, magic: 4,  ice: 4, lightning: 1, dark: 3, divine: 3, fire: 4 },
    resistancesTemplate: [
      { type: "slash", value: [2, 5], chance: 7 },
      { type: "crush", value: [2, 5], chance: 7 },
      { type: "pierce", value: [2, 5], chance: 7 },
      { type: "magic", value: [2, 5], chance: 7 },
      { type: "dark", value: [2, 5], chance: 7 },
      { type: "divine", value: [2, 5], chance: 7 },
      { type: "fire", value: [2, 5], chance: 7 },
      { type: "lightning", value: [2, 5], chance: 7 },
      { type: "ice", value: [2, 5], chance: 7 },
    ],
    statsTemplate: [
      { type: "strV", value: [2, 4, 6], chance: 1.75 },
      { type: "strP", value: [5, 8, 12], chance: 3.25 },
      { type: "dexV", value: [2, 4, 6], chance: 2.25 },
      { type: "dexP", value: [5, 8, 11], chance: 2 },
      { type: "vitV", value: [2, 4, 5], chance: 2.25 },
      { type: "vitP", value: [5, 7, 11], chance: 2.45 },
      { type: "hpMaxV", value: [10, 15, 20], chance: 4.5 },
    ],
    requiresStats: {
      vit: 8,
      str: 8
    },
    img: "resources/icons/iron_gauntlets.png",
    sprite: "ironGauntlets",
    price: 95,
    weight: 3.5,
    type: "armor",
    grade: "uncommon",
    slot: "gloves"
  },
  ironBoots: {
    id: "ironBoots",
    name: "Iron Boots",
    resistances: { slash: 5, crush: 4, pierce: 4, magic: 4,  ice: 4, lightning: 1, dark: 3, divine: 3, fire: 4 },
    resistancesTemplate: [
      { type: "slash", value: [2, 5], chance: 7 },
      { type: "crush", value: [2, 5], chance: 7 },
      { type: "pierce", value: [2, 5], chance: 7 },
      { type: "magic", value: [2, 5], chance: 7 },
      { type: "dark", value: [2, 5], chance: 7 },
      { type: "divine", value: [2, 5], chance: 7 },
      { type: "fire", value: [2, 5], chance: 7 },
      { type: "lightning", value: [2, 5], chance: 7 },
      { type: "ice", value: [2, 5], chance: 7 },
    ],
    statsTemplate: [
      { type: "strV", value: [2, 4, 6], chance: 1.75 },
      { type: "strP", value: [5, 8, 12], chance: 3.25 },
      { type: "dexV", value: [2, 4, 6], chance: 2.25 },
      { type: "dexP", value: [5, 8, 11], chance: 2 },
      { type: "vitV", value: [2, 4, 5], chance: 2.25 },
      { type: "vitP", value: [5, 7, 11], chance: 2.45 },
      { type: "hpMaxV", value: [10, 15, 20], chance: 4.5 },
    ],
    requiresStats: {
      vit: 8,
      str: 8
    },
    img: "resources/icons/iron_boots.png",
    sprite: "ironBoots",
    price: 95,
    weight: 4.5,
    type: "armor",
    grade: "uncommon",
    slot: "boots"
  },
  crownOfWisdom: {
    id: "crownOfWisdom",
    name: "Crown of Wisdom",
    resistances: { magic: 20, dark: 10, divine: 10 },
    resistancesTemplate: [
      { type: "slash", value: [1, 2], chance: 7 },
      { type: "crush", value: [1, 2], chance: 7 },
      { type: "pierce", value: [1, 2], chance: 7 },
      { type: "magic", value: [1, 2], chance: 7 },
      { type: "dark", value: [1, 2], chance: 7 },
      { type: "divine", value: [1, 2], chance: 7 },
      { type: "fire", value: [1, 2], chance: 7 },
      { type: "lightning", value: [1, 2], chance: 7 },
      { type: "ice", value: [1, 2], chance: 7 },
    ],
    statsTemplate: [
      { type: "strV", value: [1, 2, 3], chance: 1.75 },
      { type: "strP", value: [3, 5, 8], chance: 3.25 },
      { type: "dexV", value: [1, 2, 3], chance: 2.25 },
      { type: "dexP", value: [3, 5, 7], chance: 2 },
      { type: "vitV", value: [1, 2, 4], chance: 2.25 },
      { type: "vitP", value: [3, 6, 9], chance: 2.45 },
      { type: "hpMaxV", value: [4, 8, 12], chance: 4.5 },
    ],
    requiresStats: {
      int: 15
    },
    stats: {
      magicDamageP: 10
    },
    img: "resources/icons/crown_of_wisdom.png",
    sprite: "crownOfWisdom",
    price: 500,
    weight: 0.5,
    type: "armor",
    grade: "rare",
    slot: "helmet"
  },
  lichRobes: {
    id: "lichRobes",
    name: "Lich Robes",
    resistances: { slash: 5, crush: 4, pierce: 4, magic: 15,  ice: 8, lightning: 5, dark: 10, divine: 10, fire: 5 },
    resistancesTemplate: [
      { type: "slash", value: [3, 8], chance: 7 },
      { type: "crush", value: [3, 8], chance: 7 },
      { type: "pierce", value: [3, 8], chance: 7 },
      { type: "magic", value: [3, 8], chance: 7 },
      { type: "dark", value: [3, 8], chance: 7 },
      { type: "divine", value: [3, 8], chance: 7 },
      { type: "fire", value: [3, 8], chance: 7 },
      { type: "lightning", value: [3, 8], chance: 7 },
      { type: "ice", value: [3, 8], chance: 7 },
    ],
    statsTemplate: [
      { type: "dexV", value: [2, 4, 6, 8], chance: 2.25 },
      { type: "dexP", value: [5, 8, 11, 14], chance: 2 },
      { type: "vitV", value: [2, 4, 5, 7], chance: 2.25 },
      { type: "vitP", value: [5, 7, 11, 15], chance: 2.45 },
      { type: "intV", value: [2, 4, 5, 7], chance: 2.25 },
      { type: "intP", value: [5, 7, 11, 15], chance: 2.45 },
      { type: "hpMaxV", value: [10, 15, 20, 25], chance: 4.5 },
    ],
    requiresStats: {
      int: 12
    },
    img: "resources/icons/lich_robes.png",
    sprite: "lichRobes",
    price: 305,
    weight: 4.5,
    type: "armor",
    grade: "uncommon",
    slot: "chest"
  },
  knightArmor: {
    id: "knightArmor",
    name: "Knight Armour",
    resistances: { slash: 25, crush: 15, pierce: 21, magic: 14,  ice: 2, lightning: 3, dark: 17, divine: 13, fire: 1 },
    resistancesTemplate: [
      { type: "slash", value: [3, 8], chance: 7 },
      { type: "crush", value: [3, 8], chance: 7 },
      { type: "pierce", value: [3, 8], chance: 7 },
      { type: "magic", value: [3, 8], chance: 7 },
      { type: "dark", value: [3, 8], chance: 18 },
      { type: "divine", value: [3, 8], chance: 7 },
      { type: "fire", value: [3, 8], chance: 7 },
      { type: "lightning", value: [3, 8], chance: 7 },
      { type: "ice", value: [3, 8], chance: 7 },
    ],
    statsTemplate: [
      { type: "strV", value: [2, 4, 6, 8], chance: 1.75 },
      { type: "strP", value: [5, 8, 12, 15], chance: 3.25 },
      { type: "dexV", value: [2, 4, 6, 8], chance: 2.25 },
      { type: "dexP", value: [5, 8, 11, 14], chance: 2 },
      { type: "vitV", value: [2, 4, 5, 7], chance: 2.25 },
      { type: "vitP", value: [5, 7, 11, 15], chance: 2.45 },
      { type: "hpMaxV", value: [10, 15, 20, 25], chance: 4.5 },
    ],
    requiresStats: {
      vit: 15,
      str: 12
    },
    img: "resources/icons/knight_armor.png",
    sprite: "knightArmor",
    price: 800,
    weight: 14.5,
    type: "armor",
    grade: "rare",
    slot: "chest"
  },
  knightGreaves: {
    id: "knightGreaves",
    name: "Knight Greaves",
    resistances: { slash: 17, crush: 11, pierce: 12, magic: 10,  ice: 2, lightning: 3, dark: 11, divine: 7, fire: 1 },
    resistancesTemplate: [
      { type: "slash", value: [3, 7], chance: 7 },
      { type: "crush", value: [3, 7], chance: 7 },
      { type: "pierce", value: [3, 7], chance: 7 },
      { type: "magic", value: [3, 7], chance: 13 },
      { type: "dark", value: [3, 7], chance: 18 },
      { type: "divine", value: [3, 7], chance: 7 },
      { type: "fire", value: [3, 7], chance: 7 },
      { type: "lightning", value: [3, 7], chance: 7 },
      { type: "ice", value: [3, 7], chance: 7 },
    ],
    statsTemplate: [
      { type: "strV", value: [2, 4, 6, 8], chance: 1.75 },
      { type: "strP", value: [5, 8, 12, 15], chance: 3.25 },
      { type: "dexV", value: [2, 4, 6, 8], chance: 2.25 },
      { type: "dexP", value: [5, 8, 11, 14], chance: 2 },
      { type: "vitV", value: [2, 4, 5, 7], chance: 2.25 },
      { type: "vitP", value: [5, 7, 11, 15], chance: 2.45 },
      { type: "hpMaxV", value: [10, 15, 20, 25], chance: 4.5 },
    ],
    requiresStats: {
      vit: 15,
      str: 12
    },
    img: "resources/icons/knight_greaves.png",
    sprite: "knightGreaves",
    price: 525,
    weight: 7.5,
    type: "armor",
    grade: "rare",
    slot: "legs"
  },
  greathelm: {
    id: "greathelm",
    name: "Greathelm",
    resistances: { slash: 9, crush: 6, pierce: 8, magic: 8,  ice: 2, lightning: 1, dark: 9, divine: 5, fire: 1 },
    resistancesTemplate: [
      { type: "slash", value: [2, 5], chance: 7 },
      { type: "crush", value: [2, 5], chance: 7 },
      { type: "pierce", value: [2, 5], chance: 7 },
      { type: "magic", value: [2, 5], chance: 13 },
      { type: "dark", value: [2, 5], chance: 17 },
      { type: "divine", value: [2, 5], chance: 7 },
      { type: "fire", value: [2, 5], chance: 7 },
      { type: "lightning", value: [2, 5], chance: 7 },
      { type: "ice", value: [2, 5], chance: 7 },
    ],
    statsTemplate: [
      { type: "strV", value: [2, 4, 6], chance: 1.75 },
      { type: "strP", value: [5, 8, 12], chance: 3.25 },
      { type: "dexV", value: [2, 4, 6], chance: 2.25 },
      { type: "dexP", value: [5, 8, 11], chance: 2 },
      { type: "vitV", value: [2, 4, 5], chance: 2.25 },
      { type: "vitP", value: [5, 7, 11], chance: 2.45 },
      { type: "hpMaxV", value: [10, 15, 20], chance: 4.5 },
    ],
    requiresStats: {
      vit: 10,
      str: 8
    },
    coversHair: true,
    img: "resources/icons/great_helm.png",
    sprite: "greatHelm",
    price: 300,
    weight: 4.5,
    type: "armor",
    grade: "rare",
    slot: "helmet"
  },
  knightGauntlets: {
    id: "knightGauntlets",
    name: "Knight Gauntlets",
    resistances: { slash: 8, crush: 5, pierce: 7, magic: 7,  ice: 1, lightning: 1, dark: 8, divine: 4, fire: 1 },
    resistancesTemplate: [
      { type: "slash", value: [2, 5], chance: 7 },
      { type: "crush", value: [2, 5], chance: 7 },
      { type: "pierce", value: [2, 5], chance: 7 },
      { type: "magic", value: [2, 5], chance: 12 },
      { type: "dark", value: [2, 5], chance: 15 },
      { type: "divine", value: [2, 5], chance: 7 },
      { type: "fire", value: [2, 5], chance: 7 },
      { type: "lightning", value: [2, 5], chance: 7 },
      { type: "ice", value: [2, 5], chance: 7 },
    ],
    statsTemplate: [
      { type: "strV", value: [2, 4, 6], chance: 1.75 },
      { type: "strP", value: [5, 8, 12], chance: 3.25 },
      { type: "dexV", value: [2, 4, 6], chance: 2.25 },
      { type: "dexP", value: [5, 8, 11], chance: 2 },
      { type: "vitV", value: [2, 4, 5], chance: 2.25 },
      { type: "vitP", value: [5, 7, 11], chance: 2.45 },
      { type: "hpMaxV", value: [10, 15, 20], chance: 4.5 },
    ],
    requiresStats: {
      vit: 10,
      str: 8
    },
    img: "resources/icons/knight_gloves.png",
    sprite: "knightGauntlets",
    price: 250,
    weight: 3.75,
    type: "armor",
    grade: "rare",
    slot: "gloves"
  },
  knightSabatons: {
    id: "knightSabatons",
    name: "Knight Sabatons",
    resistances: { slash: 8, crush: 5, pierce: 7, magic: 7,  ice: 1, lightning: 1, dark: 6, divine: 4, fire: 0 },
    resistancesTemplate: [
      { type: "slash", value: [2, 5], chance: 7 },
      { type: "crush", value: [2, 5], chance: 7 },
      { type: "pierce", value: [2, 5], chance: 7 },
      { type: "magic", value: [2, 5], chance: 15 },
      { type: "dark", value: [2, 5], chance: 21 },
      { type: "divine", value: [2, 5], chance: 7 },
      { type: "fire", value: [2, 5], chance: 7 },
      { type: "lightning", value: [2, 5], chance: 7 },
      { type: "ice", value: [2, 5], chance: 7 },
    ],
    statsTemplate: [
      { type: "strV", value: [2, 4, 6], chance: 1.75 },
      { type: "strP", value: [5, 8, 12], chance: 3.25 },
      { type: "dexV", value: [2, 4, 6], chance: 2.25 },
      { type: "dexP", value: [5, 8, 11], chance: 2 },
      { type: "vitV", value: [2, 4, 5], chance: 2.25 },
      { type: "vitP", value: [5, 7, 11], chance: 2.45 },
      { type: "hpMaxV", value: [10, 15, 20], chance: 4.5 },
    ],
    requiresStats: {
      vit: 10,
      str: 8
    },
    img: "resources/icons/knight_sabatons.png",
    sprite: "knightSabatons",
    price: 250,
    weight: 5,
    type: "armor",
    grade: "rare",
    slot: "boots"
  },
  /* ARTIFACTS */
  talismanOfProtection: {
    id: "talismanOfProtection",
    name: "Talisman of Protection",
    stats: {
      hpMaxV: 10,
      resistAllV: 3
    },
    statsTemplate: [
      { type: "strV", value: [1, 2, 3], chance: 3.75 },
      { type: "strP", value: [3, 6, 9], chance: 3.75 },
      { type: "dexV", value: [1, 2, 3], chance: 3.75 },
      { type: "dexP", value: [3, 6, 9], chance: 3.75 },
      { type: "vitV", value: [1, 2, 3], chance: 3.75 },
      { type: "vitP", value: [3, 6, 9], chance: 3.75 },
      { type: "intV", value: [1, 2, 3], chance: 3.75 },
      { type: "intP", value: [3, 6, 9], chance: 3.75 },
      { type: "cunV", value: [1, 2, 3], chance: 3.75 },
      { type: "cunP", value: [3, 6, 9], chance: 3.75 },
      { type: "critChanceV", value: [1, 2, 3], chance: 6 },
      { type: "critDamageV", value: [3, 6, 9], chance: 6 },
      { type: "hpMaxV", value: [5, 7, 10], chance: 20 },
      { type: "hpMaxP", value: [3, 6, 9], chance: 20 },
      { type: "resistAllV", value: [2, 4, 5], chance: 8 },
    ],
    img: "resources/icons/knight_sabatons.png",
    price: 60,
    weight: 0.25,
    artifactSet: "defender",
    type: "artifact",
    grade: "uncommon",
    slot: "artifact1"
  },
  emblemOfProtection: {
    id: "emblemOfProtection",
    name: "Emblem of Protection",
    stats: {
      hpMaxV: 5,
      evasionV: 3
    },
    statsTemplate: [
      { type: "strV", value: [1, 2, 3], chance: 3.75 },
      { type: "strP", value: [3, 6, 9], chance: 3.75 },
      { type: "dexV", value: [1, 2, 3], chance: 3.75 },
      { type: "dexP", value: [3, 6, 9], chance: 3.75 },
      { type: "vitV", value: [1, 2, 3], chance: 3.75 },
      { type: "vitP", value: [3, 6, 9], chance: 3.75 },
      { type: "intV", value: [1, 2, 3], chance: 3.75 },
      { type: "intP", value: [3, 6, 9], chance: 3.75 },
      { type: "cunV", value: [1, 2, 3], chance: 3.75 },
      { type: "cunP", value: [3, 6, 9], chance: 3.75 },
      { type: "critChanceV", value: [1, 2, 3], chance: 6 },
      { type: "critDamageV", value: [3, 6, 9], chance: 6 },
      { type: "hpMaxV", value: [3, 5, 7], chance: 20 },
      { type: "hpMaxP", value: [2, 5, 7], chance: 20 },
      { type: "evasionV", value: [2, 3, 4], chance: 8 },
    ],
    img: "resources/icons/knight_sabatons.png",
    price: 60,
    weight: 0.25,
    artifactSet: "defender",
    type: "artifact",
    grade: "uncommon",
    slot: "artifact2"
  },
  ringOfProtection: {
    id: "ringOfProtection",
    name: "Ring of Protection",
    stats: {
      resistAllV: 5
    },
    statsTemplate: [
      { type: "strV", value: [1, 2, 3], chance: 3.75 },
      { type: "strP", value: [3, 6, 9], chance: 3.75 },
      { type: "dexV", value: [1, 2, 3], chance: 3.75 },
      { type: "dexP", value: [3, 6, 9], chance: 3.75 },
      { type: "vitV", value: [1, 2, 3], chance: 3.75 },
      { type: "vitP", value: [3, 6, 9], chance: 3.75 },
      { type: "intV", value: [1, 2, 3], chance: 3.75 },
      { type: "intP", value: [3, 6, 9], chance: 3.75 },
      { type: "cunV", value: [1, 2, 3], chance: 3.75 },
      { type: "cunP", value: [3, 6, 9], chance: 3.75 },
      { type: "critChanceV", value: [1, 2, 3], chance: 6 },
      { type: "critDamageV", value: [3, 6, 9], chance: 6 },
      { type: "hpMaxV", value: [3, 5, 7], chance: 20 },
      { type: "hpMaxP", value: [2, 5, 7], chance: 20 },
      { type: "evasionV", value: [2, 3, 4], chance: 8 },
    ],
    img: "resources/icons/knight_sabatons.png",
    price: 60,
    weight: 0.25,
    artifactSet: "defender",
    type: "artifact",
    grade: "uncommon",
    slot: "artifact3"
  },
  healingScrollI: {
    id: "healingScrollI",
    name: "Scroll of Healing I",
    img: "resources/icons/healing_scroll.png",
    sprite: "",
    price: 75,
    weight: 0.1,
    type: "consumable",
    grade: "common",
    slot: "",
    equippedSlot: -1,
    healValue: 20,
    usesTotal: 3,
    usesRemaining: 3
  },
  manaScrollI: {
    id: "manaScrollI",
    name: "Scroll of Mana Recovery I",
    img: "resources/icons/mana_scroll.png",
    sprite: "",
    price: 75,
    weight: 0.1,
    type: "consumable",
    grade: "common",
    slot: "",
    equippedSlot: -1,
    manaValue: 15,
    usesTotal: 3,
    usesRemaining: 3
  },
} as any;