// /* NOTE - THIS WILL *NEVER* FULLY TRANSLATE THE GAME, BUT IT WILL ATLEAST PROVIDE YOU WITH FLAVOUR TEXTS IN YOUR PREFERRED LANGUAGE */ //

const finnish = {
  // identifier
  language_id: "finnish",
  finnish: "Suomi",
  english: "English",

  // Races
  human_name: "Ihminen",
  orc_name: "Puoli-Örkki",
  elf_name: "Puoli-Haltia",
  ashen_name: "Kalpea",

  // Character Window
  core_stats: "Yleiset statsit",
  core_resistances: "puolustukset",
  status_resistances: "vastustuskyky",
  poison_status: "Myrkky",
  burning_status: "Palaminen",
  curse_status: "Kirous",
  stun_status: "Tainnutus",
  bleed_status: "Verenvuoto",

  str_tt: `<i>${icons["str"]}<i>Voima parantaa <i>${icons["melee"]}<i>voima aseiden vahinkoa 2%,\n ja parantaa maksimi taakkaa 0.5`,
  dex_tt: `<i>${icons["dex"]}<i>Taito parantaa <i>${icons["ranged"]}<i>taito aseiden vahinkoa 2%`,
  vit_tt: `<i>${icons["vit"]}<i>Sisu parantaa <i>${icons["health"]}<i>terveyttä 5,\n<i>${icons["regenHp_icon"]}<i>terveyden palautimista 1%\n ja maksimi taakkaa 1`,
  int_tt: `<i>${icons["int"]}<i>Älykkyys parantaa <i>${icons["mana"]}<i>taikaa 2,\n<i>${icons["regenMp_icon"]}<i>taian palautimista 1%\n ja <i>${icons["damage"]}<i>maagista vahinkoa 2%`,
  cun_tt: `<i>${icons["cun"]}<i>Oveluus parantaa <i>${icons["critDamage"]}<i>krit vahinkoa 1.5%,\n ja <i>${icons["critDamage"]}<i>krit mahdollisuutta 0.4%`,
  critDamage_tt: `<i>${icons["critDamage"]}<i>Krit vahinko on kertoja joka parantaa kriittisiä iskuja.`,
  critChance_tt: `<i>${icons["critDamage"]}<i>Krit mahdollisuus kertoo millä todennäköisyydellä iskusi on kriittinen.`,
  hitChance_tt: `<i>${icons["hitChance"]}<i>Iskujen tarkkuus parantaa mahdollisuuttasi osua viholliseesi. \nVerrataan vastustajan <i>${icons["evasion"]}<i>väistelyyn.`,
  evasion_tt: `<i>${icons["evasion"]}<i>Väistely parantaa mahdollisuuttasi välttää vahinkoa. \nVerrataan vastustajan <i>${icons["hitChance"]}<i>iskujen tarkkuuteen.`,

  resistances_tt: "Vahinko tyypin puolustus vähentää saman tyyppistä tulevaa vahinkoa mainitulla prosentilla.",
  stat_resist_tt: `Efektin vastustus laskee sen tekemää vahinkoa mainitulla prosentilla. \n\nSe myös antaa mahdollisuuden kokonaan vastustaa efekti. \n\nKun efekti on täysin vastustettu, se ei tee mitään.`,

  // Status Resists
  poisonDefense: "Myrkytyksen vastustus",
  burningDefense: "Palamisen vastustus",
  curseDefense: "Kirouksen vastustus",
  stunDefense: "Tainnuttamisen vastustus",
  bleedDefense: "Verenvuodon vastustus",

  // Technical stuff
  changeWordOrder: true,
  mana: "Taika",
  health: "Terveys",
  str: "Voima",
  dex: "Taito",
  vit: "Sisu",
  int: "Älykkyys",
  cun: "Oveluus",
  crush: "Murskaava",
  slash: "Viiltävä",
  pierce: "Lävistävä",
  magic: "Maaginen",
  fire: "Tuli",
  ice: "Jää",
  dark: "Pimeä",
  divine: "Jumalallinen",
  lightning: "Sähkö",
  crush_def: "Murskaus",
  slash_def: "Viilto",
  pierce_def: "Lävistävyys",
  magic_def: "Maaginen",
  fire_def: "Tuli",
  ice_def: "Jää",
  dark_def: "Pimeä",
  divine_def: "Jumalallinen",
  lightning_def: "Sähkö",
  hpMax: "Terveyttä",
  mpMax: "Taikaa",
  hitChance: "Iskujen tarkkuus",
  evasion: "Väistely",
  sight: "Näköä",
  increases: "Nostaa",
  decreases: "Alentaa",
  damage: "Vahinkoa",
  by: "",
  strV: "Voima",
  strP: "Voima%",
  vitV: "Sisu",
  vitP: "Sisu%",
  dexV: "Taito",
  dexP: "Taito%",
  intV: "Älykkyys",
  intP: "Älykkyys%",
  hpV: "Terveys",
  hpP: "Terveys%",
  mpV: "Taika",
  mpP: "Taika%",
  resistAllV: "Puolustus",
  resistAllP: "Puolusus%",
  hitChanceV: "Iskujen tarkkuus",
  hitChanceP: "Iskujen tarkkuus%",
  evasionV: "Väistely",
  evasionP: "Väistely%",
  critChanceV: "Krit Mahdollisuus",
  critChanceP: "Krit Mahdollisuus",
  critDamageV: "Krit Vahinko",
  critDamageP: "Krit Vahinko",
  status_effect: "Tila efekti",
  last: "Efektin kesto",
  lasts_for: "Efekti kestää",
  resist: "Puolustus",
  silence_text: "Taikasi on estetty!",
  silence: "Estää taian!",
  concentration_text: "Et kykene keskittymään!",
  concentration_req: "Vaatii keskittymisen",
  concentration: "Estää keskittymisen!",
  heal_power: "Parannus voima",
  type: "Tyyppi",
  ranged: "Kauko käyttö",
  requires_melee_weapon: "Vaatii lähitaistelu aseen",
  requires_ranged_weapon: "Vaatii kaukotaistelu aseen",
  recharge_only_in_combat: "Latautuu vain taistelussa",
  targets_self: "Kohde on oma hahmo",
  mana_cost: "Taian käyttö",
  use_range: "Käyttö matka",
  damage_multiplier: "Vahingon kerroin",
  resistance_penetration: "Puolustuksen läpäisy",
  aoe_size: "Vahinkoalueen koko",
  yes: "kyllä",
  no: "ei",
  tiles: "tiiliä",
  attack: "Hyökkäys",
  heal: "Parannus",
  buff: "Tehoste/Buffi",
  movement: "Liikkuminen",
  charge: "Ryntäys",
  summon: "Kutsuntaloitsu",
  turn: "Kierros",
  turns: "kierrosta",
  cooldown: "Latausaika",
  base_heal: "Parannus voima",
  map_to_hotbar: "Lisää kyky/työkalu",
  remove_from_hotbar: "Poista kyky/työkalu",
  removed_in: "Kestää",
  deals: "Aiheuttaa",
  perk_points: "Perkki pisteet",
  stat_points: "Stat pisteet",
  adventurerPerks: "Seikkailija",
  lvl_up: "Tasosi nousi! Se on nyt [LVL]!",
  regenHp: "Terveyden palautuminen",
  regenMp: "Taian palautuminen",

  // Item definitions
  slash_damageSub: "Viiltävä",
  slash_damageMain: "Haavoittavan",
  crush_damageSub: "Tylppä",
  crush_damageMain: "Murskaavan",
  pierce_damageSub: "Pistävä",
  pierce_damageMain: "Lävistävän",
  magic_damageSub: "Lumottu",
  magic_damageMain: "Maagisen",
  dark_damageSub: "Pimeä",
  dark_damageMain: "Kamalan",
  divine_damageSub: "Pyhä",
  divine_damageMain: " Jumalallisen",
  fire_damageSub: "Tulinen",
  fire_damageMain: "Liekehtivän",
  lightning_damageSub: "Ukkostava",
  lightning_damageMain: "Salamoivan",
  ice_damageSub: "Jäinen",
  ice_damageMain: "Hyytävän",
  // armor defs
  slash_resistanceSub: "Suojelevainen",
  slash_resistanceMain: "Viilloilta Suojaava",
  crush_resistanceSub: "Pehmeä",
  crush_resistanceMain: "Murskaukselta Suojeleva",
  pierce_resistanceSub: "Paksu",
  pierce_resistanceMain: "Pistoilta Suojaava",
  magic_resistanceSub: "Lumottu",
  magic_resistanceMain: "Magialta Suojaava",
  dark_resistanceSub: "Pyhä",
  dark_resistanceMain: "Pimeyden Karkottava",
  divine_resistanceSub: "Kirottu",
  divine_resistanceMain: "Virsiä Karttava",
  fire_resistanceSub: "Viilentävä",
  fire_resistanceMain: "Tulenkestävä",
  lightning_resistanceSub: "Sähkönjohtava",
  lightning_resistanceMain: "Salamankestävä",
  ice_resistanceSub: "Sulattava",
  ice_resistanceMain: "Jäänmurtava",

  // Item names
  healingScrollI_name: "Parannuksen Loitsukirja I",
  manaScrollI_name: "Taianpalautuksen Loitsukirja I",
  dagger_name: "Tikari",
  stick_name: "Keppi",
  chippedBlade_name: "Kulunut Terä",
  longsword_name: "Pitkämiekkä",
  chippedAxe_name: "Kulunut Kirves",
  orcishAxe_name: "Örkkimäinen Kirves",
  huntingBow_name: "Metsästys Jousi",
  apprenticeWand_name: "Oppilaan Sauva",
  galadorSpear_name: "Galadorin Keihäs",
  pikeMore_name: "Murhahauki",
  raggedShirt_name: "Ryysyinen Paita",
  raggedBoots_name: "Ryysyiset Jalkimet",
  raggedPants_name: "Ryysyiset Housut",
  raggedGloves_name: "Ryysyiset Hanskat",
  raggedHood_name: "Ryysyinen Huppu",
  leatherChest_name: "Nahkaliivi",
  leatherBoots_name: "Nahkakengät",
  leatherLeggings_name: "Nahkajalkasuojat",
  leatherBracers_name: "Nahkakäsisuojat",
  leatherHelmet_name: "Nahkakypärä",
  ironArmor_name: "Rautahaarniska",
  ironBoots_name: "Rautajalkimet",
  ironLegplates_name: "Rautajalkasuojat",
  ironGauntlets_name: "Rautakäsineet",
  ironHelmet_name: "Rautakypärä",
  knightArmor_name: "Ritarin Haarniska",
  knightSabatons_name: "Ritarin Jalkimet",
  knightGreaves_name: "Ritarin Jalkasuojat",
  knightGauntlets_name: "Ritarin Kintaat",
  greathelm_name: "Ritarin Kypärä",
  crownOfWisdom_name: "Viisauden Kruunu",
  lichRobes_name: "Kuolema Maagin Kaapu",
  woodenShield_name: "Puukilpi",
  ironShield_name: "Rautakilpi",
  silverShield_name: "Hopeakilpi",
  talismanOfProtection_name: "Puolustava Talismaani",
  emblemOfProtection_name: "Puolustava Tunnus",
  ringOfProtection_name: "Puolustava Sormus",
  scholarsTalisman_name: "Tieteilijän Onnekas Talismaani",
  scholarsEmblem_name: "Tieteilijän Tunnus",
  scholarsRing_name: "Tieteilijän Lumottu Sormus",
  warriorsTalisman_name: "Ylistetyn Soturin Talismaani",
  warriorsEmblem_name: "Soturin Arvostettu Tunnus",
  warriorsRing_name: "Soturin Sormus",
  loneShadesTalisman_name: "Yön Haamun Tähti Talismaani",
  loneShadesEmblem_name: "Yön Haamun Pimeä Tunnus",
  loneShadesRing_name: "Yön Haamun Kolkko Sormus",

  // Artifacts
  part_of_set: "Osa",
  artifact_def: "Artefakti",
  artifact_set: "Artefakti sarjaa",
  artifact_two_piece: "2-palan sarja efekti",
  artifact_three_piece: "3-palan sarja efekti",
  defenderSet_name: "Puolustaja",
  guardianSet_name: "Vartija",
  scholarSet_name: "Tietelijä",
  warriorSet_name: "Soturi",
  loneShadeSet_name: "Yön Haamu",

  // Enemy names
  hiisi_name: "Hiisi",
  hiisiWarrior_name: "Hiisi Soturi",
  hiisiHunter_name: "Hiisi Metsästäjä",
  skeletonWarrior_name: "Luuranko Soturi",
  skeletonArcher_name: "Luuranko Jousimies",
  skeletonMage_name: "Luuranko Maagi",
  skeletonLich_name: "Luuranko Kuolema Maagi",
  soulWraith_name: "Sielujen Viikatemies",
  greySlime_name: "Harmaa Lima",
  flamingSlime_name: "Liekehtivä Lima",
  electricSlime_name: "Sähköinen Lima",
  norsemanBerserk_name: "Pohjoismies Berserkki",
  norsemanHunter_name: "Pohjoismies Metsästäjä",
  femaleOrcRaider_name: "Örkki Hyökkääjä",
  wildTroll_name: "Villi Peikko",
  wildStoneTroll_name: "Villi Kivipeikko",
  troll_name: "Peikko",
  stoneTroll_name: "Kivipeikko",
  enthralledKnight_name: "Hurmattu Ritari",
  spectralKnight_name: "Aave Ritari",

  // Summon names
  skeletonWarriorSummon_name: "Kutsuttu Luuranko Soturi",
  skeletonLichSummon_name: "Kutsuttu Luuranko Kuolema Maagi",
  stoneTrollSummon_name: "Kutsuttu Kivipeikko",
  dummyTarget_name: "Harhautus Nukke",

  // LOG TEXTS
  you: "",
  recovery_pl: "parantaen",
  health_points: "terveys pistettä",
  for: "aiheuttaen",
  death: "kuoli.",
  damage_from_effect_pl: "<c>white<c>[STATUS] aiheuttaa [ICON][DMG] vahinkoa kehollesi!",
  damage_from_effect: "<c>white<c>[STATUS] aiheuttaa hahmolle [TARGET] [ICON][DMG] vahinkoa.",
  player_death_log: "OLET KUOLLUT...",
  cure_pl: "Parannat itsesi!",
  cure: "[ACTOR] parantaa itsensä.",
  useConsumable: "Käytät taiallisen esineen!",
  moves_to: "liikkuu ruutuun",

  // WORLD TEXTS
  gained_xp: "Sait [XP] XP!",
  player_death: "SINUT SURMATTIIN!",

  // Damage types
  poison_damage: "Myrkytys",
  burning_damage: "Polttavaa",

  // Character Creation
  choose_name: "Nimi",
  choose_race: "Rotu",
  choose_class: "Class",

  // Misc
  attack_name: "tavallisten iskujen vahinkoa",
  cures_statuses: "Parantaa efektit",
  item_weight: "Paino",
  item_worth: "Arvo",
  item_grade: "Taso",
  item_stat_bonus: "Vaikuttava kyky",
  weapon_has_great_reach: "Normaalia suurempi ase",
  resistance: "Puolustus",
  status_effects: "Tila efektit",
  encumbrance: "Taakka",
  shrine_activated: "Pyhäkkö aktivoitu!",
  shrine_used: "Pyhäkön voimat ovat jo kulutettu...",
  add_ability: "Lisää kyvyn",
  requires: "Vaatii",
  critChance: "Krit mahdollisuus",
  critDamage: "Krit voima",
  resistAll: "Puolustusvoima",
  uses: "Käyttökerrat",
  item_name: "Tavaran Nimi",
  item_type: "Tyyppi",
  item_rarity: "Harvinaisuus",
  item_weight_title: "Paino",
  item_worth_title: "Arvo",
  weapon: "ase",
  armor: "panssari",
  consumable: "käytettävä",
  artifact: "artefakti",
  required_stats: "Vaaditut kyvyt",
  active_if: "Aktivoituu kun",
  hp_more_than: "Terveys yli",
  hp_less_than: "Terveys alle",
  mp_more_than: "Taika yli",
  mp_less_than: "Taika alle",
  passive: "Passiivinen kyky",
  too_much_weight: "Kannat liikaa painoa! Pudota jotain!",
  summons_unit: "Kutsuu hahmon",
  summon_level: "Kutsutun hahmon taso",
  summon_last: "Kutsuttu hahmo kestää",
  two_handed_weapon: "Kahden käsen ase",
  rooted: "Et voi liikkua!",
  closest_enemy: "Etäisyys lähimpään viholliseen: ",
  expGain: "Kokemuspisteiden saanti",

  // Passive abilities
  frenzy_name: "Kiihko",
  heightened_casting_name: "Vahva Alku",
  warrior_instinct_name: "Soturin Aisti",
  confident_shot_name: "Varma Laukaisu",
  blood_rage_1_name: "Taiston Hirmu I",
  blood_rage_2_name: "Taiston Hirmu II",
  reckless_1_name: "Hyökkääjä I",
  reckless_2_name: "Hyökkääjä II",
  sense_of_danger_1_name: "Kuudes Aisti I",
  sense_of_danger_2_name: "Kuudes Aisti II",
  frantic_mana_recovery_name: "Hätäinen Taian Palautus",

  // Enemy types
  against_type_syntax: " vastaan",
  singular_type_slime: "Lima",
  plural_type_slime: "Limoja",
  singular_type_skeleton: "Luuranko",
  plural_type_skeleton: "Luurankoja",
  singular_type_barbarian: "Barbaari",
  plural_type_barbarian: "Barbaareja",
  singular_type_troll: "Peikko",
  plural_type_troll: "Peikkoja",
  singular_type_hiisi: "Hiisi",
  plural_type_hiisi: "Hiisiä",

  // Enemy races
  against_race_syntax: " vastaan",
  singular_race_elemenal: "Elementtaali",
  plural_race_elemental: "Elementtaaleja",
  singular_race_undead: "Epäkuollut",
  plural_race_undead: "Epäkuolleita",
  singular_race_human: "Ihminen",
  plural_race_human: "Ihmisiä",
  singular_race_monster: "Hirviö",
  plural_race_monster: "Hirviöitä",

  /* MENU */

  menu_resume: "Takaisin",
  menu_options: "Asetukset",
  menu_save_games: "Tallennetut Pelit",
  menu_main_screen: "Päämenu",
  menu_new_game: "Uusi Peli",
  menu_load_game: "Lataa Peli",

  setting_log_enemy_movement: "Kirjaa hahmojen sijainnit",
  setting_toggle_minimap: "Minikartta pois/päällä",
  setting_game_language: "Pelin kieli",
  setting_hotkey_inv: "Avaa inventaario",
  setting_hotkey_char: "Avaa hahmo ruutu",
  setting_hotkey_perk: "Avaa kehitys ruutu",
  setting_hotkey_move_up: "Liiku ylöspäin",
  setting_hotkey_move_down: "Liiku alaspäin",
  setting_hotkey_move_left: "Liiku vasemmalle",
  setting_hotkey_move_right: "Liiku oikealle",
  setting_hotkey_interact: "Poimi esine / käytä",

  open_menu: "Avaa valikko [Escape]",

  space_key: "VÄLILYÖNTI",

  save_over: "Tallenna peli",
  load_game: "Jatka peliä",
  delete_save: "Poista peli",
  create_save: "Luo uusi tallennus",
  create_file: "Tallenna tiedostoon",
  load_file: "Jatka peliä tiedostosta",

  // Grades
  common: "Yleinen",
  uncommon: "Epätavallinen",
  rare: "Harvinainen",
  mythical: "Myyttinen",
  legendary: "Legendaarinen",

  // Statuses
  effect_poison_name: "Myrkky",
  effect_poison_desc: "Myrkky kiertää veressäsi, \nsyöden voimasi ja terveytesi.",
  effect_venom_name: "Syvä myrkky",
  effect_venom_desc: "Myrkytys heikentää kehoasi.",
  effect_rage_name: "Raivo",
  effect_rage_desc: "Hävisit äskettäin kilpailun, \nmutta vain koska vastustajasi huijasi!",
  effect_berserk_name: "Berserkki",
  effect_berserk_desc: "HAKKAA PÄÄLLE POHJANPOIKA!!!",
  effect_dazed_name: "Pökerryksissä",
  effect_dazed_desc: "Pääsi on sekaisin iskun jäljiltä, \njonka takia et kykene tarkkoihin liikkeisiin.",
  effect_blighted_name: "Vitsattu",
  effect_blighted_desc: "Kehosi on heikentynyt vitsauksesta.",
  effect_ward_of_aurous_name: "Aurouksen Suoja",
  effect_ward_of_aurous_desc: "Kehosi on turvassa Aurouksen suojan alla.",
  effect_battle_fury_name: "Taistelun Riemu",
  effect_battle_fury_desc: "Riemuitse ja raivoa! Adrenaniili kiertää veressä ja veri lentää!",
  effect_burning_name: "Tulessa",
  effect_burning_desc: "OLET TULESSA!",
  effect_chilled_name: "Jäinen",
  effect_chilled_desc: "Kylmyys hidastaa ja heikentää..",
  effect_summoned_name: "Kutsuntaloitsu",
  effect_summoned_desc: "Kutsuttu soturi katoaa tämän loputtua",
  effect_disoriented_name: "Sekaisin",
  effect_disoriented_desc: "Maailma pyörii ja näet kaiken kahdesti.",
  effect_dueled_name: "Kaksintaistelu",
  effect_dueled_desc: "Et voi paeta haasteesta.",
  effect_sneaky_stabbing_name: "Polttava Puukotus",
  effect_sneaky_stabbing_desc: "Tämä tulee satuttamaan kohdettasi.",
  effect_smoke_bomb_effect_name: "Savu Pommi",
  effect_smoke_bomb_effect_desc: "Savu tukkii keuhkosi ja heikentää näköäsi!",

  // Abilities and stuff
  attack_action_desc_pl: "Teet [DMG] vahinkoa hahmoon [TARGET] hyökkäykselläsi.",
  attack_action_desc: "iskee hahmoa [TARGET], tehden [DMG] vahinkoa.",
  focus_strike_name: "Tarkka Isku",
  focus_strike_desc: "Silmäile kohteesi liikettä tarkasti,\niskien sopivimmalla hetkellä.",
  focus_strike_action_desc_pl: "Isket hahmoa [TARGET] tarkasti koko voimallasi, ja teet [DMG] vahinkoa.",
  focus_strike_action_desc: "käyttää koko voimaansa iskien hahmoa",
  true_shot_name: "Tappava Nuoli",
  true_shot_desc: "Laita kaikki voimasi tähän laukaukseen,\ntähdäten vastustajasi heikkouteen.",
  true_shot_action_desc_pl: "Täytät seuraavan nuolesi taialla, ja vapautat sen jousestasi hahmoa [TARGET] kohti, tehden [DMG] vahinkoa.",
  true_shot_action_desc: "[ACTOR] ampuu kohdetta [TARGET] taialla vahvistetulla nuolella, tehden [DMG] vahinkoa.",
  first_aid_name: "Ensiapu",
  first_aid_desc: "Hoida pienet haavasi tavalla tai toisella.",
  first_aid_action_desc_pl: "Käytät ensiapu taitojasi haavoihisi, ",
  first_aid_action_desc: "käyttää ensipau taitojaan haavoihinsa, ",
  icy_javelin_name: "Jäinen Keihäs",
  icy_javelin_desc: "Ammu jäästä tehty keihäs vihollistasi päin.",
  icy_javelin_action_desc_pl: "Ammut jäästä tehdyn keihään kohti hahmoa [TARGET], tehden [DMG] vahinkoa.",
  icy_javelin_action_desc: "ampuu jäästä tehdyn keihään kohti hahmoa [TARGET], aiheuttaen [DMG] vahinkoa.",
  icy_javelin_action_desc_aoe_pl: "[TARGET] ottaa [DMG] vahinkoa räjähdyksen voimasta!",
  barbarian_rage_name: "Barbaarin Raivo",
  barbarian_rage_desc: "Aivotyö on ajan tuhlaamista,\nhaluat näkyviä tuloksia HETI!",
  barbarian_rage_action_desc_pl: "Taistelussa ei muuta tarvitse kuin vihata näitä mulkkuja ympärilläsi! HAAA!!",
  barbarian_rage_action_desc: "käy kuumana ja alkaa raivota kovaa.",
  berserk_name: "Berserkki",
  berserk_desc: "PERRRRRRRRKELE!!!!",
  berserk_action_desc_pl: "NYT KYLLÄ PALO PINNA, ON AIKA PISTÄÄ NÄITÄ HULLUJA KUONOON!!!!!!",
  berserk_action_desc: "MENETTI JÄRKENSÄ, NYT KANNATTAA VAROA TAI SE ANTAA ISÄN KÄDESTÄ!!",
  shadow_step_name: "Varjoaskel",
  shadow_step_desc: "Astu varjojen välillä nopeasti.",
  shadow_step_action_desc_pl: "Käytät varjoja hyväksesi, ja liikut haluamaasi suuntaan väläyksessä.",
  shadow_step_action: "käyttää ympäröiviä varjoja liikkuakseen nopeasti.",
  retreat_name: "Vetäydy",
  retreat_desc: "Laita vähän etäisyyttä vaaraan.",
  retreat_action_desc_pl: "Juokset rajusti pois päin!",
  retreat_action: "yrittää paeta taistelusta!",
  charge_name: "Rynnäkkö",
  charge_desc: "Ryntää vihollistasi päin rajusti.",
  charge_action_desc_pl: "Ryntäät vastustajaa [TARGET] päin, tehden [DMG] vahinkoa!",
  charge_action_desc: "ryntää päin hahmoa [TARGET], aiheuttaen [DMG] vahinkoa.",
  reap_name: "Leikkuun into",
  reap_desc: "Ryntää kohtii mehevää sielua.",
  reap_action_desc_pl: "Leikkaat ilmaa päästäksesi hahmon [TARGET] siuluun käsiksi, tehden [DMG] vahinkoa!",
  reap_action_desc: "leikkaa ympäröivää ilmaa rynnäten kohti hahmoa [TARGET], leikaten hänen sieluansa [DMG] vahingon verran!",
  purification_name: "Puhdistus",
  purification_desc: "Puhdista kehosi myrkyistä ja epäpuhtauksista.",
  blight_name: "Vitsaus",
  blight_desc: "Kiroa kohteesi vitsauksella.",
  blight_action_desc_pl: "Vitsaat hahmon [TARGET], tehden [DMG] vahinkoa, ja heikentäen häntä!",
  blight_action_desc: "vitsaa hahmon [TARGET], aiheuttaen [DMG] vahinkoa, ja heikentäen häntä.",
  fireball_name: "Tulipallo",
  fireball_desc: "Heitä tulinen räjähde vihollistesi suuntaan \nja sytytä kaikki kohteesi liekkeihin.",
  fireball_action_desc_pl: "Lähetät tulisen ammuksen kohti vastustajiesi turmiota!",
  fireball_action_desc_aoe_pl: "[TARGET] paistuu räjähtävissä liekeissä, ottaen [DMG] vahinkoa!",
  piercing_mana_bolt_name: "Maaginen Pultti",
  piercing_mana_bolt_desc: "Ammu taiallinen panos vihollistasi kohti.",
  piercing_mana_bolt_action_desc_pl: "Taiot maagisen ammuksen lentämään kohti hahmoa [TARGET], tehden [DMG] vahinkoa!",
  piercing_mana_bolt_action_desc: "ampuu maagisen pultin hahmoa [TARGET] kohti, aiheuttaen [DMG] vahinkoa.",
  ward_of_aurous_name: "Aurouksen Kilpi",
  ward_of_aurous_desc: "Suojaa kehosi tuhoutumattomalla kilvellä!",
  ward_of_aurous_action_desc_pl: "Kutsut Aurouksen kilven suojaamaan kehoasi!",
  ward_of_aurous_action_desc: "suojaa itsensä maagisella kilvellä.",
  battle_fury_name: "Taistelijan Raivo",
  battle_fury_desc: "Hallittu viha vahvistaa.",
  battle_fury_action_desc_pl: "Annat taistelun viedä mielesi mennessään!",
  battle_fury_action_desc: "riehaantuu taistelun riemusta.",
  venomous_blow_name: "Häijy Isku",
  venomous_blow_desc: "Tässä tällissä onkin ikävä yllätys.",
  venomous_blow_action_desc_pl: "Myrkytät hahmon [TARGET] nopealla iskulla, joka myös aiheuttaa [DMG] vahinkoa!",
  venomous_blow_action_desc: "myrkyttää hahmon [TARGET] iskulla joka tekee [DMG] vahinkoa.",
  poisoned_arrow_name: "Myrkky Nuoli",
  poisoned_arrow_desc: "Taistelu muuttuu metsästykseksi.",
  poisoned_arrow_action_desc_pl: "Ammut myrkyllisen nuolen kohti hahmoa [TARGET], tehden [DMG] vahinkoa!",
  poisoned_arrow_action_desc: "ampuu myrkyllisen nuolen kohti hahmoa [TARGET], aiheuttaen [DMG] vahinkoa.",
  summon_skeleton_warrior_name: "Luo Luuranko Soturi",
  summon_skeleton_warrior_desc: "Kutsuu luuranko soturin taistelemaan puolellasi.",
  summon_skeleton_warrior_action_desc_pl: "Kutsut Luuranko Soturin kentälle!",
  barbarian_charge_name: "Barbaarin Rynnäkkö",
  barbarian_charge_desc: "Törmää kohteeseesi villillä raivolla.",
  barbarian_charge_action_desc_pl: "Karjut rajusti kuin villieläin ja ryntäät kohti hahmoa [TARGET], törmäys aiheuttaen [DMG] vahinkoa!",
  barbarian_charge_action_desc: "raivoaa eläimellisesti ja ryntää päin hahmoa [TARGET], tehden [DMG] vahinkoa.",
  chivalrious_blow_name: "Ritarillinen Hyökkäys",
  chivalrious_blow_desc: "Haasta vastustajasi kaksintaisteluun mahtavalla iskulla!",
  chivalrious_blow_action_desc_pl: "Isket hahmoa [TARGET] kunnialla, kutsuen hänet kamppailuun ja tehden [DMG] vahinkoa!",
  chivalrious_blow_action_desc: "lyö hahmoa [TARGET] kunnioittavasti, kutsuen hänet taisteluun ja tehden [DMG] vahinkoa.",
  challenge_name: "Haaste",
  challenge_desc: "Pienennä välisi kamppailu kumppaniisi suoralla juoksulla!",
  challenge_action_desc_pl: "Rynnäköit pelottomasti kohti hahmoa [TARGET], lämähtäen häneen voimalla, aiheuttaen [DMG] vahinkoa!",
  challenge_action_desc: "Ryntää kohti hahmoa [TARGET] karjuen 'ÄLÄ LÄHDE KARKUUN!', pian törmäten häneen, tehden [DMG] vahinkoa.",
  sneaky_stabbing_name: "Polttava Puukottaja",
  sneaky_stabbing_desc: "Iske vihollista kivuliaimpiin kohtiin.",
  sneaky_stabbing_action_desc_pl: "Vahvistat kykyäsi tunnistaa vihollisesi heikkoudet.",
  sneaky_stabbing_action_desc: "alkaa tarkkailemaan muiden heikoimpia paikkoja.",
  smoke_bomb_name: "Savu Pommi",
  smoke_bomb_desc: "Harhauta vastustajiasi savuisella räjähdyksellä.",
  smoke_bomb_action_desc_pl: "Heität pommin maahan, täyttäen pieneen alueen savulla!",
  smoke_bomb_action_desc_aoe_pl: "[TARGET] ottaa pommin täräyksen suoraan vastaan, ottaen [DMG] vahinkoa!",
  distraction_name: "Hätäinen Hämy",
  distraction_desc: "Heitä rähjäinen nukke maahan harhauttamaan pahantekijöitä.",
  distraction_action_desc_pl: "Asetat nuken maahan hämäämään vihollisiasi!",

  // CLASSES
  fighterClass_name: "Taistelija",
  barbarianClass_name: "Barbaari",
  sorcererClass_name: "Loitsija",
  rogueClass_name: "Rogue",

  // PERKS // 

  // SORCERER
  introduction_to_sorcery_name: "Maagin Alkukirja",
  introduction_to_sorcery_desc: "Kehitys tapahtuu askel kerrallaan.",
  intent_studies_name: "Taikojan Oppi",
  intent_studies_desc: "Opiskelu korostaa kokemusta.",
  might_of_magic_name: "Magian Mahti",
  might_of_magic_desc: "Sotaan valmistautuminen edistyy parhaiten magialla.",
  spells_of_battle_name: "Taistelun Taiat",
  spells_of_battle_desc: "Keskity helpoimpaan iskuusi ja et voi epäonnistua.",
  school_of_fire_name: "Tulen Opetukset",
  school_of_fire_desc: "Anna sielusi palaa intohimosta!",
  molded_by_flame_name: "Liekeissä Herännyt",
  molded_by_flame_desc: "Tulen voima herättää uusia tuntemuksia.",
  shield_of_ages_name: "Aikojen Kilpi",
  shield_of_ages_desc: "Vanhat kikat suojaavat uusia loitsijoita.",
  shield_of_aurous_name: "Aurouksen Suoja",
  shield_of_aurous_desc: "Aurous on havainnut kunniasi!",
  burning_passion_name: "Palava Intohimo",
  burning_passion_desc: "Mikään ei pysäytä liekehtivää sieluasi!",
  wisdoms_of_the_past_name: "Menneet Viisaudet",
  wisdoms_of_the_past_desc: "Vanhoilta ajoilta voi paljon neuvoja ammentaa.",
  flame_wizard_fury_name: "Tulivelhon Viha",
  flame_wizard_fury_desc: "Viha muuttuu tuleksi, ja tuli voimaksi.",
  makings_of_a_summoner_name: "Valtiaan Kutsu",
  makings_of_a_summoner_desc: "Taian mestarin ei tarvitse taistella yksin, kuninkaalla on aina palvelioita.",
  magical_bonds_name: "Maaginen Yhteys",
  magical_bonds_desc: "Kun kuningas komentaa, kaikki tottelevat.",
  elemental_mage_name: "Alkuaineiden Mestari",
  elemental_mage_desc: "Luonnon voimat ovat käytettävissäsi.",
  piercing_javelin_name: "Lävistävä Keihäs",
  piercing_javelin_desc: "Panssari ei pelasta tarpeeksi vahvalta iskulta.",

  // FIGHTER
  battle_sense_name: "Kamppailun Aistit",
  battle_sense_desc: "Ken taistelee elääkseen, tuntee pienimmänkin muutoksen ilmassa.",
  fighters_vitality_name: "Taistelijan Vireys",
  fighters_vitality_desc: "Lähitaistelussa vain vahvimmat soturit selviytyvät.",
  patient_blow_name: "Kärsivällinen Soturi",
  patient_blow_desc: "Tilanteen tarkkailu on taistelijan vahvin kortti.",
  strength_training_name: "Voimatreeni",
  strength_training_desc: "Voima edistää kamppailu-taitoa.",
  fighting_style_name: "Harjaantunut Iskijä",
  fighting_style_desc: "En pelkää miestä, joka on kerran harjoitellut 10 000 eri iskua, \nmutta pelkään miestä joka on harjoitellut yhtä iskua 10 000 kertaa.",
  furious_assault_name: "Raivokas Hyökkäys",
  furious_assault_desc: "Taistelua ei voiteta seisoskelemalla! Eteenpäin!",
  tactical_genius_name: "Taktiikkojen Kuningas",
  tactical_genius_desc: "Vahva on hän, kuka voi ajatella sodan raivossa.",
  resistant_in_melee_name: "Kestävä",
  resistant_in_melee_desc: "Taistelussa pysyminen on jo pitkä askel voittoon.",
  charging_bull_name: "Ryntäävä Sonni",
  charging_bull_desc: "Ottaen mallia karmeasta eläimestä, murskaa esteesi rajulla voimalla!",
  concentrated_warrior_name: "Taistelun Tasapaino",
  concentrated_warrior_desc: "Voiton voi taata vain yhdistämällä julman raivon ja lempeän kärsivällisyyden.",

  // ROGUE
  way_of_the_rogue_name: "Varjoinen Tie",
  way_of_the_rogue_desc: "Kamppailun ei tarvitse olla reilua, vain voitolla on merkitystä.",
  weakpoint_spotter_name: "Heikkouden Löytäjä",
  weakpoint_spotter_desc: "Kohdetta isketään vain parhaimalla hetkellä.",
  shadow_warrior_name: "Varjosoturi",
  shadow_warrior_desc: "Livahda varjoihin kun tilanne kääntyy.",
  fighting_dirty_name: "Likainen Tappelija",
  fighting_dirty_desc: "Luota taitoosi, mutta luota älyysi enemmän.",
  glass_cannon_name: "Hyökkääjä",
  glass_cannon_desc: "Puolustamalla ei taistelua voiteta!",
  ranged_expert_name: "Tarkka-ampuja",
  ranged_expert_desc: "Opettele tappamaan kaukaa.",
  poison_specialist_name: "Myrkyttäjä",
  poison_specialist_desc: "Soturi kuin soturi kärsii myrkytyksen seuraamuksista.",
  simple_strokes_name: "Tehokkaat Viillot",
  simple_strokes_desc: "Kun ei muuhun kykene, varmat iskut pelastavat.",
  dance_of_death_name: "Kuoleman Tanssi",
  dance_of_death_desc: "Kiemurtelu ei pelasta tältä tarkkuudelta!",
  poison_from_afar_name: "Tarkka-Myrkyttäjä",
  poison_from_afar_desc: "Kaukaa turvasta on helpoin murhata.",
  quicker_draw_name: "Nopeampi Veto",
  quicker_draw_desc: "Nopeammin, nopeammin!",
  smoke_screen_name: "Savuverho",
  smoke_screen_desc: "Peitä vastustajasi näkökenttä.",
  sneakier_stabbing_name: "Konnan Kepponen",
  sneakier_stabbing_desc: "Tästä tempusta eivät puukotukselle allergiset pidä!",
  smoke_and_mirrors_name: "Taika Temppu",
  smoke_and_mirrors_desc: "Savua ja peilejä...",
  tricky_distraction_name: "Harhautusliike",
  tricky_distraction_desc: "Laita vastustajasi läiskimään väärää kohdetta.",
  poison_taster_name: "Myrkyn Maistelija",
  poison_taster_desc: "Ammattilainen tuntee tuotteensa tarkasti.",

  // BARBARIAN
  thrill_of_battle_name: "Taiston Himo",
  thrill_of_battle_desc: "Kamppailun kaipaus on pureutunut vereesi.",
  weapon_mastery_name: "Harjoittelu",
  weapon_mastery_desc: "Kykyjä täytyy hiota tai ne katoavat.",
  raging_charge_name: "Raivokas Ryntäys",
  raging_charge_desc: "Itsevarma hyökkäys suoraan vihollista päin on rohkeuden merkki!",
  hardened_constitution_name: "Vahva Rakenne",
  hardened_constitution_desc: "Kehosi on ase, täten siitä kuuluu pitää huolta.",
  power_of_injuries_name: "Kivun Merkitys",
  power_of_injuries_desc: "Niin kauan kun kipu sattuu elämä jatkuu!",
  sharp_senses_name: "Kuudes Aisti",
  sharp_senses_desc: "Sankariteot luonnistuvat häneltä, ken uskaltaa vaarantaa henkensä.",
  perk_barbarian_rage_name: "Raivo",
  perk_barbarian_rage_desc: "Raivo ja viha laittavat veren virtaamaan.",
  impatient_name: "Kärsimätön",
  impatient_desc: "Jatketaan jo!!!!",
  ultimate_warrior_name: "Tuhon Soturi",
  ultimate_warrior_desc: "Voitan sotani koska uskallan taistella!",
  unyielding_rage_name: "Jatkuva Raivo",
  unyielding_rage_desc: "Anna vihan hallita ja kaikki kärsivät.",

  // ADVENTURER
  hearty_adventurer_1_name: "Kestävä Terveys I (Orion Pharma)",
  hearty_adventurer_1_desc: "Hyvinvointia rakentamassa.",
  hearty_adventurer_2_name: "Kestävä Terveys II (Orion Pharma)",
  hearty_adventurer_2_desc: "Hyvinvointia rakentamassa.",
  hearty_adventurer_3_name: "Kestävä Terveys III (Orion Pharma)",
  hearty_adventurer_3_desc: "Hyvinvointia rakentamassa.",
  hearty_adventurer_4_name: "Kestävä Terveys IV (Orion Pharma)",
  hearty_adventurer_4_desc: "Hyvinvointia rakentamassa.",
  hearty_adventurer_5_name: "Kestävä Terveys V (Orion Pharma)",
  hearty_adventurer_5_desc: "Hyvinvointia rakentamassa.",
  first_aid_expert_name: "Ensiavun Ekspertti",
  first_aid_expert_desc: "Hyvinvointia ylläpitämässä.",
  cleanser_name: "Puhdistaja",
  cleanser_desc: "Keho pidetään puhtaana.",
  advancing_backwards_name: "Rohkea Pakoreitti",
  advancing_backwards_desc: "Edistymistä eri suuntaan.",

  // NECROMANCER
  pursuit_of_undeath_name: "Kuolemattomuuden Tavoittelu",
  pursuit_of_undeath_desc: "Kryptisin keinoin.",

  // Settings tooltips
  log_char_movement: "<f>16px<f>Kirjaa teksti ruutuun vihollisten sijainnin joka kierroksella. \nVoi täyttää ruudun nopeasti.",
  toggle_minimap: "<f>16px<f>Minikartta auttaa suunnistamaan eri alueissa. \nVoi hidastaa peliä.",
} as any;

const english = {
  // Identifier
  language_id: "english",
  finnish: "Suomi",
  english: "English",

  // Races
  human_name: "Human",
  orc_name: "Half-Orc",
  elf_name: "Half-Elf",
  ashen_name: "Ashen",

  // Character Window
  core_stats: "Core stats",
  core_resistances: "Core resistances",
  status_resistances: "Status Resists",
  poison_status: "Poison",
  burning_status: "Burning",
  curse_status: "Curse",
  stun_status: "Stun",
  bleed_status: "Bleed",

  str_tt: `<i>${icons["str"]}<i>Strength increases <i>${icons["melee"]}<i>damage with strength scaling weapons by 2%,\n and encumbrance by 0.5`,
  dex_tt: `<i>${icons["dex"]}<i>Dexterity increases <i>${icons["ranged"]}<i>damage with dexterity scaling weapons by 2%`,
  vit_tt: `<i>${icons["vit"]}<i>Vitality increases <i>${icons["health"]}<i>health by 5,\n<i>${icons["regenHp_icon"]}<i>health regeneration by 1%\n and encumbrance by 1`,
  int_tt: `<i>${icons["int"]}<i>Intelligence increases <i>${icons["mana"]}<i>mana by 2,\n<i>${icons["regenMp_icon"]}<i>mana recovery by 1%\n and <i>${icons["damage"]}<i>magical damage by 2%`,
  cun_tt: `<i>${icons["cun"]}<i>Cunning increases <i>${icons["critDamage"]}<i>crit damage by 1.5%,\n and <i>${icons["critDamage"]}<i>crit chance by 0.4%`,
  critDamage_tt: `<i>${icons["critDamage"]}<i>Crit damage is the multiplier that improves crit hits.`,
  critChance_tt: `<i>${icons["critDamage"]}<i>Crit chance increases your chances of achieving critical hits.`,
  hitChance_tt: `<i>${icons["hitChance"]}<i>Hit chance increases the chance of hitting your target. \nCompared to enemy's <i>${icons["evasion"]}<i>evasion.`,
  evasion_tt: `<i>${icons["evasion"]}<i>Evasion increases your chance of avoiding damage. \nCompared to enemy's <i>${icons["hitChance"]}<i>hit chance.`,

  resistances_tt: "Resistance decreases incoming damage of its type by the indicated %.",
  stat_resist_tt: `Status resistance decreases any damage caused by effects by the indicated %. \n\nIt also gives a chance of completely resisting the effect. \n\nWhen effect is resisted, it is not applied at all.`,

  // Status Resists
  poisonDefense: "Poison resistance",
  burningDefense: "Burning resistance",
  curseDefense: "Curse resistance",
  stunDefense: "Stun resistance",
  bleedDefense: "Bleed resistance",

  // Technical stuff
  changeWordOrder: false,
  mana: "mana",
  health: "health",
  str: "Strength",
  dex: "Dexterity",
  vit: "Vitality",
  int: "Intelligence",
  cun: "Cunning",
  crush: "Crushing",
  slash: "Slashing",
  pierce: "Piercing",
  magic: "Magical",
  fire: "Fire",
  ice: "Ice",
  dark: "Dark",
  divine: "Divine",
  lightning: "Lightning",
  crush_def: "Crushing",
  slash_def: "Slashing",
  pierce_def: "Piercing",
  magic_def: "Magical",
  fire_def: "Fire",
  ice_def: "Ice",
  dark_def: "Dark",
  divine_def: "Divine",
  lightning_def: "Lightning",
  hpMax: "Health",
  mpMax: "Mana",
  hitChance: "Hit Chance",
  evasion: "Evasion",
  sight: "Sight",
  increases: "Increases",
  decreases: "Decreases",
  damage: "Damage",
  by: "by ",
  strV: "Strength",
  strP: "Strength%",
  vitV: "Vitality",
  vitP: "Vitality%",
  dexV: "Dexterity",
  dexP: "Dexterity%",
  intV: "Intelligence",
  intP: "Intelligence%",
  hpV: "Health",
  hpP: "Health%",
  mpV: "Mana",
  mpP: "Mana%",
  resistAllV: "All Resistances",
  resistAllP: "All Resistances%",
  hitChanceV: "Hit Chance",
  hitChanceP: "Hit Chance%",
  evasionV: "Evasion",
  evasionP: "Evasion%",
  critChanceV: "Crit Chance",
  critChanceP: "Crit Chance",
  critDamageV: "Crit Damage",
  critDamageP: "Crit Damage",
  status_effect: "Status effect",
  last: "Effect time",
  lasts_for: "Lasts for",
  resist: "Resist",
  silence_text: "You are silenced!",
  silence: "Silences magic!",
  concentration_text: "Your concentration is broken!",
  concentration: "Breaks concentration!",
  heal_power: "Healing Power",
  concentration_req: "Requires Concentration",
  type: "Type",
  ranged: "Ranged",
  requires_melee_weapon: "Requires Melee Weapon",
  requires_ranged_weapon: "Requires Ranged Weapon",
  recharge_only_in_combat: "Recharge Only In Combat",
  targets_self: "Targets Self",
  mana_cost: "Mana Cost",
  use_range: "Use Range",
  damage_multiplier: "Damage Multiplier",
  resistance_penetration: "Resistance Penetration",
  aoe_size: "Area of Effect",
  yes: "yes",
  no: "no",
  tiles: "tiles",
  attack: "Attack",
  heal: "Heal",
  buff: "Buff",
  movement: "Movement",
  charge: "Charge",
  summon: "Summon",
  turn: "Turn",
  turns: "turns",
  cooldown: "Cooldown",
  base_heal: "Base Heal",
  map_to_hotbar: "Map ability/item",
  remove_from_hotbar: "Remove ability/item",
  removed_in: "Removed in",
  deals: "Deals",
  perk_points: "Perk points",
  stat_points: "Stat points",
  adventurerPerks: "Adventurer",
  lvl_up: "You levelled up! Your level is now [LVL]!",
  regenHp: "Health regeneration",
  regenMp: "Mana recovery",

  // Enemy names
  hiisi_name: "Hiisi",
  hiisiWarrior_name: "Hiisi Warrior",
  hiisiHunter_name: "Hiisi Hunter",
  skeletonWarrior_name: "Skeleton Warrior",
  skeletonArcher_name: "Skeleton Archer",
  skeletonMage_name: "Skeleton Mage",
  skeletonLich_name: "Skeleton Lich",
  soulWraith_name: "Soul Wraith",
  greySlime_name: "Grey Slime",
  flamingSlime_name: "Flaming Slime",
  electricSlime_name: "Electric Slime",
  norsemanBerserk_name: "Norseman Berserker",
  norsemanHunter_name: "Norseman Hunter",
  femaleOrcRaider_name: "Orc Raider",
  wildTroll_name: "Wild Troll",
  wildStoneTroll_name: "Wild Stone Troll",
  troll_name: "Troll",
  stoneTroll_name: "Stone Troll",
  enthralledKnight_name: "Enthralled Knight",
  spectralKnight_name: "Spectral Knight",

  // Summon names
  skeletonWarriorSummon_name: "Conjured Skeleton Warrior",
  skeletonLichSummon_name: "Conjured Skeleton Lich",
  stoneTrollSummon_name: "Conjured Stone Troll",
  dummyTarget_name: "Dummy Target",

  // LOG TEXTS
  you: "You",
  recovery_pl: "recovering",
  health_points: "health",
  for: "for",
  death: "dies.",
  damage_from_effect_pl: "<c>yellow<c>You<c>white<c> take [ICON][DMG] damage from [STATUS]!",
  damage_from_effect: "<c>white<c>[TARGET] takes [ICON][DMG] damage from [STATUS].",
  player_death_log: "YOU ARE DEAD...",
  cure_pl: "<c>yellow<c>You<c>white<c> cure yourself!",
  cure: "[ACTOR] cures themself.",
  useConsumable: "<c>yellow<c>You<c>white<c> use a consumable item!",
  moves_to: "moves to tile",


  // WORLD TEXTS
  gained_xp: "Gained [XP] XP!",
  player_death: "YOU WERE KILLED!",

  // Damage types
  poison_damage: "Poison",
  burning_damage: "Burning",

  // Character Creation
  choose_name: "Name",
  choose_race: "Race",
  choose_class: "Class",

  // Misc
  attack_name: "base attack damage",
  cures_statuses: "Cures",
  resistance: "Resistances",
  item_weight: "Weight",
  item_worth: "Worth",
  item_grade: "Grade",
  item_stat_bonus: "Scales with",
  weapon_has_great_reach: "Greater reach than most weapons",
  status_effects: "Status effects",
  encumbrance: "Encumbrance",
  shrine_activated: "Shrine activated!",
  shrine_used: "Shrine's power has already been spent...",
  add_ability: "Grants ability",
  requires: "Requires",
  critChance: "Crit Chance",
  critDamage: "Crit Damage",
  resistAll: "All Resistances",
  uses: "Uses Remaining",
  item_name: "Item name",
  item_type: "Type",
  item_rarity: "Rarity",
  item_weight_title: "Weight",
  item_worth_title: "Worth",
  weapon: "weapon",
  armor: "armor",
  consumable: "consumable",
  artifact: "artifact",
  required_stats: "Required stats",
  active_if: "Active if",
  hp_more_than: "Health more than",
  hp_less_than: "Health less than",
  mp_more_than: "Mana more than",
  mp_less_than: "Mana less than",
  passive: "Passive ability",
  too_much_weight: "You're carrying too much to move! Drop something!",
  summons_unit: "Summons unit",
  summon_level: "Summoned unit level",
  summon_last: "Summoned unit last",
  two_handed_weapon: "Two-handed",
  rooted: "Can't move!",
  closest_enemy: "Distance to closest enemy: ",
  expGain: "Experience gain",

  // Artifacts
  part_of_set: "Part of",
  artifact_def: "Artifact",
  artifact_set: "Artifact Set",
  artifact_two_piece: "2-piece set effect",
  artifact_three_piece: "3-piece set effect",
  defenderSet_name: "Defender",
  guardianSet_name: "Guardian",
  scholarSet_name: "Scholar",
  warriorSet_name: "Warrior",
  loneShadeSet_name: "Lone Shade",

  // Passive abilities
  frenzy_name: "Frenzy",
  heightened_casting_name: "Heightened Casting",
  warrior_instinct_name: "Warrior Instinct",
  confident_shot_name: "Confident Shot",
  blood_rage_1_name: "Blood Rage I",
  blood_rage_2_name: "Blood Rage II",
  reckless_1_name: "Reckless I",
  reckless_2_name: "Reckless II",
  sense_of_danger_1_name: "Danger Sense I",
  sense_of_danger_2_name: "Danger Sense II",
  frantic_mana_recovery_name: "Frantic Mana Recovery",

  // Enemy types
  against_type_syntax: " against ",
  singular_type_slime: "Slime",
  plural_type_slime: "Slimes",
  singular_type_skeleton: "Skeleton",
  plural_type_skeleton: "Skeletons",
  singular_type_barbarian: "Barbarian",
  plural_type_barbarian: "Barbarians",
  singular_type_troll: "Troll",
  plural_type_troll: "Trolls",
  singular_type_hiisi: "Hiisi",
  plural_type_hiisi: "Hiisi creatures",

  // Enemy races
  against_race_syntax: " against ",
  singular_race_elemenal: "Elemental",
  plural_race_elemental: "Elementals",
  singular_race_undead: "Undead",
  plural_race_undead: "Undead",
  singular_race_human: "Human",
  plural_race_human: "Humans",
  singular_race_monster: "Monster",
  plural_race_monster: "Monsters",

  /* MENU */

  menu_resume: "Resume",
  menu_options: "Options",
  menu_save_games: "Save Games",
  menu_main_screen: "Main Menu",
  menu_new_game: "New Game",
  menu_load_game: "Load Game",

  setting_log_enemy_movement: "Log character movement",
  setting_toggle_minimap: "Toggle minimap",
  setting_game_language: "Game language",
  setting_hotkey_inv: "Open inventory screen",
  setting_hotkey_char: "Open character screen",
  setting_hotkey_perk: "Open level up screen",
  setting_hotkey_move_up: "Move up",
  setting_hotkey_move_down: "Move down",
  setting_hotkey_move_left: "Move left",
  setting_hotkey_move_right: "Move right",
  setting_hotkey_interact: "Interact",

  open_menu: "Open game menu [Escape]",

  space_key: "SPACE",

  save_over: "Save over file",
  load_game: "Load game",
  delete_save: "Delete save file",
  create_save: "Create new save",
  create_file: "Save to file (downloads a .txt file)",
  load_file: "Load from file (opens prompt)",

  // Grades
  common: "Common",
  uncommon: "Uncommon",
  rare: "Rare",
  mythical: "Mythical",
  legendary: "Legendary",

  // Statuses
  effect_poison_name: "Poison",
  effect_poison_desc: "Poison courses through your body, \nweakening and harming you.",
  effect_venom_name: "Venom",
  effect_venom_desc: "Venom courses through your body, \nweakening and harming you.",
  effect_rage_name: "Rage",
  effect_rage_desc: "You are slighty upset.",
  effect_berserk_name: "Berserk",
  effect_berserk_desc: "RRAAAAAGHH!!",
  effect_dazed_name: "Dazed",
  effect_dazed_desc: "A blow has left you dazed, \nmaking it much harder to perform any action.",
  effect_blighted_name: "Blighted",
  effect_blighted_desc: "Your very soul is weakened from a vile blight.",
  effect_ward_of_aurous_name: "Ward of Aurous",
  effect_ward_of_aurous_desc: "Feel at ease, Aurous himself is guaranteeing your safety.",
  effect_battle_fury_name: "Fury",
  effect_battle_fury_desc: "You are concentrating on physical might.",
  effect_burning_name: "Burning",
  effect_burning_desc: "YOU ARE ON FIRE!",
  effect_chilled_name: "Chilled",
  effect_chilled_desc: "Your body is cooling down, getting slower, weakening...",
  effect_summoned_name: "Summon",
  effect_summoned_desc: "Your conjuration dies once this expires.",
  effect_disoriented_name: "Disoriented",
  effect_disoriented_desc: "Something has left you delirious, unable to grasp your surroundings properly.",
  effect_dueled_name: "Dueled",
  effect_dueled_desc: "You have been dueled and can no longer back from the fight.",
  effect_sneaky_stabbing_name: "Sneaky Stabbing",
  effect_sneaky_stabbing_desc: "Your ability to hit critical points has been enhanced.",
  effect_smoke_bomb_effect_name: "Smoke Bomb",
  effect_smoke_bomb_effect_desc: "Your sight and power have been compromised by a hazy smoke screen.",

  // Abilities and stuff
  attack_action_desc_pl: "<c>yellow<c>You<c>white<c> connect an attack against [TARGET] and harm them for [DMG] damage.",
  attack_action_desc: "attacks [TARGET], dealing [DMG] damage.",
  focus_strike_name: "Focus Strike",
  focus_strike_desc: "Observe your opponent with precision,\nstriking only at the greatest opening.",
  focus_strike_action_desc_pl: "<c>yellow<c>You<c>white<c> focus on your opponents' mistakes, punishing [TARGET] with [DMG] damage.",
  focus_strike_action_desc: "focus strikes [TARGET] for [DMG] damage.",
  true_shot_name: "True Shot",
  true_shot_desc: "Unleash a precise arrow with all your might,\nstriking your opponent's weak point.",
  true_shot_action_desc_pl: "<c>yellow<c>You<c>white<c> coat an arrow in magic, and cast true shot on [TARGET], dealing [DMG] damage.",
  true_shot_action_desc: "shoots a magic powered arrow at [TARGET], dealing [DMG] damage.",
  first_aid_name: "First Aid",
  first_aid_desc: "Do whatever you can to recover\nfrom slight injuries on the field, ",
  first_aid_action_desc_pl: "perform first aid on your wounds, ",
  first_aid_action_desc: "performs first aid on their wounds, ",
  icy_javelin_name: "Icy Javelin",
  icy_javelin_desc: "Shoot a javelin made of pure ice and magic.",
  icy_javelin_action_desc_pl: "<c>yellow<c>You<c>white<c> form a pike from ice, and cast it towards [TARGET], dealing [DMG] damage.",
  icy_javelin_action_desc: "fires a javelin of ice at [TARGET], dealing [DMG] damage.",
  barbarian_rage_name: "Barbarian Rage",
  barbarian_rage_desc: "Stop thinking and switch to pure offense,\nbolstered by your ability to ignore pain!",
  barbarian_rage_action_desc_pl: "fill your mind with nothing but rage at the bastard enemies you face!",
  barbarian_rage_action_desc: "fills their mind with unyielding rage!",
  berserk_name: "Berserk",
  berserk_desc: "RRRAAAAAAAAAAAAAAAAAAGHHHHH!!!!!!",
  berserk_action_desc_pl: "YOU THROW AWAY ANY THOUGHT OF SELF PRESERVATION, IT'S TIME TO PUT THESE BASTARDS TO SLEEP!!!",
  berserk_action_desc: "GOES COMPLETELY BERSERK, BETTER BE WARY!!",
  shadow_step_name: "Shadow Step",
  shadow_step_desc: "Step in to the shadow, \nto find a new realm.",
  shadow_step_action_desc_pl: "<c>yellow<c>You<c>white<c> use the shadows to your advantage, moving rapidly to your destination.",
  shadow_step_action: "uses the shadows as a boost to get to their destination.",
  retreat_name: "Draw Back",
  retreat_desc: "Scurry away from battle.",
  retreat_action_desc_pl: "<c>yellow<c>You<c>white<c> disengage your foes, covering some ground!",
  retreat_action: "retreats from battle!",
  charge_name: "Charge",
  charge_desc: "Charge wildly at your foe.",
  charge_action_desc_pl: "<c>yellow<c>You<c>white<c> charge at [TARGET], dealing [DMG] damage!",
  charge_action_desc: "charges at [TARGET], dealing [DMG] damage.",
  reap_name: "Reap",
  reap_desc: "Lash out towards a foe.",
  reap_action_desc_pl: "<c>yellow<c>You<c>white<c> charge at [TARGET] intent to reap their soul, dealing [DMG] damage!",
  reap_action_desc: "charges at [TARGET], reaping them for [DMG] damage.",
  purification_name: "Purification",
  purification_desc: "Purify your body of poisons and other maladies.",
  blight_name: "Blight",
  blight_desc: "Blight your foe to weaken them.",
  blight_action_desc_pl: "<c>yellow<c>You<c>white<c> blight [TARGET], dealing [DMG] damage and weakening them!",
  blight_action_desc: "blights [TARGET], dealing [DMG] damage and weakening them.",
  fireball_name: "Fireball",
  fireball_desc: "Incinerate your foes with a flaming ball of destruction.",
  fireball_action_desc_pl: "<c>yellow<c>You<c>white<c> throw a fiery ball towards your foes!",
  fireball_action_desc: "shoots a fireball at [TARGET], burning them for [DMG] damage.",
  fireball_action_desc_aoe_pl: "[TARGET] is burned by the blast, causing [DMG] damage!",
  piercing_mana_bolt_name: "Piercing Bolt of Magic",
  piercing_mana_bolt_desc: "Pierce your foe with pure magic.",
  piercing_mana_bolt_action_desc_pl: "<c>yellow<c>You<c>white<c> fire a mana bolt at [TARGET], dealing [DMG] damage!",
  piercing_mana_bolt_action_desc: "shoots a mana bolt at [TARGET], dealing [DMG] damage.",
  ward_of_aurous_name: "Ward of Aurous",
  ward_of_aurous_desc: "Defend your body with an invincible shield.",
  ward_of_aurous_action_desc_pl: "<c>yellow<c>You<c>white<c> summon the ward of Aurous himself upon your body!",
  ward_of_aurous_action_desc: "defends themself with a magical ward.",
  battle_fury_name: "Battle Fury",
  battle_fury_desc: "Concentrating your anger into a controlled fury \nwill allow you to summon immense power.",
  battle_fury_action_desc_pl: "<c>yellow<c>You<c>white<c> allow a controlled fury to manifest in your mind!",
  battle_fury_action_desc: "commits to a furious offensive.",
  venomous_blow_name: "Venomous Blow",
  venomous_blow_desc: "This attack has a nasty surprise.",
  venomous_blow_action_desc_pl: "<c>yellow<c>You<c>white<c> strike [TARGET] with a sudden blow, dealing [DMG] damage and poisoning them!",
  venomous_blow_action_desc: "poisons [TARGET] with a sudden strike, dealing [DMG] damage.",
  poisoned_arrow_name: "Poisoned Arrow",
  poisoned_arrow_desc: "Death from afar. Slow death.",
  poisoned_arrow_action_desc_pl: "<c>yellow<c>You<c>white<c> shoot a poisonous arrow at [TARGET], dealing [DMG] damage!",
  poisoned_arrow_action_desc: "shoots an arrow coated in poison at [TARGET], dealing [DMG] damage.",
  summon_skeleton_warrior_name: "Summon Skeleton Warrior",
  summon_skeleton_warrior_desc: "Conjure a Skeleton Warrior to protect you.",
  summon_skeleton_warrior_action_desc_pl: "You call Skeleton Warrior to battle!",
  barbarian_charge_name: "Barbarian Charge",
  barbarian_charge_desc: "Recklessly close in on foes.",
  barbarian_charge_action_desc_pl: "<c>yellow<c>You<c>white<c> unleash a fearsome warcry and charge towards [TARGET], dealing [DMG] damage and disorienting them!",
  barbarian_charge_action_desc: "charges at [TARGET] with a ferocious cry, ramming into them for [DMG] damage.",
  chivalrious_blow_name: "Chivalrious Blow",
  chivalrious_blow_desc: "Gracefully strike your foe, tempting them to duel you.",
  chivalrious_blow_action_desc_pl: "<c>yellow<c>You<c>white<c> gracefully strike [TARGET], dealing [DMG] damage and dueling them!",
  chivalrious_blow_action_desc: "masterfully strikes [TARGET], harming them for [DMG] damage and dueling them.",
  challenge_name: "Challenge",
  challenge_desc: "Rush towards your opponent, ready to battle them with honour!",
  challenge_action_desc_pl: "<c>yellow<c>You<c>white<c> rush forwards, looking at [TARGET] while doing so, soon slamming into them for [DMG] damage!",
  challenge_action_desc: "rushes towards [TARGET] while shouting 'I CHALLENGE YOU!', quickly slamming into them for [DMG] damage.",
  sneaky_stabbing_name: "Sneaky Stabbing",
  sneaky_stabbing_desc: "Carefully examine your enemy's body, looking for juicy stabbing targets.",
  sneaky_stabbing_action_desc_pl: "<c>yellow<c>You<c>white<c> enhance your ability to detect weakpoints!",
  sneaky_stabbing_action_desc: "enhances their ability to detect weakspots.",
  smoke_bomb_name: "Smoke Bomb",
  smoke_bomb_desc: "Distract your targets with a well placed smoke screen.",
  smoke_bomb_action_desc_pl: "<c>yellow<c>You<c>white<c> throw a bomb on the ground, quickly filling the area with smoke!",
  smoke_bomb_action_desc_aoe_pl: "[TARGET] is caught in the smoky explosion, taking [DMG] damage!",
  distraction_name: "Hasty Distraction",
  distraction_desc: "Plant a dummy nearby for enemies to target.",
  distraction_action_desc_pl: "You prop a dummy target on the ground!",

  // CLASSES
  fighterClass_name: "Fighter",
  barbarianClass_name: "Barbarian",
  sorcererClass_name: "Sorcerer",
  rogueClass_name: "Rogue",

  // PERKS //

  // SORCERER
  introduction_to_sorcery_name: "Introduction to Sorcery",
  introduction_to_sorcery_desc: "Even the greatest of mages \nmust start somewhere.",
  intent_studies_name: "Intent Studies",
  intent_studies_desc: "Learning is a sign of good fortune.",
  might_of_magic_name: "Might of Magic",
  might_of_magic_desc: "Harness the power of sorcery.",
  spells_of_battle_name: "Spells of Battle",
  spells_of_battle_desc: "In battle only the most simple of spells will act consistently.",
  school_of_fire_name: "The School of Fire",
  school_of_fire_desc: "Your will burns like a great bonfire.",
  molded_by_flame_name: "Molded by Flame",
  molded_by_flame_desc: "Become one with fire.",
  shield_of_ages_name: "Shield of Ages",
  shield_of_ages_desc: "Proper magisters prepare measures against magic.",
  shield_of_aurous_name: "Ward of Aurous",
  shield_of_aurous_desc: "Aurous himself protects you with his warmth.",
  burning_passion_name: "Burning Passion",
  burning_passion_desc: "Your passion for magic is set ablaze!",
  wisdoms_of_the_past_name: "Wisdoms of the Past",
  wisdoms_of_the_past_desc: "Knowledge from the past protects the future.",
  flame_wizard_fury_name: "The Flame Wizard's Fury",
  flame_wizard_fury_desc: "Your foes shall tremble at your flaming fury!",
  makings_of_a_summoner_name: "The Summoner King's Call",
  makings_of_a_summoner_desc: "In order to become a king of magic, one must have servants.",
  magical_bonds_name: "Bonds forged from Magic",
  magical_bonds_desc: "Steel, faith nor gunpowder will stop my puppets!",
  elemental_mage_name: "Master of the Elements",
  elemental_mage_desc: "Elements of nature bend to your will.",
  piercing_javelin_name: "Armour Piercing Javelin",
  piercing_javelin_desc: "This one packs a ton of punch.",

  // FIGHTER
  battle_sense_name: "Battle Sense",
  battle_sense_desc: "After numerous battles, you have developed a keen sense for danger",
  fighters_vitality_name: "Fighter's Vitality",
  fighters_vitality_desc: "Combat necessitates the sturdiest of bodies.",
  patient_blow_name: "Patient Blow",
  patient_blow_desc: "Careful observation is a fighter's greatest asset.",
  strength_training_name: "Strength Training",
  strength_training_desc: "When tactics fail, strength is relied upon.",
  fighting_style_name: "Fighting Style",
  fighting_style_desc: "I fear not the man who has practiced 10 000 blows once, \nbut I fear the man who has practiced one blow 10 000 times.",
  furious_assault_name: "Furious Assault",
  furious_assault_desc: "Nothing will be gained without a hearty offensive!",
  tactical_genius_name: "Tactical Genius",
  tactical_genius_desc: "Keeping a calm mind in the midst of battle grants one an immense advantage.",
  resistant_in_melee_name: "Resistant in Melee",
  resistant_in_melee_desc: "Developing keen sense of the melee allows you to avoid some blows.",
  charging_bull_name: "Charging Bull",
  charging_bull_desc: "The enemy will be disoriented by a sudden frontal charge!",
  concentrated_warrior_name: "Balanced Warrior",
  concentrated_warrior_desc: "Combining patience with unrelenting offense fells all evils.",

  // ROGUE
  way_of_the_rogue_name: "Way of the Rogue",
  way_of_the_rogue_desc: "Fight from the shadows, never risking your skin!",
  weakpoint_spotter_name: "Weakpoint Spotter",
  weakpoint_spotter_desc: "Strike only at the most opportune moment.",
  shadow_warrior_name: "Shadow Warrior",
  shadow_warrior_desc: "Keep your distance from the foe.",
  fighting_dirty_name: "Fighting Dirty",
  fighting_dirty_desc: "Honor and fairness are excellent ways to get killed.",
  glass_cannon_name: "Glass Cannon",
  glass_cannon_desc: "Make every blow count, for they could be the last.",
  ranged_expert_name: "Ranged Expert",
  ranged_expert_desc: "Pelt them with arrows.",
  poison_specialist_name: "Poison Specialist",
  poison_specialist_desc: "Poison can always be relied upon.",
  simple_strokes_name: "Simple Strokes",
  simple_strokes_desc: "Become a well tuned killing machine.",
  dance_of_death_name: "Dance of Death",
  dance_of_death_desc: "No amount of struggling will stop me!",
  poison_from_afar_name: "Filthy Marksman",
  poison_from_afar_desc: "I'll just stay safe here while you die over there.",
  quicker_draw_name: "Quicker Draw",
  quicker_draw_desc: "Faster, faster!",
  smoke_screen_name: "Smoke Screen",
  smoke_screen_desc: "Deprive your foes of their senses.",
  sneakier_stabbing_name: "Sneakier Stabbing",
  sneakier_stabbing_desc: "Exploit your opponents allergy to multiple stab wounds.",
  smoke_and_mirrors_name: "Smoke & Mirrors",
  smoke_and_mirrors_desc: "That's all it takes to fool even the sane.",
  tricky_distraction_name: "Tricky Distraction",
  tricky_distraction_desc: "Make your foes go after the wrong target.",
  poison_taster_name: "Poison Taster",
  poison_taster_desc: "Can't accidentally poison yourself if you do it intentionally!",

  // BARBARIAN
  thrill_of_battle_name: "Thrill of Battle",
  thrill_of_battle_desc: "Revel in your lust for combat.",
  weapon_mastery_name: "Weapon Mastery",
  weapon_mastery_desc: "What good is strength if you can't use it?",
  raging_charge_name: "Raging Charge",
  raging_charge_desc: "Sometimes the deciding factor is a frontal assault.",
  hardened_constitution_name: "Hardened Constitution",
  hardened_constitution_desc: "Living in tribes toughens the body.",
  power_of_injuries_name: "Power through Injury",
  power_of_injuries_desc: "Pain is a reminder that you are still alive!",
  sharp_senses_name: "Sixth Sense",
  sharp_senses_desc: "Put your life in the line and you'll accomplish heroic deeds.",
  perk_barbarian_rage_name: "Raging",
  perk_barbarian_rage_desc: "Rage, fury and anger are all necessary emotions in the wild!",
  impatient_name: "Impatient",
  impatient_desc: "Hurry it up, I need to FIGHT!",
  ultimate_warrior_name: "Ultimate Warrior",
  ultimate_warrior_desc: "I win because I place victory before survival!",
  unyielding_rage_name: "Continuous Rage",
  unyielding_rage_desc: "This rage is unyielding, it consumes me!",

  // ADVENTURER
  hearty_adventurer_1_name: "Hearty Adventurer I",
  hearty_adventurer_1_desc: "Toughening up.",
  hearty_adventurer_2_name: "Hearty Adventurer II",
  hearty_adventurer_2_desc: "Toughening up.",
  hearty_adventurer_3_name: "Hearty Adventurer III",
  hearty_adventurer_3_desc: "Toughening up.",
  hearty_adventurer_4_name: "Hearty Adventurer IV",
  hearty_adventurer_4_desc: "Toughening up.",
  hearty_adventurer_5_name: "Hearty Adventurer V",
  hearty_adventurer_5_desc: "Toughening up.",
  first_aid_expert_name: "First Aid Expert",
  first_aid_expert_desc: "Good vibes.",
  cleanser_name: "Cleanser",
  cleanser_desc: "Better vibes.",
  advancing_backwards_name: "Advancing Backwards",
  advancing_backwards_desc: "Bravely running away.",

  // NECROMANCER
  pursuit_of_undeath_name: "Pursuit of Undeath",
  pursuit_of_undeath_desc: "Pursuing undeath.",

  // Settings tooltips
  log_char_movement: "<f>16px<f>Logs enemy movement in the text area every turn. \nCan clutter the text screen.",
  toggle_minimap: "<f>16px<f>The minimap helps with navigating through areas. \nCan cause the game to run slower.",
} as any;